### ISSUE TITLE
Support for custom logical writers

### ISSUE THREAD

**Issue by Artimi** [fastavro/fastavro#173]
Hello,
I have a proposal to add more options for adding our own logical writers/readers. Right now I'm adding my own logical writer reader capability by adding necessary functions to dicts `LOGICAL_WRITERS` and `LOGICAL_READERS` like this:
```python
class NanoTime:
    ''' Times with precisions to nanoseconds '''
    __init__(self, nanoseconds):
      # number of nanoseconds since epoch
       self.nanoseconds
   ...

import fastavro

def read_nanotime(data, writer_schema = None, reader_schema = None):
	return NanoTime(data)

def prepare_nanotime(data, schema):
	if isinstance(data, NanoTime):
		return data.nanoseconds
	else:
		return data

fastavro.read.LOGICAL_READERS['long-nano-time'] = read_nanotime
fastavro.write.LOGICAL_WRITERS['long-nano-time'] = prepare_nanotime
```
This works well so I can use schemata like this:
```
{
  "name": "Time:1",
  "doc": "Time represented as nanoseconds since epoch.",
  "namespace": "common",
  "type": "long",
  "logicalType": "nano-time"
}
```
This might seem like a hack but it is working pretty good because we always use our wrapper library to parse fastavro payload. So it is seamless for us. However, when we use schema `common.Time:1` in `union` we cannot use it directly. When I use schema like:
```
[null, "common.Time:1"]
```
then when we use as a value
```
NanoTime(0)
```
It fails on
```
ValueError: NanoTime(nanoseconds = 1495610391000000000) (type <class 'NanoTime'>) do not match ['null', 'common.Time:1']
```
This is happening because all checks for logical writers in `fastavro._write.validate` are hardcoded:
```
    if record_type == 'long':
        return (
            (isinstance(datum, (int, long,)) and
             LONG_MIN_VALUE <= datum <= LONG_MAX_VALUE) or
            isinstance(datum, (
                datetime.time, datetime.datetime, datetime.date))
        )
```
To resolve this I suggest to prepare data here in `validate` like this:
```
   logical_type = schema.get('logicalType')
   ...
    if record_type == 'long':
       if logical_type is not None:
            datum = LOGICAL_WRITERS[logical_type](datum, schema)
        return (
            (isinstance(datum, (int, long,)) and
             LONG_MIN_VALUE <= datum <= LONG_MAX_VALUE))
        )
```
It would add another calling of `prepare_` functions but on the other hand we would get rid of one `isinstance` call and it would be useful for adding custom logical types. Also the code would be more flexible because information about logical types (like `datetime.date`) would not be on multiple places. What do you think about this? I'm willing to make a PR if you are not against.

**Comment by rhaarm** [comment]
@artimi I think we are both into the same situation. #172 relates to this, I'm planning to rip out validation from a single function and push it into individual functions per-type just like the logical readers and writers then write a new validation function to use that dictionary look up.

**Comment by scottbelden** [comment]
I think the idea of custom logical types is a neat one, but I'd be hesitant to add it as it's not part of the avro specification. I'll try to take some time to more closely look at what you have written above and give some further thoughts in a day or two.

**Comment by todpunk** [comment]
Custom logical types are in fact part of the spec.  The spec doc does leave some room for interpretation, but the official sources have this: https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/LogicalType.java#L25

On top of that, several tools generate logical types that aren't part of the spec (such as some CDC tools that will have a "varchar" logical type with a base type of string for fields in the database that are varchar, differentiating them from TEXT columns which can be useful distinction while not changing the underlying data type.) . Avro Tools jar will work on these scenarios as expected in the spec (ignore logicaltype, use underlying type).

**Comment by scottbelden** [comment]
I think having a clean interface in fastavro where people can register handlers for custom logical types makes sense. Basically what @Artimi did with 

```python
fastavro.read.LOGICAL_READERS['long-nano-time'] = read_nanotime
fastavro.write.LOGICAL_WRITERS['long-nano-time'] = prepare_nanotime
```

But just more polished and supported. I'll try to come up with something while I'm at PyCon unless someone gets to it first.

**Comment by rhaarm** [comment]
@scottbelden  I just noticed that `write_union` calls `validate`, which would break some of this logic if we don't update `validate`. I've already had on my list of things to do of updating adding custom and descriptive validators per known type, since that's what's already happening with the current `validate` implementation but with if conditions.

**Comment by scottbelden** [comment]
Ah, yes, it seems like we would need to break `validate` into functions per type so that a validator could be updated.

**Comment by Artimi** [comment]
Hi again. I tried this again and found a way how to accomplish the validation. You only need to prepare the datum with `LOGICAL_WRITERS` you can take a look in a provisional PR I made https://github.com/fastavro/fastavro/pull/349/. It works ok with the two attached tests so I would be perfectly happy with this solution. The tests are not only failing (on the original code) in with custom logical writers but even for the built-ins. 
The only problem is that `LOGICAL_WRITERS` cannot be imported from `_validation.pyx` because it is from `_write.pyx` and that imports `_validation.pyx` which creates circular reference and fails at import time. I'm thinking about moving `LOGICAL_WRITERS` with all its function to another module (maybe `_logical_writers.pyx` and `_logical_writers_py.py`?). What do you think about this solution? Will you merge it if I prepare it?

**Comment by scottbelden** [comment]
I'll try to take a closer look when I have a bit of free time. Hopefully buy this weekend at the latest.

**Comment by Artimi** [comment]
I've moved `LOGICAL_WRITERS` to `_logical_writers.pyx` as announced before. Please take a look at the code and let me whether this is an acceptable way.

**Comment by scottbelden** [comment]
Resolved via https://github.com/fastavro/fastavro/pull/349

**Comment by Artimi** [comment]
@scottbelden Thanks for the cooperation!

**Comment by scottbelden** [comment]
Thank you for all your work!
