### ISSUE TITLE
How to handle multiple versions in the same memory?

### ISSUE THREAD

**Issue by rhaarm** [fastavro/fastavro#185]
I writing a Kafka Producer/Consumer and realized that `SCHEMA_DEFS,WRITERS,READERS` stores the schema for the known namespace.name. What happens when you have a running services that pulls a new version change from Schema Registry? Will `acquaint_schema` override the previously existing version?

https://github.com/tebeka/fastavro/blob/master/fastavro/_schema_py.py#L71
Looking here, it looks like it would override the previous. So I guess if versions change, I just need to run acquaint each time. I'm trying to wrap some caching around this, but it doesn't look like I can do any caching around version differences. Also, it seems the caching will need to be aware of which version is currently active in fastavro WRITERS.

**Comment by scottbelden** [comment]
Yes, if you have a schema `Foo` that gets added to one of those schema mappings you mentioned and then later have another schema `Foo`, it will overwrite the first one. You can see some history behind this in https://github.com/tebeka/fastavro/pull/34.

There has been an [open issue about caching ](https://github.com/tebeka/fastavro/issues/67) but it never got much traction and so not much thought has been put into it. As mentioned in that issue, if caching were to be explored more it would be necessary to do some profiling to see how much time it would save and what the costs are.

**Comment by scottbelden** [comment]
I believe this might be resolved by https://github.com/fastavro/fastavro/pull/451. There is no longer the global `SCHEMA_DEFS` and now those schema definitions do not clobber each other in a global cache.
