### ISSUE TITLE
Ambiguous records are a problem in fastavro

### ISSUE THREAD

**Issue by scottbelden** [fastavro/fastavro#191]
Consider the following example:

```python
from io import BytesIO
import fastavro

schema = {
    "type": "record",
    "name": "Test",
    "namespace": "test",
    "fields": [{
        "name": "foo",
        "type": [
            {
                "type": "record",
                "name": "subrecord1",
                "fields": [{
                    "name": "sub_int",
                    "type": "int",
                }],
            },
            {
                "type": "record",
                "name": "subrecord2",
                "fields": [{
                    "name": "sub_int",
                    "type": "int",
                }],
            },
        ]
    }]
}

record = {'foo': ('subrecord2', {'sub_int': 42})}

fo = BytesIO()
fastavro.write.schemaless_writer(fo, schema, record)
binary1 = fo.getvalue()
fo.seek(0)
new_record = fastavro.read.schemaless_reader(fo, schema)

fo = BytesIO()
fastavro.write.schemaless_writer(fo, schema, new_record)
binary2 = fo.getvalue()

print(binary1)  # prints b'\x02T'
print(binary2)  # prints b'\x00T'

assert binary1 == binary2  # AssertionError is raised

```

In the first encoding, the we will choose the `subrecord2` schema (because the tuple format forces us to do that). However, when we read that binary in and try to write it back out, we lose the fact that the type is `subrecord2` and we have to guess the type. We guess wrong (because the schemas for `subrecord1` and `subrecord2` are the same) and write the binary by choosing `subrecord1`.

This could cause inter-language issues. For example, if a java process writes the binary as a `subrecord2` type, sends it to a python process for modifications, and then python sends it back, it will now be a `subrecord1` type. This is because on the python side they are both just typeless dictionaries internally.

One way to solve this could be to have an optional attribute on the dictionary or some special key like `_fastavro_type`. The key would need to be unique enough that we don't expect it to collide with a schema that could define the same key. If `avro` provided some reserved namespace we could use that, but as far as I know they don't.

**Comment by scottbelden** [comment]
If we add some `_fastavro_type` or `_record_type` we will probably want to create some helper function that reads that key rather than having users read it directly. This could give us more flexibility in the naming of the key or how exactly it is stored.

**Comment by scottbelden** [comment]
Also it's worth noting that the official python libraries in apache/avro don't have any way of handling this currently and so their python libraries suffer from the same problem.

**Comment by netrounds-fredrik** [comment]
I have detected this problem as well, both with the official python library and fastavro. At least fastavro has a way to select the union branch when encoding by using the tuple representation as in the example above. The official library doesn't even have that.

To me, the obvious solution would be to let the reader represent a union in the same way as the writer, using a tuple. This would also work for primitive types (https://github.com/fastavro/fastavro/blob/c3d24640feb21f9519fdbe7cda144ac6b169ca5c/tests/test_fastavro.py#L1175) and wouldn't require hacking hidden attributes into a dict. To make such a change backward compatible, an optional flag can be added to the `reader` and `schemaless_reader` functions.

Alternatively, the JSON representation should be used both for reading and writing, where the branch is represented as a nested object/dict. This will also require an optional flag or a new set of functions for backward compatibility.

**Comment by scottbelden** [comment]
I believe this was resolved in https://github.com/fastavro/fastavro/pull/370. There is a `return_record_name` that can be set to `True`. When `True`, a union will be decoded as a tuple of the record name and the record.
