### ISSUE TITLE
fastavro license clarification

### ISSUE THREAD

**Issue by ian-whitestone** [fastavro/fastavro#222]
Hey folks,

Just wondering what license `fastavro` is meant to have. I see mention of an Apache license in [Notice.txt](https://github.com/fastavro/fastavro/blob/master/NOTICE.txt), but reference to an MIT license in [setup.py](https://github.com/fastavro/fastavro/blob/master/setup.py#L64)

thanks to @theianrobertson for pointing this out.

**Comment by scottbelden** [comment]
I'm going to preface this with saying that I am not a lawyer and certainly not an expert on software licensing.

The [Notice.txt](https://github.com/fastavro/fastavro/blob/master/NOTICE.txt) predates my time with this project, but I believe it is there to satisfy [this requirement](https://github.com/apache/avro/blob/master/LICENSE.txt#L107-L122) of a derivative work under the apache license.

Personally I would argue at this point that this library isn't a derivative work and is vastly different than the python libraries in the apache/avro repository, but in the beginning there might have been some source code copying and so perhaps that would make it a derivative work...

The license [seems to grant the ability to re-license under a different license](https://github.com/apache/avro/blob/master/LICENSE.txt#L124-L129) so I would say that the MIT license is correct for `fastavro`.

@tebeka can feel free to chime in with any additional information.

**Comment by tebeka** [comment]
Also not a lawyer :)

As far as I recall I place `NOTICE.txt` since Avro (the format) is under Apache licence. I placed fastavro under MIT license and IMO both are compatible.

@scottbelden Can do whatever he decides with it :)

**Comment by theianrobertson** [comment]
What about adding an explicit MIT license file in here to clear it up a bit?  Like in a `LICENSE` file?([example](https://github.com/pytest-dev/pytest/blob/master/LICENSE))

**Comment by scottbelden** [comment]
@theianrobertson That's definitely a good idea. I'll add that in.

**Comment by ian-whitestone** [comment]
thanks @scottbelden

**Comment by theianrobertson** [comment]
Thanks so much for the fast(avro) turnaround!
