### ISSUE TITLE
extract_named_schemas_into_repo broken in 0.19.9

### ISSUE THREAD

**Issue by kkirsanov** [fastavro/fastavro#235]
```python
import fastavro

schema_0 = {
    "name": "UUID",
    "namespace": "rfi.type",
    "type": "string",
    "logicalType": "uuid"
}

schema_1 = {
    "name": "meta",
    "namespace": "rfi.transport",
    "type": "record",
    "fields": [
        {
            "name": "trace_id",
            "type": "rfi.type.UUID"
        },
    ]
}

fastavro.acquaint_schema(schema_0)
fastavro.acquaint_schema(schema_1)
```
works on fastavro <=0.19.8 but  on 0.19.9:

```fastavro._schema_common.UnknownType: rfi.type.UUID```

**Comment by kkirsanov** [comment]
Will it be correct to replace
```if schema_type in NAMED_TYPES:```
with
```if schema_type in NAMED_TYPES or schema_type in PRIMITIVES:```
in https://github.com/fastavro/fastavro/commit/ee4ae0f8c42fb553f0f895cef91cee2cb8823ccd#diff-84ec1a9e64059d66a3b97c48568029b3R99 ?

@scottbelden

**Comment by scottbelden** [comment]
The specification says that [only records, enums, and fixed are named types](https://avro.apache.org/docs/1.8.2/spec.html#names). Your example shows a case where `fastavro` was too lenient in the past. For example, the main apache avro implementation throws a similar error:

```python
import avro.schema
import json

schemas = [{
    "name": "UUID",
    "namespace": "rfi.type",
    "type": "string",
    "logicalType": "uuid"
}, {
    "name": "meta",
    "namespace": "rfi.transport",
    "type": "record",
    "fields": [
        {
            "name": "trace_id",
            "type": "rfi.type.UUID"
        },
    ]
}]

avro.schema.Parse(json.dumps(schemas))
# avro.schema.SchemaParseException: Unknown named schema 'rfi.type.UUID', known names: ['rfi.transport.meta'].
```

**Comment by kkirsanov** [comment]
So, if I have 10 numbers  with a fixed point in a record then I have to do 10 times:
```
    "name":"xxxx",
    "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 18,
        "scale": 3
      },
```

It doesn't sound good.
