### ISSUE TITLE
Test breaks after 0.21.0

### ISSUE THREAD

**Issue by chobeat** [fastavro/fastavro#244]
This is my message:
`{'is_error': True, 'outcome': {'errors': {'field_1': 'some_message', 'field_2': 'some_other_message'}}}`

and this is my schema

`
{'namespace': 'test.avro.training', 'name': 'SomeMessage', 'type': 'record',
 'fields': [{'name': 'is_error', 'type': 'boolean', 'default': False}, {'name': 'outcome', 'type': [
     {'type': 'record', 'name': 'SomeMessage',
      'fields': ... some fields for the success case...
     {'type': 'record', 'name': 'ErrorRecord', 'fields': [
         {'name': 'errors', 'type': {'type': 'map', 'values': 'string'},
          'doc': 'Map containing the errors produced by an operation. The key is the error qualifier (usually connected to an input or output field related to the error) and the value is an error message with further details.'}]}]}]}`

When I serialize to avro and then deserialize, this is the error I get:

> fastavro/_read.pyx:424: SchemaResolutionError

with the reader and writer schema dumped.

This is the line that creates the problems:

`bytes_to_records(
messages_to_bytes([error_message], analysis_completed_schema),
analysis_completed_schema
)`

so I'm 100% sure the schemas are the same because they are the same python object and because it always worked.

**Comment by scottbelden** [comment]
Thanks for the report! This is somewhat related to https://github.com/fastavro/fastavro/issues/239. I'll try to get a fix out soon. I think a workaround for the moment is to call `reader` without supplying a `reader_schema`.

**Comment by scottbelden** [comment]
Added a PR with a failing test here: https://github.com/fastavro/fastavro/pull/245

**Comment by chobeat** [comment]
yeah I thought it was related but I wasn't sure.
