### ISSUE TITLE
Publish .whl files for macOS

### ISSUE THREAD

**Issue by ryan-williams** [fastavro/fastavro#253]
Ported from @aaltay's [comment on BEAM-4749](https://issues.apache.org/jira/browse/BEAM-4749?focusedCommentId=16547313&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16547313)

it sounds like using fastavro in Beam would be smoother if `.whl` files were published for macOS, as they already are for Linux/Windows

I'm not super familiar with this topic, but wanted to get the discussion started; does that proposal make sense?

**Comment by scottbelden** [comment]
Makes sense and hopefully it should just be a line or two in the travis file to have travis build both linux and mac versions. I'll try to play around with this shortly.

**Comment by scottbelden** [comment]
@ryan-williams The wheels should be up. I haven't actually tried installing from them so hopefully you can let me know if they work.

**Comment by aaltay** [comment]
Thank you @scottbelden and @ryan-williams.
