### ISSUE TITLE
TypeError: encoding without a string argument

### ISSUE THREAD

**Issue by IceS2** [fastavro/fastavro#259]
I'm writting a few records to avro, but on one specífic record I'm getting the following error
```
In [45]: writer(avro_buffer, parsed_schema, [json_message])
------------------------------------------------------------------------
TypeError                              Traceback (most recent call last)
<ipython-input-45-bd914c8464ad> in <module>()
----> 1 writer(avro_buffer, parsed_schema, [json_message])

fastavro/_write.pyx in fastavro._write.writer()

fastavro/_write.pyx in fastavro._write.Writer.write()

fastavro/_write.pyx in fastavro._write.write_data()

fastavro/_write.pyx in fastavro._write.write_record()

fastavro/_write.pyx in fastavro._write.write_data()

fastavro/_write.pyx in fastavro._write.write_record()

fastavro/_write.pyx in fastavro._write.write_data()

fastavro/_write.pyx in fastavro._write.write_record()

fastavro/_write.pyx in fastavro._write.write_data()

fastavro/_write.pyx in fastavro._write.write_utf8()

fastavro/_six.pyx in fastavro._six.py3_utob()

TypeError: encoding without a string argument
```

Does anybody have any idea of why is this error arising? thanks!

**Comment by scottbelden** [comment]
Can you try calling `fastavro.validate(parsed_schema, json_message)` (note `validate` takes in a single record, not a list of them) and see if it gives a more helpful error of where the problem is?

I've seen this type of problem when the data is supposed to be a string but it's actually some other type. The `writer` by default doesn't do much validation on the data so if the wrong data type is used it can blow up like this.

**Comment by IceS2** [comment]
Thanks for your help. That was the case!
Someone made a minor change to a schema I consumed!

**Comment by scottbelden** [comment]
By the way, when you call `writer` you can specify `validator=True` to have validation done. However, there is a cost associated with it and so it can be expensive if you are processing lots of records. Another option would be to validate when there is an exception with something like:

```python
try:
    writer(...)
except Exception as e:
    validate(...)
    # Maybe also raise the original exception if validate passes or just for posterity
```
