### ISSUE TITLE
Write avro files with Pyspark

### ISSUE THREAD

**Issue by argenisleon** [fastavro/fastavro#264]
Hi,
Any hint about how to save a Spark dataframe as avro files?

**Comment by scottbelden** [comment]
I'm not familiar with Spark or what would be involved to make this work. Do you know what would be needed?

**Comment by rhaarm** [comment]
You could look at how dask handles it https://github.com/rmax/dask-avro/blob/master/README.rst 

Another thought, I would suggest using parquet as it's best option IMO for spark dataframes and it's built-in with `df.write.parquet`

**Comment by scottbelden** [comment]
@argenisleon Did you see my question? I have a feeling this request will be out of scope for this library, but I'd be interested in hearing more about the changes that would be necessary.

**Comment by argenisleon** [comment]
Hi @scottbelden.
Thanks for the follow-up. 
I am not very familiar with the Spark API and how to handle custom data formats. I find this for reading Avro files. [https://stackoverflow.com/questions/29759893/how-to-read-avro-file-in-pyspark](https://stackoverflow.com/questions/29759893/how-to-read-avro-file-in-pyspark).

I end up using a Spark library for handling the Avro files.

**Comment by scottbelden** [comment]
Okay. I'm going to close this as out of scope for this library. It seems like there is already a tool that will do the conversion. The tool appears to be written in Java and so while a python version of that tool would probably be more useful for you, I feel like that should probably exist as a separate utility.
