### ISSUE TITLE
Load schema definition from an existing avro file

### ISSUE THREAD

**Issue by alexflint** [fastavro/fastavro#271]
How can I load a schema definition from an avro file using fastavro?

**Comment by scottbelden** [comment]
What do you mean by "load"?

If you just want to see what schema was used when writing the avro file you could do the following:

```python
import fastavro

with open("file.avro", "rb") as fp:
    print(fastavro.reader(fp).writer_schema)
```

**Comment by scottbelden** [comment]
@alexflint Did you see my comment? Can you expand on what you are asking?

**Comment by scottbelden** [comment]
I'm going to close this as I haven't heard back. Feel free to reopen or make a new issue if you have more details.
