### ISSUE TITLE
UnionSchema deduction is too permissive

### ISSUE THREAD

**Issue by scottbelden** [fastavro/fastavro#272]
See https://issues.apache.org/jira/browse/AVRO-2226.

We have the same problem.

This test case currently fails:

```python
def test():
    schema = [{
         "type": "record",
         "name": "A",
         "fields": [{"name": "foo", "type": ["string", "null"]}]
        },
        {
         "type": "record",
         "name": "B",
         "fields": [{"name": "bar", "type": ["string", "null"]}]
        },
        {
         "type": "record",
         "name": "AOrB",
         "fields": [{"name": "entity", "type": ["A", "B"]}]
        }]

    datum_to_read = {'entity': {'foo': 'this is an instance of schema A'}}

    assert [datum_to_read] == roundtrip(schema, [datum_to_read])
```

**Comment by scottbelden** [comment]
PR to the avro repo (which probably will never get merged as they don't seem to merge anything) is here: https://github.com/apache/avro/pull/331

We can probably do a similar check for the field names.

**Comment by akellehe** [comment]
@scottbelden today I'm mulling over maintaining my own fork of the python project... I'm considering whether or not I'll be able to provide long term support. 

Here is the PR with the fix in place if you want to cherry pick over to yours for now (you can also find the patch on the jira issue) https://github.com/akellehe/avro/tree/AVRO-2226-union-schema-is-too-permissive. Would you please vote for this issue (in jira) if it effects you?

**Comment by scottbelden** [comment]
@akellehe The python versions that apache has seem basically dead. I don't think they have had any updates in two or three years because I don't think any of the maintainers know Python. Maybe the person who used to do the Python parts left... I'm not sure. If you depend on those and don't want to or can't switch to `fastavro` I would say forking that is the only option. There have been numerous python PRs that are reasonable and just sit there without any interaction from maintainers.

Assuming I have a log in, I can vote for it, but I doubt it will matter. I plan to incorporate your change here (even though I haven't personally run into the issue) because it is not handled correctly by this library either.
