### ISSUE TITLE
scale is optional per Avro spec.

### ISSUE THREAD

**Issue by hfaouaz** [fastavro/fastavro#282]
My schema had no scale in decimal logical type, and fastavro throws an error  as such:

File "fastavro/_read.pyx", line 187, in fastavro._read._read_decimal
KeyError: 'scale'

Per avro 1.8 specs:  

"scale, a JSON integer representing the scale (optional). If not specified the scale is 0."

**Comment by scottbelden** [comment]
Thanks. https://github.com/fastavro/fastavro/pull/283 should resolve this.
