### ISSUE TITLE
if date is jan 1 year 1, we get ValueError: ordinal must be >= 1

### ISSUE THREAD

**Issue by hfaouaz** [fastavro/fastavro#284]
It looks like the code in _read_py.py doesn;t handle year 1 correctly.

def read_date(data, writer_schema=None, reader_schema=None):
    return datetime.date.fromordinal(data + DAYS_SHIFT)

I had to update the code to check if the ordinal difference is less than 1 then set to year one.
if diff <1:
    d = -719162 #year one ordinal value
Is this an issue with datetime or fastavro implementation on handling year 1.

**Comment by scottbelden** [comment]
What is the value of `data` you are trying to use? Can post a script that will produce the stack trace since I'm having trouble getting it to error?

**Comment by hfaouaz** [comment]
print(datetime.date.fromordinal(-719164 + DAYS_SHIFT))

**Comment by scottbelden** [comment]
`-719164` translates to two days before Jan 1, 0001. Jan 1 is `-719162`:

```python
print(datetime.date.fromordinal(-719162 + DAYS_SHIFT))
# 0001-01-01
```

**Comment by hfaouaz** [comment]
you are correct sir!  I guess our translation is wrong. my bad.  thanks for the clarification.

**Comment by ychaparala** [comment]
actually, if both calendars are used Greogrian and Julian calendar to generate the date, year 1 becomes -719164.  should that be an option to read the avro file, provide the calendar or calendars?

**Comment by scottbelden** [comment]
The ISO 8601 standard for dates uses the Gregorian calendar so I'm going to say that Julian is not supported. If this is important for you, it might be better to bring it up as a change to the Avro specification. At the moment when using a `date` logical type there is no extra field to specify the type of calendar and that would have to be included in the avro specification to be added here.
