### ISSUE TITLE
logical type time_micros  failing since its outside of range

### ISSUE THREAD

**Issue by hfaouaz** [fastavro/fastavro#285]
reading a logical time micro, if the time is midnight, the time conversion fails in, 
def read_time_micros(data, writer_schema=None, reader_schema=None):

example:
data = 87741000000    #( 00:22:21 )

h = int(data / MCS_PER_HOUR)
m = int(data / MCS_PER_MINUTE) % 60
s = int(data / MCS_PER_SECOND) % 60
mcs = data % MCS_PER_SECOND
print(datetime.time(h, m, s, mcs))

Also, there is no way to set the timezone.

Note:  I believe this is due to providing a UTC offset.  Once time in micro is converted the result need to be offset.  I am still debugging it.

**Comment by kkirsanov** [comment]
According to http://avro.apache.org/docs/1.8.2/spec.html#Time+%28microsecond+precision%29 : The time-micros logical type represents a **time of day**, with **no reference to a particular calendar, time zone or date**, with a precision of one microsecond.

So the behavior of fastavro seems quite correct to me. How time of day can be greater than 24h?

**Comment by scottbelden** [comment]
I agree with @kkirsanov that the spec says that a `time-mircos` should not be aware of the timezone. Did you perhaps intend to use `timestamp-micros` which does factor in a timezone?
