### ISSUE TITLE
Issue when writing data to file. 

### ISSUE THREAD

**Issue by Code-nomad** [fastavro/fastavro#286]
When I pump data over from a csv to a dataframe all goes well but if I try to use fastavro to produce a file from this I get a stack trace saying there are encoding issues. 

`df = pd.read_csv(filename, sep='|', header=None, names=field_names)

print(field_names)

\# Create and parse schema
schema = {
       'doc': 'Dummy',
       'type': 'record',
       'name': 'sampleAvro',
       'namespace': 'AVRO',
       'fields': fields
   }

parsed_schema = parse_schema(schema)

\# convert pandas dataframe to dictionary
dictionary = df.to_dict('records')

\#print(dictionary)
print(parsed_schema)
\# Write dict to avro file

with open('example.avro', 'wb') as out:
    writer(out, parsed_schema, dictionary)
`

I get the following stacktrace: 

`    writer(out, parsed_schema, dictionary)
  File "fastavro/_write.pyx", line 719, in fastavro._write.writer
  File "fastavro/_write.pyx", line 686, in fastavro._write.Writer.write
  File "fastavro/_write.pyx", line 535, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 472, in fastavro._write.write_record
  File "fastavro/_write.pyx", line 513, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 316, in fastavro._write.write_utf8
  File "fastavro/_six.pyx", line 22, in fastavro._six.py3_utob
TypeError: encoding without a string argument`

This is a sample of data I am loading, 

`ANDO|20|00204|19970729|19970729|0|0
TERI|334|03345|20160518|20160518|1728|0`

The schema object has this content upon writing:

`{
  'type': 'record',
  'name': 'AVRO.sampleAvro',
  'fields': [{
    'name': 'C7B1CD',
    'type': 'string'
  }, {
    'name': 'C7SQN2',
    'type': 'int'
  }, {
    'name': 'C7X2CB',
    'type': 'string'
  }, {
    'name': 'C7AADT',
    'type': 'int'
  }, {
    'name': 'C7ABDT',
    'type': 'int'
  }, {
    'name': 'C7AATM',
    'type': 'int'
  }, {
    'name': 'C7ABNB',
    'type': 'int'
  }],
  '__fastavro_parsed': True
}`

the dict looks something like this:

`[{
  'C7B1CD': 'ANDO',
  'C7SQN2': 20,
  'C7X2CB': 204,
  'C7AADT': 19970729,
  'C7ABDT': 19970729,
  'C7AATM': 0,
  'C7ABNB': 0
}, {
  'C7B1CD': 'TERI',
  'C7SQN2': 334,
  'C7X2CB': 3345,
  'C7AADT': 20160518,
  'C7ABDT': 20160518,
  'C7AATM': 1728,
  'C7ABNB': 0
}]`

**Comment by Code-nomad** [comment]
Can someone assist me on how to fix this?

**Comment by scottbelden** [comment]
There are a few ways to try to better understand what the problem is. One way is to call `writer` with the keyword `validator=True` or you can use `fastavro.validation.validate_many(records, schema)`. Both of these do more thorough validation but there is a cost to running them which is why they aren't done by default.

In any case, they should help identify the problem which is that your schema defines the field `C7X2CB` as a string, but the values it has in the records are `204` and `3345` (both `int`s)

**Comment by Code-nomad** [comment]
Thank you! This indeed ended up being the issue at hand.
