### ISSUE TITLE
When the same avro file is created multiple times, its md5 checksum changes

### ISSUE THREAD

**Issue by ali-auro** [fastavro/fastavro#300]
We use fastavro 0.21.12. We calculate a MD5 checksum for the avro file we are generating and use the checksum to indicate if the file content changed or not. We have found that the checksum changes even when we recreate the exact same avro file. When doing a diff from shell, diff says that the binary files differ. Apparently, the avro file contains something related to file creation time. We tried codec='null' and codec='deflate' when calling fastavro.writer, the results are the same. 

Would it be possible to provide an option to turn off adding time related info to the file such that the same avro file will always have the same MD5 checksum?

**Comment by scottbelden** [comment]
The thing that is changing is the [sync_marker](https://github.com/fastavro/fastavro/blob/master/fastavro/_write_py.py#L499). The specification says that the sync marker is `The 16-byte, randomly-generated sync marker for this file.`

I think it sounds reasonable to allow the user to specify this on the `writer` like `writer(file_object, parsed_schema, records, sync_marker=b"...")`.

So you would have to provide the value. Thoughts?

**Comment by ali-auro** [comment]
The proposed solution sounds good to us. I don't know too much about the
avro specification, what is the advantage of randomly generating the sync
marker? Could the writer define a default sync marker and add a flag to
turn on random sync marker if needed? In other words,
writer(file_object, parsed_schema, records, sync_marker=b"the_default",
use_random_sync_marker=False)
This would make the usage of the library a bit easier. That being said, we
are fine as long as there is a way to make the md5 checksum constant.

Thanks,
Aijun

**Comment by scottbelden** [comment]
I did a quick search to see if there was any talk about the randomness and found this: https://mail-archives.apache.org/mod_mbox/avro-user/201301.mbox/%3CCAHNLEqvRrdA3qhGmDs8jCXGP-TeK24DTmZ1sfDgfu10mW=PB0Q@mail.gmail.com%3E

I'll see if I can throw something together at some point this weekend.

**Comment by ali-auro** [comment]
Thanks Scott. Much appreciated!
