### ISSUE TITLE
.pyx files need _force argument on parse_schema

### ISSUE THREAD

**Issue by dmsolow** [fastavro/fastavro#312]
Since fastavro writes the schema to datafiles with `__fastavro_parsed` intact, a separate process reading the file may fail with schemas that used aliases, because it won't parse the schema upon reading. This is addressed in in .py files with the `_force` argument to `parse_schema`, but it needs to be added to .pyx files

A longer term solution would probably be to change how this process works. I don't think writing `__fastavro_parsed` to the datafile is a good idea.

**Comment by scottbelden** [comment]
Good catch. I'm surprised this hasn't caused a test failure...

And I agree with you that `__fastavro_parsed` shouldn't be written to the datafile. At the time I thought it made sense and we could avoid some parts of the schema processing if we saw that in the datafile we were reading, but I was wrong (which was the reason `_force` was introduced at all.
