### ISSUE TITLE
Nested schemas replaced by parse_schema

### ISSUE THREAD

**Issue by norim13** [fastavro/fastavro#314]
Is there any way I can get a complex schema (with dependencies on other schemas) with its dependencies already replaced? 

It's probably best for me to give an example:

Master Schema:
```
{
    "name": "MasterSchema",
    "namespace": "com.namespace.master",
    "type": "record",
    "fields": [
        {"name": "field_1", "type": "com.namespace.dependencies.Dependency"}
    ]
}
```

Dependency Schema:
```
{
    "name": "Dependency",
    "namespace": "com.namespace.dependencies",
    "type": "record",
    "fields": [
        {"name": "sub_field_1", "type": "string"}
    ]
}
```

Given this two schemas were parsed with fastavro, and are stored in  `SCHEMA_DEFS`, I'd like to have a way of getting this:
```
{
    "name": "MasterSchema",
    "namespace": "com.namespace.master",
    "type": "record",
    "fields": [
        {
            "name": "field_1", 
            "type": {
                "name": "Dependency",
                "namespace": "com.namespace.dependencies",
                "type": "record",
                "fields": [
                    {"name": "sub_field_1", "type": "string"}
                ]
            }
        }
    ]
}
``` 

I'm currently using "avro" for python and it allows this kind of parsing. This issue came to me when I was trying to migrate from that library to fastavro. Do you think this is a legitimate request? Is there any way of accomplishing this in the current release of fastavro?

**Comment by scottbelden** [comment]
How did you do this with the `avro` library. Knowing that might help me understand what they do. If you have a script that will do it with the `avro` library that would be extremely helpful.

**Comment by norim13** [comment]
Sorry for the delayed answer. 

In the avro lib I would do something like `avro.schema.Names().get_name('Schema', 'com.schema.namespace').to_json()` and that would return the "expanded" schema.

**Comment by FlavSF** [comment]
Adding my name to the feature request :) I'm limited to using Avro because of this feature. Here's a sample of how I did the implementation: https://stackoverflow.com/a/54965406/10901720

**Comment by scottbelden** [comment]
@norim13 I finally got some time to look into this. In the general case, it seems pretty simple to implement and I have a local implementation that I'm playing with. However, the main problem I'm running into is in the case of recursive schemas. As you can imagine, there wouldn't be a way to print out the schema if it is recursive. I have an idea for some logic that could keep track of if a schema is recursive and if so not try to continue recursing but to just keep the `type` as the named type.

Here's an example of a simple recursive schema that is in our tests:

```python
    {
        "name": "LongList",
        "type": "record",
        "fields": [
            {"name": "value", "type": "long"},
            {"name": "next", "type": ["LongList", "null"]},
        ]
    }
```

I'm curious if you have any thoughts about recursive schemas.

**Comment by FlavSF** [comment]
@scottbelden jumping back in, I was able to produce a quick example of how Avro handles the "good" example (per norim13 example) as well as a recursive example (per yours):
https://gist.github.com/FlavSF/4f24ae3b3fca7b638267fc3a9a4d8af4
As far as I can tell, looks like Avro doesn't try to go down the tree if it detects recursion?

**Comment by scottbelden** [comment]
@norim13 @FlavSF I have a PR that should support this: https://github.com/fastavro/fastavro/pull/340

It adds an `expand` argument to the `parse_schema` function. One thing to note (that I mentioned in that documentation) is that the output of this expanded schema should not get passed in to other reader/writer functions as the schema. The avro specification says `A schema or protocol may not contain multiple definitions of a fullname` and this would sometimes (though not always) violate that. Passing an expanded schema into those other functions might work or it might throw an exception, but in general it isn't supported.

**Comment by norim13** [comment]
> @norim13 I finally got some time to look into this. [...]
> I'm curious if you have any thoughts about recursive schemas.

@scottbelden I never really though of that as I really have no use case for recursive schemas, but the only way I can think of to deal with it is exactly how @FlavSF posted about how Avro handles it.

Btw, as I really wanted to use fastavro by the time I opened the issue, I ended up making a lousy implementation by taking advantage of `SCHEMA_DEFS`. The only problem is that this variable is inside a "private" module (`fastavro._schema_common`), so I shouldn't really be relying on it... Do you see anything wrong in making it available to the outside? Or at least to have any way to get access to the currently known schemas?

**Comment by scottbelden** [comment]
I think `SCHEMA_DEFS` is too much of an implementation detail to expose it. Exposing some copy of that structure could be done, but I would fear that it might be hard to maintain that API if `SCHEMA_DEFS` were to be removed or changed substantially.

**Comment by Luxas98** [comment]
Tried to load https://github.com/IntouchHealth/avro-fhir/tree/master/schemas with fastavro and this seems to be related, as there is loads of nesting. Avro does not have a problem to load:

Avro example:
`python
import avro.schema
import glob
schemas = avro.schema.Names()
schema_files = glob.glob('./avro-fhir/schemas/*.avsc')

def load_fhir_schemas():
    for file_path in schema_files:
        file_text = open(file_path).read()
        json_data = json.loads(file_text)
        try:
            avro.schema.SchemaFromJSONData(json_data, schemas)
        except Exception as e:
            print(e)
            continue

load_fhir_schemas()

test_files = glob.glob('../examples/*.json')
    test_files = [file for file in test_files if 'Bundle' in file]
    bundle_data = json.load(open(test_files[0]))
    bundle_schema = schemas.get_name('intouchhealth.fhir.stu3.Resources.Bundle')
    writer = DataFileWriter(open("users_bundle_1.avro", "wb"), DatumWriter(), bundle_schema, codec="deflate")
    writer.append(bundle_data)
    writer.close()
`

fastavro example:
`python
import fastavro

# as I understood fastavro should be able to do load of referenced schemas automagicaly
bundle_schema = fastavro.schema.load_schema('./avro-fhir/schemas/bundle.avsc')

with open('user_bundle_fastavro.avro', 'wb') as avro_file: 
    fastavro.json_writer(avro_file, bundle_schema, [bundle_data])
   # Fails with: Exception: Unhandled type: intouchhealth.fhir.stu3.Datatypes.String
   # similar for writer
`

**Comment by scottbelden** [comment]
@Luxas98 I'm having trouble running your scripts because they load some `examples/*.json`. Are you able to upload the json file you are loading in somewhere?
