### ISSUE TITLE
Python 3.7 warning on `write.py` `from . import _write`. `in 3.8 it will stop working`

### ISSUE THREAD

**Issue by kurtostfeld** [fastavro/fastavro#321]
```
  /Users/.../lib/python3.7/site-packages/fastavro/write.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from . import _write
```

This isn't causing any functional problems, but I'm getting loud warnings in my log output that I'd prefer to remove.

**Comment by scottbelden** [comment]
Thanks. This should be resolved in the next release. I might wait until there is a more substantial change before making a release unless things stagnate for a while and then I'll go ahead and cut one.

**Comment by kurtostfeld** [comment]
Thank you. It's ultra low priority. I can disable the warning too. Thank you!
