### ISSUE TITLE
Aliases in enum isn't working as expected

### ISSUE THREAD

**Issue by m0nhawk** [fastavro/fastavro#323]
I want to use aliases to rename node name and enum values. I have the following (slightly modified `fastavro` example, I added enum field `badness`, schema change and reading with a new schema); but this doesn't work:

```python
import json
from fastavro import writer, reader, parse_schema

schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'station', 'type': 'string'},
        {'name': 'time', 'type': 'long'},
        {'name': 'temp', 'type': 'int'},
        {'name': 'badness', 'type': {
                "type": "enum",
                "name": "badness",
                "symbols" : ["good", "medium", "bad"]
            }, "default": "good"
        }
    ],
}
parsed_schema = parse_schema(schema)

# 'records' can be an iterable (including generator)
records = [
    {u'station': u'011990-99999', u'temp': 0, u'time': 1433269388, u'badness': 'medium'},
    {u'station': u'011990-99999', u'temp': 22, u'time': 1433270389, u'badness': 'good'},
    {u'station': u'011990-99999', u'temp': -11, u'time': 1433273379},
    {u'station': u'012650-99999', u'temp': 111, u'time': 1433275478, u'badness': 'bad'},
]

# Writing
with open('weather.avro', 'wb') as out:
    writer(out, parsed_schema, records)

schema['fields'][3]['name'] = 'fairness'
schema['fields'][3]['aliases'] = ['badness']
schema['fields'][3]['type']['symbols'] = ['good', 'neutral', 'bad']
schema['fields'][3]['type']['aliases'] = ['good', 'medium', 'bad']

# Reading
with open('weather.avro', 'rb') as fo:
    for record in reader(fo, parse_schema(schema)):
        print(record)
```

I'm using `fastavro==0.21.19`. Aliases for node names working as expected, but for enum values it's seems to ignore `aliases` section at all.

```
---------------------------------------------------------------------------
SchemaResolutionError                     Traceback (most recent call last)
<ipython-input-70-ba38f2e08a2c> in <module>
      1 # Reading
      2 with open('weather.avro', 'rb') as fo:
----> 3     for record in reader(fo, parse_schema(schema)):
      4         print(record)
fastavro/_read.pyx in _iter_avro_records()
fastavro/_read.pyx in fastavro._read._read_data()
fastavro/_read.pyx in fastavro._read.read_record()
fastavro/_read.pyx in fastavro._read._read_data()
fastavro/_read.pyx in fastavro._read.read_enum()
SchemaResolutionError: medium not found in reader symbol list ['good', 'neutral', 'bad']
```

**Comment by scottbelden** [comment]
I believe what you are trying to do by having aliases of the symbols themselves is not supported in the avro specification. There is an [open issue](https://issues.apache.org/jira/browse/AVRO-1752) regarding this so you could add your support there.

The only current way to do what you want to do is via an [enum evolution using default values](https://issues.apache.org/jira/browse/AVRO-1340) that will be a part of avro 1.9 (though I've already implemented it in fastavro). To do this, in the new reader schema you would need to set the `default` to the symbol you want when a symbol from the writer schema was used that no longer exists.

In your example, the old symbols are `["good", "medium", "bad"]` and the new symbols are `["good", "neutral", "bad"]`, so we would need to change the default to `neutral`. This means that where ever a `medium` was written, a `neutral` will be read.

Your script would be modified by changing:

```python
schema['fields'][3]['type']['symbols'] = ['good', 'neutral', 'bad']
schema['fields'][3]['type']['aliases'] = ['good', 'medium', 'bad']
```

to

```python
schema['fields'][3]['type']['symbols'] = ['good', 'neutral', 'bad']
schema['fields'][3]['type']['default'] = 'neutral'
```

Of course, this doesn't help in the case where someone would want to change the symbols from say `["A", "B", "C"]` to `["D", "E", "F"]` all at once (it would have to evolve over multiple iterations currently).

Let me know if this helps. Thanks!

**Comment by m0nhawk** [comment]
I was thinking that the `aliases` for enum type works the same, as for the field: if in `reader` schema aliases there is an old name, it resolves to a new name.

Yes, the `default` solution will work for me.

**Comment by scottbelden** [comment]
Unfortunately it seems that is not part of the spec. Feel free to comment on that issue if you'd like but it's good to hear the `default` will work.
