### ISSUE TITLE
Thoughts on numpy integration?

### ISSUE THREAD

**Issue by pbotros** [fastavro/fastavro#325]
Any thoughts on building a numpy integration within fastavro, similar to #112 but for numpy instead of Pandas? I'm happy to contribute this myself, but wanted to check if any maintainers or others have comments/concerns before doing it myself.

I'm imagining a fastavro.reader#to_numpy method that would create a numpy structured array from an underlying avro file, with one row in the avro file corresponding to one row in the structured array. Only compatible (== primitive) types would be supported.

The main benefit (at least, from my perspective) is speed of constructing this array by avoiding Python for-loops. [Cython typed memoryviews](https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html) could be helpful for speedup here. At first glance, it doesn't seem like too sweeping of a change within fastavro.

Thoughts/comments/concerns? Thanks!

**Comment by scottbelden** [comment]
I haven't really thought about this at all as I don't regularly use numpy. Would this only be a change to the reader or do you expect there would be a writer function as well?

Can you give an idea of where you would do the creation of numpy types? My initial concern is that this would add a lot of `if/else` checks for paths using numpy versus not using numpy.

**Comment by pbotros** [comment]
I haven't thought too much about a writer; I was only thinking `reader` for my use case, but I could envision similar `writer` changes too. Similar to fastparquet's API (https://fastparquet.readthedocs.io/en/latest/quickstart.html).

Sketch of the API:

```
class reader(file_reader):
  ...
  
  def to_numpy(self, ...):
    # Preallocate numpy array
    ...

    # Write backing array of numpy array
    ...

    # Read blocks from avro file
    for i in range(block_count):
      data = _read_data(...)
      write_keys(data, array)
    ...

     return array
```

Basically this would live on top of the parsing of the avro record (i.e. call `_read_data` in a loop), and so hopefully there aren't any numpy-specific pieces of code outside of this method I'm suggesting.

**Comment by scottbelden** [comment]
Closing this as not planning to support for now
