### ISSUE TITLE
Req: ISO date string conversion to int 

### ISSUE THREAD

**Issue by yiga2** [fastavro/fastavro#334]
To avoid transforming YYYY-MM-DD to int for logicalType date before calling the writer, could we extend `prepare_date()` like so:

```
def prepare_date(data, schema):
    """Converts datetime.date or 'YYYY-MM-DD' to int timestamp"""
    if isinstance(data, datetime.date):
        return data.toordinal() - DAYS_SHIFT
    elif isinstance(data, str):
        return datetime.strptime(data, "%Y-%m-%d").toordinal() - DAYS_SHIFT
    else:
        return data
```

**Comment by scottbelden** [comment]
That seems reasonable. It looks like a [`fromisoformat` was added in Python 3.7](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat) so eventually we would be able to use that.

Of course, when reading the data you would not get the same string back out.

**Comment by yiga2** [comment]
Understood. The date back would indeed be an `int`

In our use case, we import the avro files into BigQuery so having the `date` in its native datatype would allows us to import directly into column-based partitioned table.
