### ISSUE TITLE
Error on optional array of records

### ISSUE THREAD

**Issue by yiga2** [fastavro/fastavro#336]
Code to reproduce:

```
from fastavro import writer, reader

schema = {
    "type": "record",
    "name": "test",
    "fields": [
        {"name": "name", "type": "string"},
        {"name": "address",
         "type": [
             "null",
             {"type": "array",
              "items": {
                  "type": "record",
                  "name": "whatever",
                  "fields": [
                      {"name": "street", "type": ["null", "string"]},
                      {"name": "zip", "type": ["null", "string"]}
                      ]
                  }
              }
            ]
         }
    ]
}

records = [
    {'name': 'name1', 'address': [{'street': '22st'}]},
    {'name': 'name2'}
]


with open('test.avro', 'wb') as f:
    writer(f, schema, records, codec='deflate')

with open('test.avro', 'rb') as f:
    print(list(reader(f)))
```

If I write record `name2` only, no error and reader returns `[{'name': 'name2', 'address': None}]`
However for `name1` where `address` is passed (correctly, as a list), it errors out:
`...(type <class 'list'>) do not match ['null', {'type': 'array', 'items': {'type': 'record'...`

**Comment by yiga2** [comment]
Did find the answer [here](https://stackoverflow.com/questions/41565881/empty-list-as-default-value-in-avro-array).
If I remove `null` from the type union of the `address` field and set `"default": []`, the reader returns as expected:
`[{'name': 'name2', 'address': []}, {'name': 'name1', 'address': [{'street': '22st', 'zip': None}]}]`

Now, an empty list is not the same as `null` or None.
Also, `null` as a valid value when not set works with other type of arrays e.g. an array of string... 
Thoughts ?

**Comment by scottbelden** [comment]
You can keep the `null` in the type union and use a default of `None`. Specifically, the main problem is `{"name": "zip", "type": ["null", "string"]}` without a default value. Previously we would assume that no value means `None`, but this caused some data to be interpreted as the wrong type so now it is a bit more strict. It's might be possible to relax that again some more in the future if there is a way to add some better checking logic.

**Comment by yiga2** [comment]
I used an avro export from BigQuery as baseline for the schema, which did/does not include defaults. Adding defaults to the children fields in the writer does indeed the trick. Thanks !
And that works with the BigQuery reader (based on the java library I assume) as it only accepts `null` defaults - I have logged a support ticket though to accept `[]`.

The use of `default` is confusing as the Avro specs mentions its use for the reader only. As you described it, I thought the standard behavior was no value means `None`

I will submit a request to BigQuery team instead, to include generic `default` for all fields on export.

**Comment by scottbelden** [comment]
Yeah, I would like to change it back so that the lack of a value implies `None` as that is what most people expect but there's at least one place in the code that I know needs some updaing in order to do that.

**Comment by yiga2** [comment]
... and if some reader libraries are picky, you may want to introduce a configurable setting/flag for "behavior of default" e.g. for no array value, set `[]` instead of `null`. Or a list of tuple (type, value-to set-if-absent)

**Comment by yiga2** [comment]
Actually, after reading a few avro posts on jira, let me restate to see if I understand.
Writer should
- ignore the `default` setting altogether
- encode only the fields being passed and validate the value according to the type or union
- write in the header the schema passed, even if "larger" than the actually records being written (as an append could fill these fields)

Reader should
- use by default the same schema in the reader. But the reader schema to use could be smaller
- if there is no value for a given field requested by the schema, return the default value if one exists in the reader schema - if there is none, error out 

Thoughts ?

**Comment by scottbelden** [comment]
I have a PR that resolves this case (and passes all the other tests). I'm pretty sure there are still some aspects that need to be fleshed out with unions and nulls and default values, but I suppose we'll get to those when the time comes.

**Comment by yiga2** [comment]
@scottbelden thank you very much for the quick turnaround, for this and the ISO date enh !
