### ISSUE TITLE
Snappy support seems to have broken

### ISSUE THREAD

**Issue by mattomatic** [fastavro/fastavro#345]
Hi guys, 

I noticed that snappy seems to have been broken with release 0.0.22. 

The issue is that `snappy_read_block` previously expected to get in a file descriptor which had method `read` on it. However, after https://github.com/fastavro/fastavro/commit/7376b0121695b2de84090da26c6fbe4a6d3940ef the reader was replaced by a decoder, and the decoder doesn't have `read`, resulting in:

```
  File "/opt/venv/lib/python3.6/site-packages/fastavro/_read_py.py", line 504, in _iter_avro_records
    block_fo = read_block(decoder)
  File "/opt/venv/lib/python3.6/site-packages/fastavro/_read_py.py", line 476, in snappy_read_block
    data = fo.read(length - 4)
AttributeError: 'BinaryDecoder' object has no attribute 'read'
```

I think the fix is to change `snappy_read_block` to look like:
```
def snappy_read_block(fo):
    length = read_long(fo)
    data = fo.read_fixed(length - 4)
    fo.read_fixed(4)  # CRC
    return MemoryIO(snappy.decompress(data))
```

**Comment by scottbelden** [comment]
Thanks for the report! I've been meaning to actually add tests that use the snappy compression (and other compressions) for a while (which probably would have caught this). I'll try to get this fixed up ASAP.

**Comment by mattomatic** [comment]
Here joo go: https://github.com/fastavro/fastavro/pull/346
