### ISSUE TITLE
ValueError: Unrecognized codec: 'snappy' on avro read

### ISSUE THREAD

**Issue by VinothRajasekar** [fastavro/fastavro#352]
for record in avro_reader:
  File "fastavro/_read.pyx", line 635, in _iter_avro_records
ValueError: Unrecognized codec: 'snappy'

Using 0.22.0 version. looks like snappy codec is supported on read with 0.22.2 version. However, on read getting unrecognized codec for snappy code avro records.

```from fastavro import reader
with open('episodes.avro', 'rb') as fo:
    avro_reader = reader(fo)
    for record in avro_reader:
        print(record)

**Comment by scottbelden** [comment]
Do you have `python-snappy` installed? I should probably change the error message as there are two potential errors: 1) The codec support hasn't been added and 2) The codec library isn't installed and so we aren't able to encode/decode.
