### ISSUE TITLE
appending to an avro file gives an error

### ISSUE THREAD

**Issue by EricLeer** [fastavro/fastavro#358]
Hi,

I tried to append to an existing avro file using fastavro and got the error. Upon further inspection even the example code in the documentation throws the same error.

```
from fastavro import writer, parse_schema

schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'station', 'type': 'string'},
        {'name': 'time', 'type': 'long'},
        {'name': 'temp', 'type': 'int'},
    ],
}
parsed_schema = parse_schema(schema)

records = [
    {u'station': u'011990-99999', u'temp': 0, u'time': 1433269388},
    {u'station': u'011990-99999', u'temp': 22, u'time': 1433270389},
    {u'station': u'011990-99999', u'temp': -11, u'time': 1433273379},
    {u'station': u'012650-99999', u'temp': 111, u'time': 1433275478},
]

more_records = [
    {u'station': u'012990-99999', u'temp': 1, u'time': 1433279388},
    {u'station': u'012990-99999', u'temp': 21, u'time': 1433280389},
    {u'station': u'012990-99999', u'temp': -10, u'time': 1433283379},
    {u'station': u'013650-99999', u'temp': 110, u'time': 1433285478},
]

with open('weather.avro', 'wb') as out:
    writer(out, parsed_schema, records)

# Write some more records
with open('weather.avro', 'a+') as out:
    writer(out, parsed_schema, more_records)
```

This code gives me the following error:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-37-eaf39a75b14e> in <module>
     34 # Write some more records
     35 with open('weather.avro', 'a+') as out:
---> 36     writer(out, parsed_schema, more_records)

fastavro/_write.pyx in fastavro._write.writer()

fastavro/_write.pyx in fastavro._write.Writer.__init__()

fastavro/_six.pyx in fastavro._six.py3_appendable()

AttributeError: 'OutStream' object has no attribute 'buffer'
```
It seems like a test designed for OSX is failing. I'm on ubuntu 18.0.4

```
def py3_appendable(file_like):
        # in addition to "are you seekable?" and "do you know your position?"
        # we also do this direct identity comparison of 'file_like' vs.
        # sys.stdout.buffer, this works around a strange discovery of OSX
        # Platform, that stdout.buffer *is* seekable, and *does* know its
        # position, strange!
        if (file_like.seekable() and file_like.tell() != 0
and file_like is not sys.stdout.buffer):
         ...
```
Any ideas on a possible solution?

**Comment by scottbelden** [comment]
I'm trying to reproduce this. The first thing I ran into is that the append needs to be done in `a+b`, not just `a+` as you have. Could you make sure to fix that and see if you still run into the same issue?

If so, could you give a few more details on your setup? You mentioned you were using Ubuntu 18.04. Which version of python and fastavro do you have installed? Also, are you running the example as a standalone script or in ipython (as it seems)? I don't think that should matter, I just want to try to make sure I'm doing the same thing.

**Comment by scottbelden** [comment]
@EricLeer Did you see my comments? I think others have seen similar issues as you so if I can better understand your environment it should allow me to find a solution.

**Comment by EricLeer** [comment]
Sorry for getting back to you a bit latter.

I have also tried the `a+b` mode, but it gave the same result.

My python version is `3.6.8`  and my fastavro version is `0.22.2`.

I was indeed running it from a jupyter notebook. I have now also checked it from a standalone script and the strange thing is there it does work normally as expected.
