### ISSUE TITLE
Fastavro validation not working properly from 22.1 to 22.2

### ISSUE THREAD

**Issue by josepduarte** [fastavro/fastavro#365]
From version 22.1 to version 22.2, fastavro validation is not working properly. 
The following piece of code:
```
import fastavro

schema_json = {
	"namespace": "com.test.avro",
    "name": "Test",
    "type": "record",
    "fields" : [
        {"name": "type_label", "type": "string"},
        {"name": "created_at", "type": {"type": "long", "logicalType": "timestamp-micros"}}
    ]
}
schema = fastavro.parse_schema(schema_json)

INVALID_SCHEMA = {
    'type_label': 'type',
    'created_at': 'this_field_should_be_a_long_and_not_a_string',  # This is the invalid field
}

is_valid = fastavro.validate(INVALID_SCHEMA, schema_json, raise_errors=True)

print("\nis_valid: " + str(is_valid))
```

, produces the following result:

```
TypeError: an integer is required
Exception TypeError: 'an integer is required' in 'fastavro._logical_writers.prepare_timestamp_micros' ignored

is_valid: True
```

It is printing the exception with the expected result but that exception is being ignored (even when the `raise_erros` flag is set).
Also, it is returning True and should be returning False.

**Comment by scottbelden** [comment]
Thanks for the report. It looks like there was an exception happening in the cython path that was not being handled. It looks like that even in 0.22.1 it would have printed out those messages and silently failed when doing using `fastavro.writer`.

I have a PR that I believe should resolve this.
