### ISSUE TITLE
OrderedDict support for reading

### ISSUE THREAD

**Issue by smalyshev** [fastavro/fastavro#367]
Records in avro have ordered fields, but output of the record uses standard python dictionary, which is unordered. #141 handles OrderedDict support for writing, but there's no way to make fastavro to read data into OrderedDict. JSON decoder for python has special option which allows to specify which class to use for objects: https://docs.python.org/3/library/json.html#encoders-and-decoders (`object_pairs_hook` parameter) - maybe it makes sense to support something like that for fastavro too?

**Comment by Gyllsdorff** [comment]
FWIW, Dicts are guaranteed to be ordered in python 3.7 so this problem will eventually (in about 20 years) resolve itself.

https://mail.python.org/pipermail/python-dev/2017-December/151283.html
> Make it so. "Dict keeps insertion order" is the ruling. Thanks!

**Comment by scottbelden** [comment]
Yes, being on 3.7+ (Or I think even 3.6+ if you are using CPython) will solve this by default. For the general case, I'd have to see how this would be handled in the cython side of the code to know if it would be as performant.

**Comment by scottbelden** [comment]
This should be resolved now that this library support Python 3.7 and up.
