### ISSUE TITLE
validating nameless schema

### ISSUE THREAD

**Issue by Rosswell** [fastavro/fastavro#368]
Having an issue validating a nameless/recordless schema, where the schema is 
```
{
	"subject":"test_data-key",
	"version":1,
	"id":30,
	"schema":"\"string\""
}
```
and so the corresponding `data.avsc` file is just
```
{
  "type" : "string"
}
```
even though `fastavro.parse_schema(schema)` succeeds (as it is a valid avro schema), calling `fastavro.validate(schema, 'key_data')` results in:
```
fastavro/_validation.pyx:167: in fastavro._validation.validate
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   UnknownType: key_data

fastavro/_validation.pyx:224: UnknownType
```
Is there something I'm doing wrong here?

**Comment by scottbelden** [comment]
`validate` takes the record as the first argument and the schema as the second. So it should be `validate("key_data", schema)`.

**Comment by Rosswell** [comment]
@scottbelden wow. Sorry for my rookie mistake, and thanks for the help! works just fine now
