### ISSUE TITLE
Thread safety of fastavro.writer

### ISSUE THREAD

**Issue by mcguipat** [fastavro/fastavro#369]
I've observed some inconsistent behavior when calling `fastavro.writer` which I believe arises from an internal data structure being unsafe with multi-threaded (or potentially multiprocessed) calls.  When submitting a large number of tasks to be executed in parallel by a `dask` cluster, several tasks began throwing the following exception when executing `fastavro.writer(f, schema, json_objs, "snappy")` where `schema` is a union schema:
```
  File "fastavro/_write.pyx", line 734, in fastavro._write.writer
  File "fastavro/_write.pyx", line 689, in fastavro._write.Writer.write
  File "fastavro/_write.pyx", line 535, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 427, in fastavro._write.write_union
  File "fastavro/_validation.pyx", line 167, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 210, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 130, in fastavro._validation.validate_record
  File "fastavro/_validation.pyx", line 213, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 210, in fastavro._validation.validate
  File "fastavro/_validation.pyx", line 128, in fastavro._validation.validate_record
  File "fastavro/_schema.pyx", line 36, in fastavro._schema.schema_name
  File "fastavro/_schema.pyx", line 44, in fastavro._schema.schema_name
fastavro._schema_common.SchemaParseException: "name" is a required field missing from the schema: {'type': 'record'}
```
This was executed on linux with `py37` and `fastavro 0.21.21`.  After observing this behavior, I began logging the schema and the records which produced the exception; however, I was unable to reproduce the exception with single threaded execution.  

Given the `dask` workers were run with `nprocs = 1`, I am inclined to believe that this is produced as a result of multi-threaded execution.  The other possibility I considered is that there may be an issue when communicating pickled objects/functions. Unfortunately I am unable to share the exact schema and records due to sensitivity of the data.  Given the nature of the issue, it does not seem like they would be relevant.

Looking through the stack trace, the best candidate I can identify as the source of the issue is `SCEHMA_DEFS`.

**Comment by scottbelden** [comment]
There are multiple global structures currently in `fastavro` and so it is not thread safe.

**Comment by mcguipat** [comment]
> There are multiple global structures currently in `fastavro` and so it is not thread safe.

Is there any suggested way to interact in a multi-threaded way? Or does one need to use a global lock around any call to the library?

**Comment by scottbelden** [comment]
Using a global lock could be one way. Another option could be to have all the serialization/deserialization happen on one thread rather than many threads. I would expect it to work with multiprocessing (since memory shouldn't be shared), but I haven't actually tried that.

**Comment by mcguipat** [comment]
Just so it's documented here, are there any operations on the library that are threadsafe?  Reading perhaps?  From what I can tell, `parse_schema` and `writer` are certainly not.

**Comment by scottbelden** [comment]
As you mentioned, I think the main reason for not being thread safe is the `SCHEMA_DEFS` dictionary. Unfortunately, that is also used in reading and validation so at the moment I would not assume any part is thread safe.

**Comment by mcguipat** [comment]
> As you mentioned, I think the main reason for not being thread safe is the `SCHEMA_DEFS` dictionary. Unfortunately, that is also used in reading and validation so at the moment I would not assume any part is thread safe.

Could this not be easily resolved across the library by simply adding an additional optional parameter which would be the cached schemas that could be defaulted to the global `SCHEMA_DEFS`?

**Comment by scottbelden** [comment]
That probably _could_ work, but currently `SCHEMA_DEFS` is fairly internal and not something that I think would be obvious for creating. It doesn't seem like the most friendly data structure to expose or expect users to deal with. I'd rather see if there's a way to move away from the global data to make the library thread safe by default but I haven't had a chance to see what would be needed to do that.

**Comment by scottbelden** [comment]
`SCHEMA_DEFS` was removed in https://github.com/fastavro/fastavro/pull/451 and so while I'm not sure that the `writer` is thread-safe, I think there is a higher chance that it could be.

**Comment by scottbelden** [comment]
I'm going to close this as I believe it should be more thread safe (though there could still be cases where it is not). If there are still thread safety issues please let me know but I think `SCHEMA_DEFS` was the main culprit.
