### ISSUE TITLE
Writer: support ISO timestamp string

### ISSUE THREAD

**Issue by yiga2** [fastavro/fastavro#374]
Similar to https://github.com/fastavro/fastavro/issues/334, can support be added for a ISO string timestamp as input for the writer e.g.  `'2016-09-21 20:45:16+00:00'` ?

This would require inserting at the beginning of `prepare_timestamp_micros()` and `prepare_timestamp_millis()` the following conversion:
```
if isinstance(data, str):
        data =  datetime.datetime.strptime(data, "%Y-%m-%d %H:%M:%S%z")
```

**Comment by scottbelden** [comment]
I think this makes sense. The same [`fromisoformat` function](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat) mentioned in the other issue would eventually be able to be used when this library is Python 3.7+.

Until then though, I think we'd have to be more strict about the format for the timestamp. In your example you mentioned `'2016-09-21 20:45:16+00:00'` but it seems that maybe the more common format is to have a `T` between the day and the hours (so it would look like this: `'2016-09-21T20:45:16+00:00'`).

Also, the `isoformat()` function will output microseconds by default:

```
>>> datetime.datetime.now().isoformat()
'2019-11-13T10:14:11.329781'
```

So perhaps the format string we initially accept should require microseconds?

I think the idea is a good one, but I'm just not sure about what string format should be accepted until the less restrictive `fromisoformat` can be used.

**Comment by yiga2** [comment]
Makes perfect sense to use `fromisoformat` as it deals with many variants already. 
When do you plan to de-support 2.7 ? There is an official date in January floating around but it is up to you obviously.
Selfishly I am on 3.7 but can convert to `long` upstream until this is supported.

**Comment by scottbelden** [comment]
I would love to drop 2.7 now or in January when 2.7 officially reaches its end of life. It would simplify many aspects of the code base including this. However, I haven't decided when it actually makes sense to do that. At the moment the vast majority of the downloads are still for 2.7 as seen here:

```
[
  {
    "python_version": "2.7",
    "download_count": "1320288"
  },
  {
    "python_version": "3.6",
    "download_count": "348197"
  },
  {
    "python_version": "3.7",
    "download_count": "102131"
  },
  {
    "python_version": "3.5",
    "download_count": "85708"
  },
  {
    "python_version": null,
    "download_count": "65531"
  },
  {
    "python_version": "3.8",
    "download_count": "1441"
  },
  {
    "python_version": "3.4",
    "download_count": "313"
  },
  {
    "python_version": "3.2",
    "download_count": "1"
  }
]
```

I want to see if that changes at all as 2020 begins. I do think it makes sense to drop 2.7 support at some point next year.

**Comment by scottbelden** [comment]
I was going to put this in now that this library is Python 3.7+ but after thinking about it I think it would be better for users to create their own custom logical types: https://fastavro.readthedocs.io/en/latest/logical_types.html#custom-logical-types.
