### ISSUE TITLE
Specify Deflate compression level

### ISSUE THREAD

**Issue by drghifari** [fastavro/fastavro#377]
As we know that Deflate has compression level from 0-9 [1]. And fastavro uses default level of zlib [2]. The default zlib value is -1 (`Z_DEFAULT_COMPRESSION`) which represents a default compromise between speed and compression (currently equivalent to level 6) according to the python docs [3]

Is there any chance that we can specify deflate compression level?

[1] https://en.wikipedia.org/wiki/DEFLATE#Encoder/compressor
[2] https://github.com/fastavro/fastavro/blob/master/fastavro/_write_py.py#L257
[3] https://docs.python.org/3/library/zlib.html

**Comment by scottbelden** [comment]
To be honest, I'm not that familiar with deflate compression... if a compression level is specified, does that same compression level need to be specified when decompressing? Or can the normal decompressor read data that has been compressed with any level?

**Comment by dalbani** [comment]
No to your first question, and yes to the second.
That's basically how all compression algorithms works AFAIK.

**Comment by scottbelden** [comment]
That's good (and what I would hope).

I'm not sure yet about the best way to support this yet... perhaps just [another argument here](https://github.com/fastavro/fastavro/blob/master/fastavro/_write_py.py#L440-L447) with something like `compression_level` or more specifically `zlib_compression_level`.

**Comment by dalbani** [comment]
I'm not sure referencing the implementation ("zlib") is good idea. So I would say `deflate_compression_level`.
Or maybe a more generic `codec_compression_level`, should another codec in Avro ever also support a compression level.
