### ISSUE TITLE
Make `schema_name` part of the public API

### ISSUE THREAD

**Issue by rnpridgeon** [fastavro/fastavro#378]
It would be handy if the public API for `fatavro.schema` exposed [schema_name](https://github.com/fastavro/fastavro/blob/master/fastavro/schema.py#L9) as part of the public API.  Although my use case is specific to the use of[ Confluent's Schema Registry's subject naming strategies ](https://docs.confluent.io/current/schema-registry/serializer-formatter.html#sr-avro-subject-name-strategy) I'm sure this feature may be useful to others.

**Comment by scottbelden** [comment]
It looks like the current `schema_name` function returns both the namespace and the full name. Is this what you would want from a public function? It seems like maybe returning just the full name would make more sense in a public API but I'm not sure how this would be used in the schema registry.

**Comment by rnpridgeon** [comment]
You are correct, just the fullname would suffice @scottbelden, thanks!
