### ISSUE TITLE
Support for lz4 codec

### ISSUE THREAD

**Issue by mcguipat** [fastavro/fastavro#379]
Would there be support for adding an lz4 codec?  If so, I'd be happy to PR.

**Comment by scottbelden** [comment]
From what I can tell, an lz4 codec isn't specified in the [avro specification](https://avro.apache.org/docs/current/spec.html) nor is it one of the codecs that is implemented in java but left out of the specification (see https://issues.apache.org/jira/browse/AVRO-2427 and https://github.com/apache/avro/tree/master/lang/java/avro/src/main/java/org/apache/avro/file).

However, as long as the implementation and requirements are similar to something like `snappy` (where it's basically just an optional import and a small encoder/decoder function) then I think that it wouldn't be a problem. It would come with the caveat that there could be a breaking change down the road if lz4 were added to the specification and were different than the implementation added in `fastavro`.

A PR would be welcome. Thanks!

**Comment by mcguipat** [comment]
@scottbelden, I've opened a [PR](https://github.com/fastavro/fastavro/pull/381); however, it's failed the coverage check due to uncovered `except ImportError:` handling.  The other optional codecs are also missing coverage on the same lines.  How would you like me to address this?

**Comment by scottbelden** [comment]
Thanks for the PR. It's been merged. I'll try to get a new release out shortly. I'm not worried about the ImportError lines. At some point I may look into a better way to test those cases (probably something along the lines of monkeypatching something in `sys` to act as if the codec library isn't installed) but I don't think that's important enough to hold the PR back.
