### ISSUE TITLE
empty map fails to serialize

### ISSUE THREAD

**Issue by gaborbernat** [fastavro/fastavro#380]
Inside https://github.com/fastavro/fastavro/blob/master/fastavro/_write_py.py#L121-L127

The map start write block is not written on empty map, so the map end writes throws error for a mapping type. Is this intentional?

```python
    if len(datum) > 0:
        encoder.write_map_start(len(datum))
        vtype = schema['values']
        for key, val in iteritems(datum):
            encoder.write_utf8(key)
            write_data(encoder, val, vtype)
    encoder.write_map_end()
```

**Comment by scottbelden** [comment]
Thanks for the issue. That seems like an oversight and it looks like the function for handling arrays does the same thing. Do you happen to have a simple script that throws the error so that I can make sure I'm targeting the right fix?

**Comment by gaborbernat** [comment]
Not at the moment; but ran into similar issues with some unions 🤔 So for now switched back to python3-avro...

**Comment by scottbelden** [comment]
Okay. I have a thought on what might cause it so I'll see if I can reproduce it.

**Comment by gaborbernat** [comment]
I'll post a simplified example a bit later 👍

**Comment by scottbelden** [comment]
I was able to reproduce the issue and have a PR that should resolve it: https://github.com/fastavro/fastavro/pull/384

**Comment by gaborbernat** [comment]
thanks, was this released? 👍

**Comment by scottbelden** [comment]
Probably at some point today. I am trying to knock out a few other simple issues.
