### ISSUE TITLE
Avro serialisation in-memory

### ISSUE THREAD

**Issue by cdeil** [fastavro/fastavro#387]
How about adding a function that allows Avro serialisation in-memory, without hitting the disk?

I know it's possible via `io.BytesIO` now:
```
from io import BytesIO
out = BytesIO()
writer(out, parsed_schema, records)
out.getvalue()
```

But e.g. https://docs.python.org/3/library/json.html has direct support for that use case via `dumps` and `loads`. It's common when sending things instead of writing to a file.

Alternatively, I'd suggest adding a docs example mentioning this pattern of using `io.BytesIO` to serialise and de-serialise in-memory.

**Comment by scottbelden** [comment]
This is supported and is used extensively when the tests are run. The docs do mention that the first argument to the `write` function is `file-like` but I'm not opposed to adding more examples to the docs. Feel free to submit a PR if you'd like or I'll try to add the example in the near future.

**Comment by scottbelden** [comment]
Resolved via https://github.com/fastavro/fastavro/commit/435446130c66bf53500d5864239e28e0da068d1a

**Comment by cdeil** [comment]
@scottbelden - Thank you!
