### ISSUE TITLE
Top-Level Union unsupported

### ISSUE THREAD

**Issue by danieltahara** [fastavro/fastavro#388]
fastavro version: 0.22.9

Top-level primitive, record, array, and other fields are allowed, but top-level union fields are not. It's not obvious to me from the Avro spec that this isn't allowed, but I could see how it would make decoding super tricky. https://avro.apache.org/docs/current/spec.html#schemas. That said, fastavro supports a vanilla union type as the schema, so I don't see why there's the limitation.

```
In [1]: from fastavro import parse_schema

In [2]: schema = {
   ...:    "name": "sensor_native",
   ...:    "type": ["null", "double"],
   ...: }

In [3]: parse_schema(schema)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-551aa533bb5f> in <module>
----> 1 parse_schema(schema)

fastavro/_schema.pyx in fastavro._schema.parse_schema()

fastavro/_schema.pyx in fastavro._schema._parse_schema()

TypeError: unhashable type: 'list'
```

versus:
```
In [6]: schema = ["null", {
   ...:    "name": "sensor_native",
   ...:    "type": "double"
   ...: }]

In [7]: parse_schema(schema)
Out[7]: ['null', {'type': 'double'}]
```

There needs to be an `isinstance(schema_type, list)` here: https://github.com/fastavro/fastavro/blob/master/fastavro/_schema.pyx#L180

**Comment by scottbelden** [comment]
I believe top level unions are supported, but this example definitely exposes some confusion. A top level union schema would looke something like `[<type1>, <type2>, ...]`

For example, this works:

```python
from fastavro import parse_schema, writer, reader
from io import BytesIO

schema = ["null", "int"]
records = [3, None]

bio = BytesIO()
writer(bio, parse_schema(schema), records)

bio.seek(0)

print(list(reader(bio)))
# [3, None]
```

The example you gave of 

```
schema = {
    "name": "sensor_native",
    "type": ["null", "double"],
}
```
is not a union schema because as mentioned in the schemas section of specification, a union schema is defined as `A JSON array, representing a union of embedded types.`

I should also mention that the `name` field is probably adding to the confusion. You'll notice that the output of `parse_schema` in your second example gets rid of the `name` because it's not part of a primitive or union schema; it's only part of a record schema.

**Comment by danieltahara** [comment]
Yeah, I should have been tighter on what I meant by "top-level". Officially, my second example is a top-level union, but i was looking for the ability to have a named + documented union type rather than a union of null and a documented sub-type.

It's odd/unfortunate that "named" unions are not supported. Intuitively it seems like anything that is a valid "field" would be a valid schema. If that's not the intent, I'd blame the poor Avro spec/documentation, since that never makes it clear.

**Comment by scottbelden** [comment]
If the union were a field in a record then you could have a `doc` with it like this:

```python
schema = {
    "type": "record",
    "name": "record_name",
    "fields": [
        {
            "name": "field1",
            "type": ["null", "int"],
            "doc": "This is a union representing something",
        }
    ],
}
```

But other than that it doesn't look like avro has a way to "document" a union.

I'm going to close this but feel free to re-open it if I missed something.
