### ISSUE TITLE
pre-1970 timestamps on Windows

### ISSUE THREAD

**Issue by jmgpeeters** [fastavro/fastavro#389]
When serialising or deserialising a timestamp (I'm using millis) with negative offset to the 1970-1-1 epoch, this generally fails on Windows platforms. This is because

```
cpdef parse_timestamp(data, resolution):
    return datetime.datetime.fromtimestamp(data / resolution, tz=utc)
```
will get hit with a negative argument. E.g.

```
datetime.datetime.fromtimestamp(-1.0)
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-146-844a4ebeb041> in <module>
    ----> 1 datetime.datetime.fromtimestamp(-1.0)
OSError: [Errno 22] Invalid argument
```

On Linux I'm not seeing issues. This is clearly a known problem (e.g. https://bugs.python.org/issue1646728) but nevertheless annoying, as it prevents fastavro from being used reliably on Windows (for our purposes).

I'm not sure what the performance implications would be, but the function could be replaced by

```
EPOCH_UTC = datetime.datetime(1970, 1, 1, tzinfo=fastavro._timezone.utc)
cpdef parse_timestamp(data, resolution):
   return EPOCH_UTC + datetime.timedelta(seconds=data/resolution)
```

Something similar would also be needed on the write end, where

```
cpdef prepare_timestamp_millis(object data, schema):
   ...
            return <long64>(<double>(data.timestamp()) * MLS_PER_SECOND)
  ...
```
causes a similar failure, when calling .timestamp on a pre-EPOCH datetime.
If you agree (maybe this has come up before?) I'm happy to prepare a PR or test out a branch.

Best,
-Joris.

**Comment by scottbelden** [comment]
Can you post a simple script to reproduce this?

**Comment by jmgpeeters** [comment]
Certainly.
Here's one that illustrates the write issue:

```
schema = {'type': 'record',
 'name': 'dt_test',
 'namespace': 'fastavro.test',
 'fields': [
      {'name': 'dt', 'type': {'type': 'long', 'logicalType': 'timestamp-millis'}},
  ]}
s = fastavro.parse_schema(schema)

record = {
    'dt': datetime.datetime(1950, 1, 1)
}

bout = io.BytesIO()
fastavro.schemaless_writer(bout, s, record)
```

which gives ...

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
OSError: [Errno 22] Invalid argument

Exception ignored in: 'fastavro._write.prepare_timestamp_millis'
OSError: [Errno 22] Invalid argument
```

... and for read, using the same schema:
```
record = {
    'dt': -10000000,  # passing a long allows the write to succeed.
}

bout = io.BytesIO()
fastavro.schemaless_writer(bout, s, record)
bout.seek(0)
b = bout.read()
fastavro.schemaless_reader(io.BytesIO(b), s)
```

now failing as,
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-13-e512b77a40e1> in <module>
      1 bout.seek(0)
      2 b = bout.read()
----> 3 fastavro.schemaless_reader(io.BytesIO(b), s)

fastavro/_read.pyx in fastavro._read.schemaless_reader()
fastavro/_read.pyx in fastavro._read.schemaless_reader()
fastavro/_read.pyx in fastavro._read._read_data()
fastavro/_read.pyx in fastavro._read.read_record()
fastavro/_read.pyx in fastavro._read._read_data()
fastavro/_read.pyx in fastavro._read.read_timestamp_millis()
fastavro/_read.pyx in fastavro._read.read_timestamp_millis()
fastavro/_read.pyx in fastavro._read.parse_timestamp()
OSError: [Errno 22] Invalid argument
```

Note that this can only be reproduced on Windows.

**Comment by scottbelden** [comment]
This is indeed annoying. Here's another bug report talking about it: https://bugs.python.org/issue36439

Hopefully this will eventually get fixed in Python so that we don't have to do any special handling. For the time being though, I think it does makes sense for us to handle this. If you can submit a PR then please do so.

As for performance implications, I think we should try to keep things as performant as possible, but giving up a little for more reliability and usability is okay.

**Comment by jmgpeeters** [comment]
Sorry for the delay here. I got around to this today and have opened https://github.com/fastavro/fastavro/pull/394 for review.

**Comment by scottbelden** [comment]
This was resolved via https://github.com/fastavro/fastavro/pull/394
