### ISSUE TITLE
_parse_schema strips "doc" key from record

### ISSUE THREAD

**Issue by ulrikjohansson** [fastavro/fastavro#393]
The code here: 
https://github.com/fastavro/fastavro/blob/7df1334ae761d1c4ae3e087a4f3d2683998fd0d6/fastavro/_schema.pyx#L88-L93
strips "doc" keys from avro records when calling `fastavro.parse_schema(schema)`.
Is this intentional? It seems like "doc" keys are valid optional keys in record types.

An example input python dict schema:
```
{
  "type": "record",
  "name": "record_name",
  "doc": "blah",
  "fields": [
    {
      "name": "field1",
      "type": "string",
      "default": ""
    }
  ]
}
```
Result of `parse_schema()`
```
{
  "type": "record",
  "name": "record_name",
  "fields": [
    {
      "name": "field1",
      "type": "string",
      "default": ""
    }
  ]
}
```
I'm using fastavro v0.22.9

**Comment by scottbelden** [comment]
I don't think this is necessarily intentional. However, the spec says [A schema's "doc" fields are ignored for the purposes of schema resolution. Hence, the "doc" portion of a schema may be dropped at serialization.](https://avro.apache.org/docs/current/spec.html#Schema+Resolution).

I'd like to better understand how you are using `parse_schema` to know if it should be changed.

**Comment by ulrikjohansson** [comment]
I'm using it indirectly through another library called kafkit (used for interacting with confluent's schema registry). Here is the line that calls fastavro: 
https://github.com/lsst-sqre/kafkit/blob/16036285a0e63b7ada70dc31275ad3fc6baf5300/kafkit/registry/sansio.py#L367

So I have a dict representation of an avro schema that I want to register to a confluent schema registry.
My problem is that these schemas are handled elsewhere at the moment, and it's impossible for me to make the "register" functionality in the kafkit library produce and exact copy of the avro schema already in the schema registry for a specific subject. The schema registry saves the "doc-less" schema with a new id.

Regardless of schema compatibility, I think it's useful to be able to push a schema to the schema registry with the doc keys intact, so that they can be viewed in the registry with the documentation that goes with it.

This isn't a huge problem, since it's fully compatible with the previous schema, it was more an interesting thing I discovered while testing this out.
