### ISSUE TITLE
Add xz codec support

### ISSUE THREAD

**Issue by brokenjacobs** [fastavro/fastavro#405]
I saw a closed issue discussing adding xz support when python2.7 support is dropped from the library.

Can this be reconsidered now? If not, could support be built using the lzma backports library?
https://pypi.org/project/backports.lzma/

We are using xz codec in many of our avro files and this would be very helpful.

**Comment by scottbelden** [comment]
I would be okay with that. I'll try to get to it at some point, or if you would like to submit a PR then I could work with you to get that merged.
