### ISSUE TITLE
test_ancient_datetime test fails due to a timezone different than UTC

### ISSUE THREAD

**Issue by mateuszmrozewski** [fastavro/fastavro#409]
Steps to reproduce:
1. Set system timezone to something other than UTC/GMT, ie. 'Australia/Sydney'.
2. Run the test.

Expected:
Test works

Actual:
Test fails with different times:
`FAILED tests/test_logical_types.py::test_ancient_datetime - assert datetime.date...0, 1, 1, 0, 0) == datetime.date...12, 31, 14, 0)`

The test seems to try to go around it, but From Python documentation about datetime.replace() method:

> Note that tzinfo=None can be specified to create a naive datetime from an aware datetime with no conversion of date and time data.

It seems that serialization and deserialization may have an issue with timezones.

**Comment by scottbelden** [comment]
Yeah, I've been meaning to fix this. I think it's just a problem with the way the test is written rather than the actual implementation of the code. I'll try to clean this up. However, if you think the actual implementation is wrong then please let me know.

**Comment by mateuszmrozewski** [comment]
Test creates a naive datetime instance. After serializing and deserializing we get an aware datetime instance in UTC. This seems to be the correct approach, although the implicit change to UTC might be confusing. That is the nature of timezones :-)

Simplified piece of code that shows this behaviour (if you are in non utc timezone):
`from datetime import datetime, timedelta
from pytz import utc
import time

epoch = datetime(1970, 1, 1, tzinfo=utc)
dt2 = datetime(1970, 1, 1)
t2 = int(time.mktime(dt2.timetuple())) * 1000 + int(
                dt2.microsecond / 1000)
after = epoch + timedelta(seconds=t2/1000)

print(dt2)
print(t2)
print(after)`

I will prepare a PR to fix the test.
