### ISSUE TITLE
Optionally skip type specification for Union fields when writing JSON

### ISSUE THREAD

**Issue by gudjonragnar** [fastavro/fastavro#420]
I have an avro schema that contains optional fields in the form of a Union of `null` and a named type, although a primitive type produces the same result. The field's schema looks something like this:
```
...
    "fields": [{
        "name": "field_name",
        "type": ["null", "string"],
        "default": null
    }]
...
```
When writing a record that has `field_name` null will produce the json 
```
{
...
    "field_name": null,
...
}
```
but if it is set to some string it will be 

```
{
...
    "field_name": {"string": "some string"},
...
}
```
I realize this is an intended behaviour ( #188 ) but would you be open to adding an option to suppress writing the type?

**Comment by scottbelden** [comment]
I'm not sure about this yet...

Would you also expect to suppress writing the type information for named types? For example, in the JSON output if the path taken for a union is a record, then that type gets encoded in the output:

https://github.com/fastavro/fastavro/blob/9c477b72302b5071ac0b671946925c0f6bd172cb/tests/test_json.py#L235-L241

Also, if this option were added, the resulting output JSON would be treated as output only. It wouldn't be possible to read that JSON back in via the `json_reader`. Is that what you are expecting?

**Comment by gudjonragnar** [comment]
In my case I only have this union as a [null, something_else] to have optional fields with only one non-null option, therefore the type is "known". I would therefore also suppress the type specification for named types. 
Regarding the json not being readable by `json_reader` I guess for my purposes it would be ok, since I am sending this json onwards and never reading it myself. The receiving application expects no type specification.
I realize this is quite a specific case, especially now that I know the `json_reader` wouldn't be able to read it.

**Comment by scottbelden** [comment]
This issue seems to be pretty equivalent to another issue on the official avro issue tracker: https://issues.apache.org/jira/browse/AVRO-1582.

**Comment by gudjonragnar** [comment]
There doesnt seem to be any movement on that issue unfortunately :crying_cat_face:

**Comment by scottbelden** [comment]
Yeah... I don't think I'm opposed to adding this as an option, but I just haven't had time recently to work through some of these existing issues and see how complex it is to make this change work. I'll try to give it a shot when I can find some time, but at the moment I'm not sure when that will be.

**Comment by gudjonragnar** [comment]
I could possibly take a crack at it, but I am not sure where this change should be implemented, but after a very quick look at the code I guess either by adding a bool initialization value to `AvroJSONEncoder` and use that in `write_index` or by extending the class and overwrite the `write_index` method.

**Comment by gudjonragnar** [comment]
I made a PR with some very minor changes that seem to work.

**Comment by scottbelden** [comment]
Thanks! I'll try to get a new version out shortly.
