### ISSUE TITLE
Optional schema when appending to existing avro file  

### ISSUE THREAD

**Issue by stigchristian** [fastavro/fastavro#422]
I suggest that the schema argument should be made optional (accept `None`) when using fastavro.write() to append to an existing avro file.

The current implementation reads the schema from the file and that schema could be used as the writer schema in case the schema argument is `None` when the method is invoked.

It's possible to use the existing file's schema today with the following workaround, but it is doing stuff that happens futher down in the stack anyway, making unnecessary seek and read operations.

```
with open('example.avro', 'wb') as out:
    writer(out, schema1, records1)

with open('example.avro', 'a+b') as fo:
    fo.seek(0)
    avro_reader = reader(fo)
    fo.seek(0,2)
    writer(fo, avro_reader.writer_schema, records2)
```

If this is implemented and a developer chooses to omit the schema when appending to an existing file, it is accepted that fields not present in the files embedded schema won't be written.

**Comment by scottbelden** [comment]
I agree that this would make the API better. At the moment we require the schema be exactly the same which could have it's own issues (e.g. two schemas that are the same but differ only in whitespace):

https://github.com/fastavro/fastavro/blob/9c477b72302b5071ac0b671946925c0f6bd172cb/fastavro/_write_py.py#L406-L408

I would possibly take your request one step further and say that when appending, the API shouldn't take a `schema` at all. If the user is required to provide a schema that is already readable in the file, it doesn't really make sense.

With all that being said, I'm not sure if there is a clean way to update the `writer` to do this. Currently the order of the arguments is the file object, then the schema, then the records:

https://github.com/fastavro/fastavro/blob/9c477b72302b5071ac0b671946925c0f6bd172cb/fastavro/_write_py.py#L487-L495

We'd have to make both the `schema` and `records` arguments be optional and then have additional checking that would be pretty messy.

Perhaps the better approach is to create a new `append` API that takes only the file object and records. Using the `writer` to append could eventually be removed.

**Comment by stigchristian** [comment]
> I would possibly take your request one step further and say that when appending, the API shouldn't take a schema at all. If the user is required to provide a schema that is already readable in the file, it doesn't really make sense.

> With all that being said, I'm not sure if there is a clean way to update the writer to do this. Currently the order of the arguments is the file object, then the schema, then the records:

Yes, that would be the better solution, but as you say there is probably not a clean way to update the `writer` to do that, and that is why my suggestion was to accept `None` for the schema argument. I realise that it is kind of a quick 'n dirty solution, but at least it won't break the existing API. 


> Perhaps the better approach is to create a new append API that takes only the file object and records. Using the writer to append could eventually be removed.

I agree on this, but the downside if or course the deprecation of existing functionality and the maintenance required around this. Anyway, I believe that it is the best long-term solution.
