### ISSUE TITLE
Despite no defaults set in schema, nullable fields default to null value in validate and writer

### ISSUE THREAD

**Issue by zachary-povey** [fastavro/fastavro#423]
Closely related to the closed issues #48 & #49 (you may just want to re-open 49).

There is nothing in the [official avro spec](https://avro.apache.org/docs/current/spec.html) to suggest that defaulting values should be any different between union fields including null and those not. 

However fastavro (v0.23.2) gives nullable unions a default value of null/None automatically.

**Example using validate**
Executing the script:
```python
import fastavro as fa

schema = {
    "name": "my_schema",
    "type": "record",
    "fields": [
        {"name": "normal_field", "type": "string"},
        {"name": "normal_union_field", "type": ["int", "float"]},
        {"name": "nullable_union_field", "type": ["null", "string"]},
    ],
}

valid_record_1 = {"normal_field": "a", "normal_union_field": 1, "nullable_union_field": "b"}
valid_record_2 = {"normal_field": "a", "normal_union_field": 1.0, "nullable_union_field": None}

invalid_record_1 = {"normal_union_field": 1, "nullable_union_field": "b"}
invalid_record_2 = {"normal_field": "a", "nullable_union_field": "b"}
invalid_record_3 = {"normal_field": "a", "normal_union_field": 1}

print(
    [
        fa.validate(record, schema=schema, raise_errors=False)
        for record in [valid_record_1, valid_record_2, invalid_record_1, invalid_record_2, invalid_record_3]
    ]
)

```
outputs: `[True, True, False, False, True]` - i.e. the nullable union field is missing but it passes validation. This seems to be a result of fastavro defaulting fields to None when encoding which is demonstrated below.  

**Example using writer**
Using same setup as script above if we run:
```python
from io import BytesIO
buffer = BytesIO()
fa.writer(buffer, schema=schema, records=[invalid_record_3])
buffer.seek(0)

print(list(fa.reader(buffer)))
```
we get `[{'normal_field': 'a', 'normal_union_field': 1, 'nullable_union_field': None}]`. So the field is being defaulted to None, even though no default is set in the schema.

Examples were using python 3.8 with fastavro 0.23.2.

**Comment by scottbelden** [comment]
This is also related to https://github.com/fastavro/fastavro/issues/292.

Unfortunately, at this point, changing this to require an explicit `None` would be a massive breaking change. If a restriction like this were to be added, it would probably have to be gated behind something like a `strict` option that would be off by default.

Is there a larger problem beyond just the example you gave. The areas where I see this usually become a major issue is in things like unions of two records that differ by only an optional field and the validator can mess up when trying to figure out which record type the data is.

**Comment by zachary-povey** [comment]
No wider issue as such, just that as it goes against the official spec, it is a bit surprising and in my specific case could have led to undesired behaviour.

I have a pretty simple case of converting a csv file into avro and was relying on a call to `fastavro.validate_many` as a guard against someone updating the csv format. For example if they changed the name of one column, I would have an extra field and a missing field when compared to the schema. However due to this issue (and the fact that extra fields are ignored), if the field was nullable in the schema this wouldn't fail and all values for this field would simply be set to null in the output avro. Obviously the solution is simple in my case but it wasn't clear that there was a problem at all to begin with because I thought, having not set any default values in the schema, I was protected against this already.

**Comment by scottbelden** [comment]
The second example using the `writer` can be resolved by using the new `strict` option. So if you instead do:

```python
from io import BytesIO
buffer = BytesIO()
fa.writer(buffer, schema=schema, records=[invalid_record_3])
buffer.seek(0)

print(list(fa.reader(buffer)))
```

You get an error: `ValueError: Field nullable_union_field is specified in the schema but missing from the record`

Though we probably need to add a similar `strict` option to `validate`.
