### ISSUE TITLE
Performance regression introduced in 051b10 makes fastavro slower than avro in some cases

### ISSUE THREAD

**Issue by stestagg** [fastavro/fastavro#425]
I'm writing an avro python library, and am running performance comparisons between fastavro and avro-python3:  [Benchmarks](https://stestagg.github.io/cavro/benchmark.html)

I noticed recently that fastavro is now slower than avro-python3 when dealing with more complex schemas (This benchmark + schema is unfortunately an attempt to recreate a simpler schema based on a real-world scenario that I've dealt with!)

With the 70kb schema in the attached zip, fastavro is about 30% slower than avro-python3. 

I've extracted a kinda-minimal test case to reproduce this, and a simple bisect confirmed that 051b10 is the culprit (which makes sense given the commit description)

The test case + schema are attached and in this gist: https://gist.github.com/stestagg/76410b684dc9343b28d3cf9919345ad8

Zipped version: [fastavro.zip](https://github.com/fastavro/fastavro/files/4544959/fastavro.zip)

**Comment by scottbelden** [comment]
I think this will be easy to fix. After I put that in I realized I had made a mistake but didn't realize it was significant. In that PR, I had created an `_validate` that expects an already parsed schema and so my intention was that the reader/writer would use that function since they do the parsing at the beginning. But after I made the release I realized I forgot to do that.

**Comment by stestagg** [comment]
Looks good from here :)

![Screenshot from 2020-04-30 17-07-50](https://user-images.githubusercontent.com/704526/80733116-2d571300-8b05-11ea-9a4e-773966503575.png)

**Comment by scottbelden** [comment]
Great! I was able to run the script you provided in the gist, but is the full script you are using to generate the plots available? If so I'd love to be able to run it in the future.

**Comment by stestagg** [comment]
The benchmarks are here: https://github.com/stestagg/cavro/tree/master/benchmark, feel free to use/copy as you like
