### ISSUE TITLE
Unable to use codecs with schemaless_writer/reader

### ISSUE THREAD

**Issue by yeralin** [fastavro/fastavro#432]
Hi, I might have a silly question, but is it possible to use compression with schemaless writers/readers?

**Comment by scottbelden** [comment]
Not currently. The codec information is encoded in the avro header which is the part that is omitted when using the schemaless functions. I think it might be confusing to read a compressed output as you would need to know which codec was used and potentially the compression level (if that was supplied when writing)

**Comment by yeralin** [comment]
Ok, then I will do manual compression! Thank you :)
