### ISSUE TITLE
Use type annotations

### ISSUE THREAD

**Issue by spenczar** [fastavro/fastavro#434]
Type annotations are getting increasingly popular and common in the Python ecosystem. I'm interested in adding annotations to fastavro. Would a PR that does so be of interest?

**Comment by scottbelden** [comment]
This is something I do in a lot of other code bases I work on and would probably do here as well once Python 2 support is dropped (which at the moment there isn't any official date I've come up with but my thought is sometime this year). I don't like the comment style typing syntax that needs to be used for Python 2 so I don't really want to put those in at the moment.

**Comment by spenczar** [comment]
Yeah, that's completely understandable.

What about type stubs? Those get written into `.pyi` files next to source code, so `mypy` learns about types, but they don't affect Python 2 compatibility.

They're less nice than having the annotations right in the code, but they're a step in the right direction.

**Comment by scottbelden** [comment]
I would be okay with that until we can put the types directly in the code. I probably won't take the time to add these interface files, but if this is something you would find useful at the moment I would gladly accept a PR that adds these.
