### ISSUE TITLE
Include fieldname and value in TypeError and ValueError

### ISSUE THREAD

**Issue by juarezr** [fastavro/fastavro#439]
### Problem

Sometimes is hard to figure out what is the wrong when writing rows with fastavro.

It may be a error with the:

1. field defined in schema
2. column value in some row of the data
3. wrong definition for `precision` or `scale`
4. missing value for a required field
5. etc...

In this cases a exception like bellow is raised:

```
  File "/home/juarezr/src/github/petl/petl/io/avro.py", line 409, in _write_toavro
    fastavro.writer(fo=target_file,
  File "fastavro/_write.pyx", line 628, in fastavro._write.writer
  File "fastavro/_write.pyx", line 581, in fastavro._write.Writer.write
  File "fastavro/_write.pyx", line 335, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 285, in fastavro._write.write_record
  File "fastavro/_write.pyx", line 329, in fastavro._write.write_data
TypeError: Expected list, got str
```
### Enhancement

I suggest including information for the developer figure out what's wrong in the exception message.

It can be information like:

- field name with error
- the value that raised the error
- the row number for large datasets
- any additional tip for fixing it

Maybe this will make our lives easy. :smile: 

Thanks for the excelent library.

**Comment by scottbelden** [comment]
The [`validation` API](https://fastavro.readthedocs.io/en/latest/validation.html) is usually able to do a good job at giving the reason for the problem. Can you confirm that it finds the problem and gives sufficient information for the error you have? If not we can definitely try to improve it.

I think there are currently two ways to help find these issues in the future.

The first is that the `write` function has a `validator` argument. If set to `True`, it will call our validation function before writing the next record. This will probably have a large impact on performance and therefore isn't done by default.

The second option would be to change where you call `write` and do something like this:

```python
try:
    write(...)
except Exception:
    validate(...)
```

This would only do the validation when the write fails.

I personally like the second option better and at some point `fastavro` might do that by default, but it's just not the case right now.
