### ISSUE TITLE
Decimal numbers are not rounded to a schema's scale during serialization

### ISSUE THREAD

**Issue by matpuk** [fastavro/fastavro#445]
Hello!

According to the avro schema definition, the 'scale' property can be omitted.
So, I wrote a simple script which just fails with the error 'ValueError: Scale provided in schema does not match the decimal':

```
from decimal import Decimal, getcontext
from io import BytesIO

import fastavro

getcontext().prec = 10


def serialize(schema, data):
    bytes_writer = BytesIO()
    fastavro.schemaless_writer(bytes_writer, schema, data)
    return bytes_writer.getvalue()


def deserialize(schema, binary):
    bytes_writer = BytesIO()
    bytes_writer.write(binary)
    bytes_writer.seek(0)

    res = fastavro.schemaless_reader(bytes_writer, schema)
    return res


def test_default_scale_value():
    schema = {
        "name": "test_default_scale_value",
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 10,
    }

    data1 = Decimal("-2.12344")
    binary = serialize(schema, data1)
    data2 = deserialize(schema, binary)
    assert (data1 == data2)


if __name__ == '__main__':
    test_default_scale_value()

```

Is this a bug? I'm using Ubuntu-20.04, Python 3.8.2, fastavro 0.23.5.

**Comment by scottbelden** [comment]
I'll preface this by saying that I'm not as well versed on how the decimal encoding works. In the spec, it says that the decimal type should represent a number in the form of:

unscaled × 10<sup>-scale</sup>

So for your number that would be:

-212344 × 10<sup>-5</sup>

So without providing a scale of `5`, I would assume that when deserializing you would get back `Decimal("-212344")`. Is that what you are expecting?

**Comment by matpuk** [comment]
I expect that if i didn't provide a scale, I can store any decimals with precision number of digints in them:
precision = 5
12345
1234.5
123.45
12.345
1.2345
0.1234

Ok. Now i see the problem: even in PostgreSQL I define my decimals as 18, 9 (precision 18, scale = 9), but I can't find how to force Python decimals to honor a scale. The only thing I can set is a precision. But it works only during a math.
So, even if I set precision = 10, Decimal('1.12345678901234567890') will stay as is until I multiply it by 1 or do other math...

Maybe, fastavro should try to bring decimals to a schema precision and scale?

**Comment by matpuk** [comment]
Ok. I modified my test script and added the 'scale' parameter. And it doesn't work either:

```
from decimal import Decimal, getcontext
from io import BytesIO

import fastavro

getcontext().prec = 10


def serialize(schema, data):
    bytes_writer = BytesIO()
    fastavro.schemaless_writer(bytes_writer, schema, data)
    return bytes_writer.getvalue()


def deserialize(schema, binary):
    bytes_writer = BytesIO()
    bytes_writer.write(binary)
    bytes_writer.seek(0)

    res = fastavro.schemaless_reader(bytes_writer, schema)
    return res


def test_default_scale_value():
    schema = {
        "name": "test_default_scale_value",
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 18,
        "scale": 9
    }

    data1 = Decimal("-2.12345678901234567890")
    print(data1)
    binary = serialize(schema, data1)
    data2 = deserialize(schema, binary)
    assert (data1 == data2)


if __name__ == '__main__':
    test_default_scale_value()

```

**Comment by scottbelden** [comment]
> I expect that if i didn't provide a scale, I can store any decimals with precision number of digints in them:
> precision = 5
> 123.45

So let's take this as an example. Suppose the schema says that the precision is 5 and no scale is defined. When we encode the decimal `123.45` it is basically just encoding the fact that there are the digits `1, 2, 3, 4, 5`. So when we read that value, it will read the value `12345` and just return that.

So the input would be `123.45` but the output would be `12345`.

I think this issue on the Avro JIRA is pretty similar to the problem being discussed here: https://issues.apache.org/jira/browse/AVRO-1864

**Comment by scottbelden** [comment]
> Ok. I modified my test script and added the 'scale' parameter. And it doesn't work either:

In the new example, the value being encoded is `Decimal("-2.12345678901234567890")` but this value has a precision of 21 and a scale of 20 (not 18 and 9) which is why the error is still happening

**Comment by matpuk** [comment]
> > Ok. I modified my test script and added the 'scale' parameter. And it doesn't work either:
> 
> In the new example, the value being encoded is `Decimal("-2.12345678901234567890")` but this value has a precision of 21 and a scale of 20 (not 18 and 9) which is why the error is still happening

Yes. I understand. But can fastavro try to convert incoming decimal to schema's precision and scale. I think this will be enough.

**Comment by scottbelden** [comment]
> Yes. I understand. But can fastavro try to convert incoming decimal to schema's precision and scale? I think this will be enough.

So in your example where the input is `Decimal("-2.12345678901234567890")` and the schema says the precision is 18 and the scale is 9, what would you expect the output (after writing and reading) to be?

**Comment by matpuk** [comment]
I expect Decimal('-2.123456789').
The idea is simply: get decimal value, apply .quantize('.'+'0'*scale) and then convert it to bytes.

**Comment by scottbelden** [comment]
I'll have to look into the precision bug.

At the moment I'm probably not going to change any implementation yet. On one hand, I can see how this could be convenient but it could also catch people by surprise. If someone were to store some data and then later read it and get back a different value then they might be caught off guard.

The same principle would be true if someone were trying to use a schema with a `fixed` type of say length `4`. I would hope the library would not silently truncate an input of length `8`.

**Comment by matpuk** [comment]
All modern SQL databases use the principle I described. There is no surprise in getting float or decimal number rounded to conform with a schema. Because otherwise it is just a nightmare to control every decimal number inside application business logic and make sure it will fit into all used schemas and according data storages/sources.

> The same principle would be true if someone were trying to use a schema with a `fixed` type of say length `4`. I would hope the library would not silently truncate an input of length `8`.

This is the incorrect example. Mathematical rounding is not the same.

But ok. I will update the issue description to reflect the actual issue and maybe we will get back to it some day later...

**Comment by scottbelden** [comment]
Closing this as I don't plan to change the implementation currently.
