### ISSUE TITLE
Multi-schema support

### ISSUE THREAD

**Issue by gaborbernat** [fastavro/fastavro#450]
Currently, fastavro caches parsed schema types here: https://github.com/fastavro/fastavro/blob/c98886167f/fastavro/_schema_common.py#L13. This cache is global though, not per parsed schema. This means fastavro does not support multiple schemas in parallel if these schemas have overlapped type names that differ in any shape or form. 

Here's a minimal reproducible version of this (this works with v0.23.5 but not in v0.23.6 as the later now correctly parses array formats via https://github.com/fastavro/fastavro/commit/c98886167fe3347990c6df373bc82bc1eb7879c9):

```python
from io import BytesIO

from fastavro import parse_schema, schemaless_writer, __version__

print(__version__)

schema_v1 = [
    {"name": "Location", "type": "record", "fields": [{"name": "city", "type": "string"}]},
    {"name": "Weather", "type": "record", "fields": [{"name": "of", "type": "Location"}]},
]

schema_v2 = [
    {"name": "Location", "type": "record", "fields": [{"name": "city", "type": "long"}]},
    {"name": "Weather", "type": "record", "fields": [{"name": "of", "type": "Location"}]},
]

example_1 = {"of": {"city": "London"}}
example_2 = {"of": {"city": 123}}

parse_v1 = parse_schema(schema_v1)
parse_v2 = parse_schema(schema_v2)


with BytesIO() as outcome:
    schemaless_writer(outcome, parse_v2, example_2)
    print(outcome.getvalue())

with BytesIO() as outcome:
    schemaless_writer(outcome, parse_v1, example_1)
    print(outcome.getvalue())
```

v0.23.5 output:
```console
0.23.5
b'\x02\xf6\x01'
b'\x02\x0cLondon'
```

v0.23.6 output:
```console
0.23.6
b'\x02\xf6\x01'
Traceback (most recent call last):
  File "regression.py", line 29, in <module>
    schemaless_writer(outcome, parse_v1, example_1)
  File "fastavro/_write.pyx", line 651, in fastavro._write.schemaless_writer
  File "fastavro/_write.pyx", line 335, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 249, in fastavro._write.write_union
ValueError: {'of': {'city': 'London'}} (type <class 'dict'>) do not match [{'type': 'record', 'name': 'Location', 'fields': [{'name': 'city', 'type': 'string'}], '__fastavro_parsed': True}, {'type': 'record', 'name': 'Weather', 'fields': [{'name': 'of', 'type': 'Location'}], '__fastavro_parsed': True}]
```

Suggestion: make the cache schema bound. You could, in theory, achieve this by resetting the cache between calls of ``parse_schema``, but this would mean now parsing would not be thread-safe. Instead, I suggest you create the cache within ``parse_schema`` and pass it through as an additional argument during the parsing.

**Comment by scottbelden** [comment]
Thanks for tracking this down. I think it is probably somewhat related to https://github.com/fastavro/fastavro/issues/185 and https://github.com/fastavro/fastavro/issues/369.

> but this would mean now parsing would not be thread-safe

I'm not sure that `parse_schema` is currently thread-safe. It reads and writes to `SCHEMA_DEFS` which is the global structure that is causing the issue.

The whole `SCHEMA_DEFS` should probably go away and reading/writing should only rely on the passed in schema and no other pre-existing schemas that were parsed in the past. This might be easier said than done though. I think there is some code in the wild that relies on the fact that we cache schemas, though I would probably be okay with making a change that breaks that functionality as what you have here is something that I would expect to work.

**Comment by gaborbernat** [comment]
Do you have any plan/availability to address this soon-ish?

**Comment by ksunden** [comment]
One thing that has come up for me lately: Avro RPC allows you to separately define types (outside of an individual schema)

https://avro.apache.org/docs/current/spec.html#Protocol+Declaration

There doesn't seem to be a convenient way to seed the `parse_schema` call with these types.

Athough, now that I think about it... if it is global, I guess just parsing these once would seed the `SCHEMA_DEFS`

So, if this were to change, I would want some way of providing type declarations that are used within `parse_schema`

**Comment by scottbelden** [comment]
> Do you have any plan/availability to address this soon-ish?

I'm not sure at the moment. The global `SCHEMA_DEFS` is used in a lot of places so I don't know what all will be affected by a change to remove that or how it might change the existing API.

**Comment by gaborbernat** [comment]
We've excluded the latest release to fix the issue, but worried about that if the next release will not include the fix we'll break again 🤔

**Comment by scottbelden** [comment]
Understandable. At the moment I would specify `fastavro<=0.23.5` for your case when you install. It was not intentional to cause this specific problem, but the case of using multiple versions of the same named type is something that I was not accounting for as I've known that it doesn't always work (though maybe that isn't as clear as it should be)

**Comment by typhoon2k** [comment]
We just tried to upgrade fastavro to the latest version and hit this change.
Our use case was to parse schemas one by one (retrieved one by one from schema registry, with references between them) and then use cached schemas in validation.
If for parsing schemas there is a workaround (by using `_named_schemas`), then for validation no workarounds are available. Therefore we can't upgrade...

**Comment by scottbelden** [comment]
As you mentioned, I believe the way this could work for parsing would be to supply the `_named_schemas` like so:

```python
all_named_schemas = {}
parsed_schema_1 = parse_schema(schema_1, _named_schemas=all_named_schemas)
parsed_schema_2 = parse_schema(schema_2, _named_schemas=all_named_schemas)
parsed_schema_3 = parse_schema(schema_3, _named_schemas=all_named_schemas)
```

As mentioned in the docs, the `_named_schemas` is marked as an internal argument. That's mostly because I didn't think there would be much need for users to ever really know or care about that data structure. That mostly still holds true, but there have been a few cases like the one you mentioned where maybe it does make sense to have it be part of the public API. I'm not sure yet... so for right now I'm going to keep it labeled the way it is, but I don't imagine it changing at any point in the foreseeable future.

As for `validate`, I see what you are talking about and I think it's a bug. In the example above, if `parsed_schema_3` was given as the argument to `validate`, then we should be able to pull the `__named_schemas` value from that parsed schema. I'll try to put together a quick PR to fix this.

**Comment by typhoon2k** [comment]
> As for validate, I see what you are talking about and I think it's a bug. In the example above, if parsed_schema_3 was given as the argument to validate, then we should be able to pull the __named_schemas value from that parsed schema.

Yes, that is our problem as `validate` bypasses detection of existing `__named_schemas` due to `parse_schema` call with `_force=True`.
Thanks for looking into this @scottbelden !

**Comment by typhoon2k** [comment]
Thanks @scottbelden, that was super fast! I can confirm that it is working and it also unblocks our migration to the latest version of fastavro.
