### ISSUE TITLE
Schema's decimal precision is ignored when serializing a decimal

### ISSUE THREAD

**Issue by matpuk** [fastavro/fastavro#452]
A decimal number is not checked for actual precision before serializing. This leads to loss of significant digits during deserialization.

A check similar to decimal scale validation is needed.

```
from decimal import Decimal, getcontext
from io import BytesIO

import fastavro

getcontext().prec = 18


def serialize(schema, data):
    bytes_writer = BytesIO()
    fastavro.schemaless_writer(bytes_writer, schema, data)
    return bytes_writer.getvalue()


def deserialize(schema, binary):
    bytes_writer = BytesIO()
    bytes_writer.write(binary)
    bytes_writer.seek(0)

    res = fastavro.schemaless_reader(bytes_writer, schema)
    return res


def test_ignored_precision_value():
    schema = {
        'name': 'test_ignored_precision_value',
        'type': 'bytes',
        'logicalType': 'decimal',
        'precision': 4,
        'scale': 2
    }

    data1 = Decimal('123456789012345.1')
    print(f'Original: {data1}')
    binary = serialize(schema, data1)
    data2 = deserialize(schema, binary)
    print(f'Restored: {data2}')
    assert (data1 == data2)


if __name__ == '__main__':
    test_ignored_precision_value()
```

**Comment by scottbelden** [comment]
I believe this came up recently in another issue. Thanks for the test case; it definitely helps.

I would expect in this case that an exception should be thrown since the precision of the decimal value is larger than the precision defined in the schema. Is that what you are expecting too?

**Comment by matpuk** [comment]
I mentioned this issue recently, yes. Exception similar to scale check is expected, yes. I can create a PR myself if needed.

**Comment by scottbelden** [comment]
If you want to make a PR that would be great (and probably make it faster to get merged in).
