### ISSUE TITLE
fastavro and avro expect/generate different binary blob

### ISSUE THREAD

**Issue by gaborbernat** [fastavro/fastavro#456]
Hello, I have a case of fastavro and avro library generating and expecting different binaries when serializing a large payload. The sole difference between avro and fastavro output is the presence of a lonely ``(`` at the start of the fastavro one, which is lacking in case of avro. 

However, what's encoded by Avro cannot be decoded by fastavro and the other way around because of this. Any idea what could be inserting this extra ``(`` at the start of the fastavro encoding?

**Comment by scottbelden** [comment]
By start do you mean the very first byte in the binary? Are you able to provide a sample script that shows the problem?

**Comment by gaborbernat** [comment]
Hello, yes the very first byte. Sadly this is a huge schema with a huge payload so isolating a minimal reproducer is not easy, hence if you have any ideas to track down the issue here? Can't debug the code itself sadly because it's a c-extension.

**Comment by scottbelden** [comment]
Are you using the normal writer function for both? If so, both files should start with `b'Obj1` which is hex Ox4F626A01. Is that how the file starts when using the avro library?

Also, if you take the serialized result from fastavro, is fastavro able to deserialize it?

**Comment by gaborbernat** [comment]
Here's my repro code without the schema or large dump:

```
import json
from io import BytesIO
from pathlib import Path

from avro.io import DatumReader, BinaryDecoder
from avro.schema import parse
from fastavro import parse_schema, schemaless_reader, schemaless_writer, json_writer

blob = Path("bre.dump").read_bytes()
avro_schema = next(i for i in parse(Path("3.1.avsc").read_text()).schemas if i.name == "ok")

reader = DatumReader()
with BytesIO(blob) as binary_input:
    binary_decoder = BinaryDecoder(binary_input)
    raw = reader.read_record(avro_schema, avro_schema, binary_decoder)


fastavro_schema = parse_schema(json.loads(Path("3.1.avsc").read_text()))
with BytesIO(b"(" + blob) as binary_input:
    result = schemaless_reader(binary_input, fastavro_schema, fastavro_schema)

assert raw == result
```
Where the blob starts with ```b'V0e962779-0d5f-42ff-bfae-d094e07c77b4_stable\x02\x0ebad...'```. If I remove the ``b"("`` from the above code fastavro fails... they seem equal codeto me 🤔 ``'0e962779-0d5f-42ff-bfae-d094e07c77b4_stable'`` is a string within the schema and ``bad`` too.

**Comment by scottbelden** [comment]
Just so I'm clear...

1. The example you gave works as is?
2. If you change `with BytesIO(b"(" + blob) as binary_input:` to `with BytesIO(blob) as binary_input:` then the code fails with the exception you mentioned?
3. How is the binary being written? I'm assuming using `fastavro.schemaless_writer` and `avro.io.BinaryEncoder`?

**Comment by gaborbernat** [comment]
It's written using avro that does not generate with the leading (. Avro decodes well, fastavro fails to load. Upon pretending the ( fastavro decodes well.  Fastavro also generates the leading ( if I try to write the raw record.

**Comment by scottbelden** [comment]
I'm starting to get an idea of what might be going on, but a few more questions...

1. It looks like from the exception that the first thing it tries to do is read a union. Can you tell me how long that union is?
2. When writing the binary, can you tell me index in the union is the right one for the data that you are writing?
3. Can you tell me what type of data is being written for that union?

**Comment by scottbelden** [comment]
Also, is the same schema being used for both writing and reading?

**Comment by gaborbernat** [comment]
Yes same schema used. I'll try to create a minimal reproducer tomorrow and come back.

**Comment by scottbelden** [comment]
How are you writing the binary?

I think I now get it.

The schema you have is a union, but I just noticed that you have this line:

`avro_schema = next(i for i in parse(Path("3.1.avsc").read_text()).schemas if i.name == "ok")`

And so the schema you pass to the standard avro library is one of the schemas from that union. I'm betting it's index `20` from that union. And so when you are using the standard avro library, you are calling `reader.read_record()` because you already picked out the record schema that you want.

However, when you are using fastavro, you are giving it the full union schema and it's failing because it reads `b"V"` and interprets that as index 43 in the union (which is probably more than your union has based on the `IndexError: list index out of range`.

If you were to change:

```python
avro_schema = next(i for i in parse(Path("3.1.avsc").read_text()).schemas if i.name == "ok")
reader = DatumReader()
with BytesIO(blob) as binary_input:
    binary_decoder = BinaryDecoder(binary_input)
    raw = reader.read_record(avro_schema, avro_schema, binary_decoder)
```

to

```python
avro_schema = parse(Path("3.1.avsc").read_text())  # use the full union schema
reader = DatumReader()
with BytesIO(blob) as binary_input:
    binary_decoder = BinaryDecoder(binary_input)
    raw = reader.read(avro_schema, avro_schema, binary_decoder)  # change read_record to read
```

Then both would work with the binary that starts with `b"("

On the other hand, you could probably change:

```python
fastavro_schema = parse_schema(json.loads(Path("3.1.avsc").read_text()))
```

to

```python
fastavro_schema = parse_schema(json.loads(Path("3.1.avsc").read_text()))[20]
```

And then fastavro would read the binary that begins with `b"V"`

**Comment by gaborbernat** [comment]
You were spot on, thanks for helping on that 👍
