### ISSUE TITLE
Improve decimal schema validation

### ISSUE THREAD

**Issue by matpuk** [fastavro/fastavro#457]
Currently, I found 3 issues with decimal schema:

1. Negative values for precision and scale are allowed
2. There is no check that specified precision will fit into fixed number of bytes
3. There is no check that precision >= scale

Is it ok to fix all of the issues in one PR?

**Comment by scottbelden** [comment]
I thought number 2 was fixed in https://github.com/fastavro/fastavro/pull/453. Is it not?

As for 1 and 3, it would be fine to fix both in a single PR as those both sound like pretty simple fixes.

**Comment by matpuk** [comment]
This is different from #453. Previously I fixed decimal values serialization (checks that must be performed for every value). But now it's about schema parsing stage. We should check this (https://avro.apache.org/docs/current/spec.html#Decimal):
'''
An array of length n can store at most floor(log_10(2 ** (8 × n - 1) - 1)) base-10 digits of precision
'''

I thought about fixing it in #453, but decided to group schema parse time issues separately.

**Comment by scottbelden** [comment]
Ah, I see. That seems like a simple check as well that could all be in the same PR.
