### ISSUE TITLE
timestamp-millis does not serialize accurately for some cases

### ISSUE THREAD

**Issue by hoogamaphone** [fastavro/fastavro#458]
When serializing a `timestamp-millis` field and then deserializing it, it can sometimes be off by milliseconds.

Here's an example script that uses `fastavro==0.24.0`

```python
import datetime
import io

import fastavro
import pytz


def record_to_binary(data, schema):
    with io.BytesIO(b"") as output_file:
        fastavro.writer(output_file, schema, [data])
        output_file.seek(0)
        bytes_ = output_file.read()
    return bytes_


def binary_to_record(binary, schema):
    with io.BytesIO(binary) as binary_file:
        return next(fastavro.reader(binary_file, reader_schema=schema))


schema = {
    "type": "record",
    "name": "example",
    "fields": [{"name": "datetime", "type": {"type": "long", "logicalType": "timestamp-millis"}}],
}
parsed_schema = fastavro.parse_schema(schema)

my_date = datetime.datetime(2243, 1, 1, 0, 0, 0, 64000, tzinfo=pytz.utc)
expected_data = {"datetime": my_date}
binary = record_to_binary(expected_data, parsed_schema)
actual_data = binary_to_record(binary, parsed_schema)
print(f"expected_data={expected_data}")
print(f"  actual_data={actual_data}")
assert actual_data == expected_data
```

I get the following output when I run this script:

```
expected_data={'datetime': datetime.datetime(2243, 1, 1, 0, 0, 0, 64000, tzinfo=<UTC>)}
  actual_data={'datetime': datetime.datetime(2243, 1, 1, 0, 0, 0, 63000, tzinfo=<UTC>)}
Traceback (most recent call last):
  File "/opt/project/timestamp_round_trip.py", line 34, in <module>
    assert actual_data == expected_data
AssertionError
```

This error does not occur in the `avro-python3` library. I've gone through the code differences, and the only thing I can find is that `fastavro` makes use of [`datetime.timedelta.total_seconds()`](https://docs.python.org/3/library/datetime.html#datetime.timedelta.total_seconds). 

Some other dates that I've been able to replicate this issue for are:
```
datetime.datetime(1974, 4, 4, 0, 0, 0, 1000, tzinfo=pytz.utc)
datetime.datetime(2515, 1, 1, 0, 0, 0, 37000, tzinfo=pytz.utc)
datetime.datetime(881, 1, 1, 0, 0, 0, 257000, tzinfo=pytz.utc)
```

I am running these in a docker container that is running CentOS 7.5

Lastly, here's a test that uses hypothesis, which is how I found the failing examples

```python
import hypothesis
import hypothesis.strategies

@hypothesis.given(hypothesis.strategies.datetimes(timezones=st.just(pytz.utc)))
@hypothesis.settings(print_blob=True, deadline=None)
def test_datetime_round_trip(given_datetime: datetime.datetime):
    datetime_millis = given_datetime.replace(microsecond=given_datetime.microsecond // 1000 * 1000)
    schema = {
        "type": "record",
        "name": "example",
        "fields": [{"name": "datetime", "type": {"type": "long", "logicalType": "timestamp-millis"}}],
    }
    parsed_schema = fastavro.parse_schema(schema)

    expected_data = {"datetime": datetime_millis}
    binary = record_to_binary(expected_data, parsed_schema)
    actual_data = binary_to_record(binary, parsed_schema)
    assert actual_data == expected_data

**Comment by scottbelden** [comment]
Thanks for the report. The test case should hopefully make this easier to track down. That is quite bizarre, but I think you might be right about `total_seconds()`. I need to check the code, but I'm assuming we are creating a delta between the given time and the epoch and now that I look at the docs they do mention `Note that for very large time intervals (greater than 270 years on most platforms) this method will lose microsecond accuracy.`

Of course, that doesn't quite answer the case of `datetime.datetime(1974, 4, 4, 0, 0, 0, 1000, tzinfo=pytz.utc)` as that should be close enough.

I'll try to take a look soon.

**Comment by hoogamaphone** [comment]
Yeah, the 1974 date definitely made me scratch my head

**Comment by scottbelden** [comment]
I took a look at the 1974 case and the delta is correct at `1554 days, 0:00:00.001000` and the `total_seconds` seems correct at `134265600.001` but when multiplied by the MLS_PER_SECOND the result is `134265600000.99998` and since we cast that to an `int` we lose the millisecond.

I think this can be fixed by doing the math on the `delta.days`, `delta.seconds`, and `delta.microseconds` like they do in the avro library. I'll try it out along with the other problem values you found and see how it goes.

**Comment by scottbelden** [comment]
Should be fixed by https://github.com/fastavro/fastavro/pull/459. I'll probably try to get a new release out in the next week or so.
