### ISSUE TITLE
Duplicate deflate compression

### ISSUE THREAD

**Issue by alistairking** [fastavro/fastavro#463]
I'm very new to this project, so my apologies if I've missed something obvious, but it seems that the pure-python writer compresses each block twice when using deflate:
https://github.com/fastavro/fastavro/blob/master/fastavro/_write_py.py#L281

Looking at the git blame around these lines it seems that it might have been some mess up with the merge of two feature branches. (https://github.com/fastavro/fastavro/commit/f412823fadb048478e40c10e1f6d4776aadcab04 and https://github.com/fastavro/fastavro/commit/53ed64d95d4f82875d1238b1f76d4d87547e40e1)

It doesn't impact the correctness of the resulting data, but it does seem like a waste of CPU time.

**Comment by scottbelden** [comment]
Oh wow, good catch. This is definitely not intentional and I'll push a change to remove the extra line.

**Comment by scottbelden** [comment]
Resolved via https://github.com/fastavro/fastavro/commit/9b0cb9154df13e7bcf1b3eaf88c8ae7d6065666a
