### ISSUE TITLE
Facing issues writing a date object

### ISSUE THREAD

**Issue by vim345** [fastavro/fastavro#470]
I have a field that has the logicalType of date and its type is int. I'd expect a python date object or a date ISO string such as "2015-05-04" to be automatically parsed to the corresponding int number that is supported by the avro schema. However, I get an error. Here's my code snippet:

```
import datetime
from fastavro import writer, reader, parse_schema

schema = {
    "doc": "A weather reading.",
    "name": "Weather",
    "namespace": "test",
    "type": "record",
    "fields": [{"name": "ddd", "type": "int", "logicalType": "date",},],
}

parsed_schema = parse_schema(schema)

# 'records' can be an iterable (including generator)
records = [
    # {"ddd": "2015-04-04"},
    {"ddd": datetime.date(2015, 4, 4)},
    # {"ddd": 123},
]

# Writing
with open("weather.avro", "wb") as out:
    writer(out, parsed_schema, records)

# Reading
with open("weather.avro", "rb") as fo:
    for record in reader(fo):
        print(record)

```

Here's the error:
```
python test.py
Traceback (most recent call last):
  File "fastavro/_write.pyx", line 351, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 69, in fastavro._write.write_long
TypeError: an integer is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 23, in <module>
    writer(out, parsed_schema, records)
  File "fastavro/_write.pyx", line 696, in fastavro._write.writer
  File "fastavro/_write.pyx", line 649, in fastavro._write.Writer.write
  File "fastavro/_write.pyx", line 387, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 377, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 321, in fastavro._write.write_record
  File "fastavro/_write.pyx", line 386, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 351, in fastavro._write.write_data
  File "fastavro/_write.pyx", line 69, in fastavro._write.write_long
TypeError: an integer is required on field ddd
```

Note that I'm using Python 3.7 and fastavro 1.0.0.

Any idea what I'm doing wrong here?

**Comment by ksunden** [comment]
```
schema = {
    "doc": "A weather reading.",
    "name": "Weather",
    "namespace": "test",
    "type": "record",
    "fields": [{"name": "ddd", "type":{"type": "int", "logicalType": "date",}},],
}
```

The logical type must be specified as part of the type schema itself, not just thrown in at the same level as "name".

Admittedly it looks a little funky, but it does work ([Avro docs](https://avro.apache.org/docs/current/spec.html) themselves do not give any docs in the spec for something using specifically logicalType in a field (or similar), but this is consistent with behavior for other things, such as arrays, maps, enums, and records, which similarly add keys to the schema on top of "type")

**Comment by scottbelden** [comment]
I should probably take this as a task to at the minimum add an example or two in the docs.

Perhaps the better solution would be to try to catch some of these common errors when parsing the schema though I think they would probably just be exposed as warnings, like "it looks like you want this to be a logical type but it should be formatted as such".

**Comment by vim345** [comment]
Oh, right. I totally forgot about nesting the type definition

`I should probably take this as a task to at the minimum add an example or two in the docs.`
Having an example here in the docs would be great, but I wish they had it in the official AVRO [specs page](https://avro.apache.org/docs/current/spec.html#Date). What they have a very simple definition and there's no mention of defining it as a nested property inside the `type`. 

Thank you for looking at this. I really appreciate it.
