### ISSUE TITLE
Typo in the docs "from fastavro import load_schema"

### ISSUE THREAD

**Issue by QinBa** [fastavro/fastavro#471]
The import in the example 
https://github.com/fastavro/fastavro/blob/4777a11dbc718b05ca8a244e7a0ecc080f0d50d6/fastavro/_schema_py.py#L458  should really be `from fastavro.schema import load_schema`

**Comment by scottbelden** [comment]
Do you get an error? I just verified that `from fastavro import parse_schema` works for me.

**Comment by ksunden** [comment]
@scottbelden They were talking about `load_schema`, not `parse_schema`, `parse_schema` is explicitly set in `__init__.py`, `load_schema` is not:

https://github.com/fastavro/fastavro/blob/4777a11dbc718b05ca8a244e7a0ecc080f0d50d6/fastavro/__init__.py#L61

**Comment by scottbelden** [comment]
I'm sorry, I completely misread that. Fixed in https://github.com/fastavro/fastavro/commit/f468264b0f86661f1893c8b32bc592fb44e39c75
