### ISSUE TITLE
Build wheel for Python 3.9

### ISSUE THREAD

**Issue by scottbelden** [fastavro/fastavro#473]

**Comment by scottbelden** [comment]
Travis Status: https://travis-ci.community/t/python-3-9-0-build/10091

**Comment by gaborbernat** [comment]
Did you consider migrating from travis to Github Actions, that's much better at supporting newer pythons?

**Comment by scottbelden** [comment]
I had never really heard of Github Actions until yesterday when I attempted to start trying to build the new wheels. It does seem like it might be the better approach and so I was going to try to look into it when I had a moment.

**Comment by gaborbernat** [comment]
If you want some example how I set this up for my projects, also using tox https://github.com/tox-dev/tox-ini-fmt/blob/main/.github/workflows/check.yml and https://github.com/pypa/virtualenv/blob/main/.github/workflows/check.yml

**Comment by scottbelden** [comment]
Thanks for the examples! That was probably one of the first things I was going to search for when starting to look into this.

**Comment by AWSjswinney** [comment]
I just opened pull request https://github.com/fastavro/fastavro/pull/475 which adds arm64 builds to Travis CI. As far as I know, GitHub Actions doesn't support native builds on Arm, but it might be possible to use Docker + QEMU to build arm64 wheels. I'd prefer to use Travis because it's easier, but I'm happy to defer to your opinion. Which would you prefer?

**Comment by gaborbernat** [comment]
I'd personally use Travis then for arm64, and Github Actions for normal.

**Comment by scottbelden** [comment]
I think I agree with @gaborbernat. If Arm isn't supported by github actions then I probably wouldn't be opposed to keeping travis for arm builds.

**Comment by AWSjswinney** [comment]
Okay, thanks. I'll modify my pull request accordingly.
