### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [fastavro/fastavro#479]
**Summary**
Installing fastavro on aarch64 via pip using command "pip3 install fastavro" tries to build wheel from source code.

**Problem description**
fastavro doesn't have wheel for aarch64 on PyPI repository. So, while installing fastavro via pip on aarch64, pip builds wheel for same resulting in it takes more time to install fastavro. Making wheel available for aarch64 will benefit aarch64 users by minimizing fastavro installation time.

**Expected Output**
Pip should be able to download fastavro wheel from PyPI repository rather than building it from source code.

@fastavro-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make fastavro wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by scottbelden** [comment]
This is being worked on here: https://github.com/fastavro/fastavro/pull/475.

It was on hold while I was re-working some of the CI stuff, but we can now get back to it.

**Comment by scottbelden** [comment]
Wheels should now be available on pypi for Python 3.6 to 3.8. The 3.9 build was timing out for some reason so I couldn't get that one released. Hopefully that will get resolved soon.
