### ISSUE TITLE
Schemaless reader not working if reader and writer schema differs by just "doc" attribute

### ISSUE THREAD

**Issue by shakti-garg** [fastavro/fastavro#486]
**Scenario:** 
In below case, reader and writer schema are same except that one of the schema(reader in this case) has "doc" attribute to the union field.
As a result, it tries to match schemas and errors at _read.pyx -> read_union (line no 450) with below exception:
`fastavro._read_common.SchemaResolutionError: Schema mismatch: {'type': 'record', 'name': 'test.ApplicationSubmitted', 'fields': [{'name': 'applicationId', 'type': 'string'}, {'name': 'data', 'type': 'string'}]} is not null
`

**Proposed Solution**
Add a flag for enable/disable of "doc" attribute in the parse_schema method of _schema.pyx.
This will help schemaless reader to ignore "doc" attribute when it parses reader/writer schemas. 

**Reader schema**
```
{
        "name": "Message",
        "type": "record",
        "namespace": "test",
        'doc': 'test',
        "fields": [
            {"name": "id",
             "type": "long",
             'doc': 'test'},
            {"name": "payload",
             'doc': 'test',
             "type": [
                 'null',
                 {
                     "name": "ApplicationSubmitted",
                     "type": "record",
                     'doc': 'test',
                     "fields": [
                         {"name": "applicationId", 'doc': 'test', "type": "string"},
                         {"name": "data", 'doc': 'test', "type": "string"}
                     ]
                 }
             ]}
        ]
    }
```

**Writer Schema**
```
{
        "name": "Message",
        "type": "record",
        "namespace": "test",
        "fields": [
            {"name": "id",
             "type": "long"},
            {"name": "payload",
             "type": [
                 'null',
                 {
                     "name": "ApplicationSubmitted",
                     "type": "record",
                     "fields": [
                         {"name": "applicationId", "type": "string"},
                         {"name": "data", "type": "string"}
                     ]
                 }
             ]}
        ]
    }
```

**Comment by scottbelden** [comment]
Thanks for the report. This was actually much more than just the `doc` attribute as it could break if a new type was added to the union like in this case:

https://github.com/fastavro/fastavro/blob/d74dc395203cfbefa9966ce6840dc85acebbdd32/tests/test_schema_evolution.py#L330-L365

Fortunately, I think [the fix](https://github.com/fastavro/fastavro/pull/487) is pretty easy and should hopefully be merged and a new release can be published soon.

**Comment by shakti-garg** [comment]
Thanks scott for the fix. This is indeed very simple than i proposed. 

But i still have one opinion that only the "doc" attribute shouldn't be considered as a case for schema evolution. I am referring to the logic here for matching reader and writer schemas, when they only differ on "doc" attribute. I can see some processing power unnecessarily spent into it.

**Comment by scottbelden** [comment]
It's not really that the `doc` is being considered for schema evolution, it's moreso that the reader is being supplied a reader_schema and so we need to check to see if everything is valid.

As for the processing power, it's possible that normalizing the schema (removing `doc` and other attributes that aren't necessary) beforehand could save time in this case, but it would also add processing time in the case where the schemas differ by more than just the `doc` attribute (which I think is probably the more common case).

Some profiling would need to be done to see the effect of a normalization process and while I welcome that analysis, it's probably not something I'm going to look at any time soon.

**Comment by shakti-garg** [comment]
Cool. It makes sense

I will try to do that comparison on my end and update you if i see any concerns.
