### ISSUE TITLE
Schema resolution bug for nullable enums

### ISSUE THREAD

**Issue by 97nitt** [fastavro/fastavro#488]
We stumbled across this fun little bug yesterday. We're using the Confluent Kafka Python client and the Avro serializers/deserializers included with it that use `fastavro` under the hood. We have a record schema that has a nullable enum field in it, and it was recently updated to add a new symbol to that enum field. A new Kafka consumer was started using the updated schema as the "reader" schema. That _should_ have been able to deserialize all of the existing messages in the Kafka topic, but messages that were encoded with the older version of the schema failed to be deserialized with a `SchemaResolutionError`. We confirmed that Java and .Net consumers of the same data had no problems.

I was able to come up with a test case that reproduces the error, removing Kafka from the equation. It also demonstrates that no such error occurs when the Apache Avro library is used. So there appears to be an issue in `fastavro` when attempting to resolve an updated enum schema within the context of a union.

The test case that reproduces the problem can be found here:
https://github.com/97nitt/fastavro-bug

**Comment by scottbelden** [comment]
Thanks for the test case. Can you try installing version `1.2.1` and seeing if you still see the problem? I fixed a similar issue and made that release earlier today and if I try with that version it looks like your tests pass (whereas I see the failure when trying with `1.2.0`)

**Comment by 97nitt** [comment]
Yep, `1.2.1` resolved our issue. Thanks for the quick response!
