### ISSUE TITLE
Validating with named schemas

### ISSUE THREAD

**Issue by gudjonragnar** [fastavro/fastavro#493]
After the change from using a global schema map to passing around named schemas It seems to me that validating a message against a complex schema with nested named schemas is not possible (or I have just missed it).
Previously I would use `fastavro.validation.validate` to validate the a message against a schema. However that fails without the global variable. However using the private API function `fastavro.validation._validate` passing in the datum, schema and my named schemas works.

I don't feel comfortable to simply use the private API, although it works at the moment. Would you consider introducing a function to the public API that wraps the private function, or add `named_schemas` as a keyword only argument to `fastavro.validation.validate`?

**Comment by scottbelden** [comment]
Is there any way you can give an example script showing the problem? The `validate` function is already basically a thin wrapper around `_validate` and basically is just there to ensure that the schema has actually been parsed:

https://github.com/fastavro/fastavro/blob/024f3d7ef86fd548200e35da5c8c94e71246fdcd/fastavro/_validation_py.py#L371-L397

How did you get your `named_schema`? Is it different than the one you get from calling `parse_schema` and then looking at the `__named_schemas` key?

**Comment by gudjonragnar** [comment]
Thanks for the quick response.
So first off, I was using version `0.23.2` before, so quite "old".
I think the mismatch might stem from the fact that the avro schemas I am reading are organized in directories that matches the namespaces. The schemas are read by a tool that generates JAVA classes, and that was the original purpose.
 This structure means that `fastavro.schema.load_schema` can not load referenced schemas properly. From the docs i see that it...
> Will recursively load referenced schemas assuming they can be found in files in the same directory and named with the convention <full_name>.avsc.
Previously the validation would rely on `SCHEMA_DEFS` and thus it would work if I just loaded all my schemas in the correct order, but that is not the case now.
I could (mis)use the internal `_named_schemas` parameter to `load_schema` to pass in those I have already loaded and simply create my own `SCHEMA_DEFS` like object and use with the validation. 

The other option is to somehow transform the dir structure onto a flat format for my purposes.

If we use the Parent/Child example from https://fastavro.readthedocs.io/en/latest/schema.html#fastavro._schema_py.load_schema but lay it out like this
```
├── Child
│   └── Child.avsc
└── Parent
    └── Parent.avsc
```
we have something similar to my case. If I understand correctly `load_schema('/path/to/Parent/Parent.avsc')` would not find the Child. 

So I guess my true problem is not just the validate but also loading schemas. In fact the problems stem from the way the avro schemas are laid out.

Do you have any thoughts on this situation?

I can provide more concrete examples if needed, when I have more time.

**Comment by scottbelden** [comment]
Unfortunately the specification doesn't have any guidance on how lay out large hierarchical schemas on disk and so there are divergences in how the different libraries/tools expect them. [This problem has been brought up in the past](https://stackoverflow.com/questions/63732097/processing-multiple-avro-avsc-files-which-are-in-different-directory-and-refer) but I haven't really looked to see if there's a pseudo-standard way that the other tools expect the directory structure.

Which tool are you using at the moment? Maybe I can do some investigation at some point and potentially add another way of parsing the directory structure in the future.

For the moment though, I think these are the two options:

1. Create a new folder that includes symlinks to all of the other schemas. I just tested this and `load_schema` should be able to load everything in correctly.
2. As you mentioned, provide the `_named_schemas` when calling `load_schema` and make sure to load all the schemas in the correct order again.

To me, option 1 seems like it would be the more robust option. Let me know what you think.

**Comment by gudjonragnar** [comment]
We are using the `avro-maven-plugin` to read the schemas and generate Java classes.
When using the maven plugin we also have to specify the order in which to parse the schemas to handle inter-dependencies, similar to what I was doing using `fastavro 0.23.2`.
One plus I see to this approach is that you don't impose a certain directory structure on the user. At the same time you lose the discovery mechanism that is implemented in `fastavro 1.2.3`.
I think providing an option to parse schemas using "the old way", without having to go into symlinking (and correctly name the files according to the namespace) would be useful for those who have already established projects with a directory structure that does not match the one expected by `load_schema`. At the same time I acknowledge maintaining two ways of loading schema could be a headache.

That being said, I think I will look into a version of option 1.

**Comment by scottbelden** [comment]
How were you previously parsing all the schemas in the right order? Was it essentially something like this?

```python
for file in [
    "path/to/sub_dependency",
    "path/to/dependency",
    "path/to/overall_schema",
]:
    load_schema(file)
```

**Comment by gudjonragnar** [comment]
@scottbelden Yes, basically. On top of that I was gathering the schemas into my own dictionary, where the keys are simplified , instead of the full namespace (just for easier use).

**Comment by scottbelden** [comment]
@gudjonragnar I've been thinking about this some and made an attempt to implement a new `load_schema_ordered` API. This would take in the list of schemas such that the inner dependencies are first and the outer most schema is last. So in the example above where I had the following:

```python
for file in [
    "path/to/sub_dependency",
    "path/to/dependency",
    "path/to/overall_schema",
]:
    load_schema(file)
```

This would turn into:

```python
load_schema_ordered(
    [
        "path/to/sub_dependency",
        "path/to/dependency",
        "path/to/overall_schema",
    ]
)
```

I have a PR with the changes here: https://github.com/fastavro/fastavro/pull/497

If you think something like this would be useful, let me know. Perhaps you could grab one of the wheels that are built during the CI and do some initial testing with it to see if it would work.

**Comment by gudjonragnar** [comment]
At first glance it looks like something I could use. I will take a better look when I find time to test it.

**Comment by scottbelden** [comment]
I went ahead and merged this. It seems like it's in a useable state and I'd rather go ahead and get it out there for people to use if they'd like to.

**Comment by gudjonragnar** [comment]
I was just about to report that I had tested it and it works for my purposes at least.
I only had one minor nitpick, it being that if I had two schemas that depend on a common schema I would have to load the common schema twice. For example:

Schema A depends on C and schema B also depends on C (A and B not the same type). Loading it would mean I would call:
```python
schema_A = load_schema_ordered(['path/to/C', 'path/to/A'])
schema_B = load_schema_ordered(['path/to/C', 'path/to/B'])
```
and loading C twice. For this example it might not make much difference, but possibly with large schema dependency trees, although likely not a deal breaker since this is a one time operation.

**Comment by scottbelden** [comment]
That's a good observation, but I think that's okay. The two ways around that that I can think of would be the following:

1. Have some global state to know previous schemas that have been loaded. This is what used to be done with `SCHEMA_DEFS` and was removed because it would cause non-obvious errors
2. Allow the user to pass the `named_schemas` structure (which is basically the local version of `SCHEMA_DEFS`) into some of these functions since that structure has the knowledge of previous parsed schemas. At the moment though I'm not a fan of users having to really interact with that structure as it feels like it would make for an ugly and unintuitive API.

So for the moment I think being more explicit about the schema dependencies is okay.
