### ISSUE TITLE
load_schema failed when two properties are of same object type

### ISSUE THREAD

**Issue by FelixKJose** [fastavro/fastavro#494]
Hello,

I am using fastavro for loading schema but I am noticing a wierd behavior as when I have two properties of same object type, **load_schema()** failed with following exception:

> Traceback (most recent call last):
>   File "fastavro/_schema.pyx", line 289, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 87, in fastavro._schema.parse_schema
>   File "fastavro/_schema.pyx", line 224, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 269, in fastavro._schema.parse_field
>   File "fastavro/_schema.pyx", line 110, in fastavro._schema._parse_schema
> fastavro._schema_common.UnknownType: com.felix.common.Identifier
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "fastavro/_schema.pyx", line 289, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 87, in fastavro._schema.parse_schema
>   File "fastavro/_schema.pyx", line 224, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 269, in fastavro._schema.parse_field
>   File "fastavro/_schema.pyx", line 110, in fastavro._schema._parse_schema
> fastavro._schema_common.UnknownType: com.felix.Address
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "fastavro/_schema.pyx", line 289, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 87, in fastavro._schema.parse_schema
>   File "fastavro/_schema.pyx", line 224, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 269, in fastavro._schema.parse_field
>   File "fastavro/_schema.pyx", line 110, in fastavro._schema._parse_schema
> fastavro._schema_common.UnknownType: com.felix.common.Period
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/fkj/PycharmProjects/FastAvroTest/fastavrotest/main.py", line 12, in <module>
>     "model_not_working/com.felix.Employee.avsc"
>   File "fastavro/_schema.pyx", line 283, in fastavro._schema.load_schema
>   File "fastavro/_schema.pyx", line 302, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 295, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 283, in fastavro._schema.load_schema
>   File "fastavro/_schema.pyx", line 301, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 373, in fastavro._schema._inject_schema
>   File "fastavro/_schema.pyx", line 337, in fastavro._schema._inject_schema
> Exception: Internal error; You should raise an issue in the fastavro github repository

Interesting thing is when I change the type of one of the properties (**identifier**) [which has same type before], to a different type, then it worked.

I am attaching the codebase with this issue.
[FastAvroTest.zip](https://github.com/fastavro/fastavro/files/5823809/FastAvroTest.zip)

**Comment by scottbelden** [comment]
@FelixKJose Thanks for the report and the easy to run test case. I believe this should be resolved by https://github.com/fastavro/fastavro/pull/495.

I verified that the changes resolve the test case you posted, but if your actual schema is more complicated than the test you provided then I can point you to the wheels during CI and you can install one of those to verify that the new version will work with your full schema. Let me know if you'd like to do that, otherwise I'll plan to get a new release out probably today or tomorrow.

**Comment by FelixKJose** [comment]
Hi @scottbelden Yes, my schema is very complicated, so I will try the fix you pointed and let you know if it solves the issue. If not I would like to have the wheel.
Thank you so much for the very quick rresponse.

**Comment by FelixKJose** [comment]
@scottbelden Could you please provide a wheel, so I could verify whether this resolves my issue with my actual schema?

**Comment by scottbelden** [comment]
Sure. The wheels are at the bottom of these pages:

Windows: https://github.com/fastavro/fastavro/actions/runs/490158044
Linux: https://github.com/fastavro/fastavro/actions/runs/490158045
OSX: https://github.com/fastavro/fastavro/actions/runs/490158046

**Comment by FelixKJose** [comment]
@scottbelden When do you think a new version with this change will be officially released?

**Comment by scottbelden** [comment]
Assuming it works for your full schema I'll probably try to do it tonight or tomorrow morning (so hopefully within 24 hours).

**Comment by FelixKJose** [comment]
@scottbelden Sorry, the wheel doesn't work for the same code that I reported itself, so I am not sure what I am doing wrong. I am attaching my updated code:
[FastAvroTest.zip](https://github.com/fastavro/fastavro/files/5824739/FastAvroTest.zip)

**Comment by FelixKJose** [comment]
@scottbelden Whenever you get time, could you point me what I am doing wrong?

**Comment by scottbelden** [comment]
I pulled your zip down and I think it works for me. Here's what I did:

```bash
python3.7 -m venv py37
source py37/bin/activate
pip install fastavro-1.2.3-cp37-cp37m-macosx_10_14_x86_64.whl
cd fastavrotest/
python main.py
```

After running `python main.py` it printed out the schemas and didn't produce the error like before.

**Comment by FelixKJose** [comment]
@scottbelden Thank you so much. Yes, it was my bad, I have recreated my virtual env and it started working. But when I tested the full schema, I am getting following error:

> Traceback (most recent call last):
>   File "fastavro/_schema.pyx", line 289, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 87, in fastavro._schema.parse_schema
>   File "fastavro/_schema.pyx", line 224, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 269, in fastavro._schema.parse_field
>   File "fastavro/_schema.pyx", line 110, in fastavro._schema._parse_schema
> fastavro._schema_common.UnknownType: com.felix.common.Identifier
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "fastavro/_schema.pyx", line 289, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 87, in fastavro._schema.parse_schema
>   File "fastavro/_schema.pyx", line 224, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 269, in fastavro._schema.parse_field
>   File "fastavro/_schema.pyx", line 110, in fastavro._schema._parse_schema
> fastavro._schema_common.UnknownType: com.felix.Download
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "fastavro/_schema.pyx", line 289, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 87, in fastavro._schema.parse_schema
>   File "fastavro/_schema.pyx", line 224, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 269, in fastavro._schema.parse_field
>   File "fastavro/_schema.pyx", line 96, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 110, in fastavro._schema._parse_schema
> fastavro._schema_common.UnknownType: com.felix.common.Reference
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "fastavro/_schema.pyx", line 289, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 87, in fastavro._schema.parse_schema
>   File "fastavro/_schema.pyx", line 224, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 269, in fastavro._schema.parse_field
>   File "fastavro/_schema.pyx", line 110, in fastavro._schema._parse_schema
> fastavro._schema_common.UnknownType: com.felix.Device
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/felixkizhakkeljose/PycharmProjects/FastAvroTest/fastavrotest/main.py", line 18, in <module>
>     "full_schema/com.felix.ObservationsEnvelope.avsc"
>   File "fastavro/_schema.pyx", line 283, in fastavro._schema.load_schema
>   File "fastavro/_schema.pyx", line 302, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 302, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 302, in fastavro._schema._load_schema
>   [Previous line repeated 1 more time]
>   File "fastavro/_schema.pyx", line 289, in fastavro._schema._load_schema
>   File "fastavro/_schema.pyx", line 87, in fastavro._schema.parse_schema
>   File "fastavro/_schema.pyx", line 224, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 269, in fastavro._schema.parse_field
>   File "fastavro/_schema.pyx", line 224, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 269, in fastavro._schema.parse_field
>   File "fastavro/_schema.pyx", line 96, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 171, in fastavro._schema._parse_schema
>   File "fastavro/_schema.pyx", line 193, in fastavro._schema._parse_schema
> fastavro._schema_common.SchemaParseException: redefined named type: com.felix.common.enums.ConnectivityType

I am attaching the full schema with the sample.
[FastAvroTest.zip](https://github.com/fastavro/fastavro/files/5825258/FastAvroTest.zip)

**Comment by FelixKJose** [comment]
@scottbelden Please let me know if you need anymore information.

**Comment by scottbelden** [comment]
@FelixKJose I had pushed some changes a little while ago that should fix the full schema case. I was just dealing with CI issues but I think I have those resolved. Here are the OSX wheels if you'd like to double check: https://github.com/fastavro/fastavro/actions/runs/490984809

I'll probably make a new release with the fixes tomorrow unless I hear any other issues.

**Comment by FelixKJose** [comment]
@scottbelden Thank you so much. Yes, I tested and load_schema worked. 

But when I use that to publish data to Kafka I am getting following error:

> Traceback (most recent call last):
>   File "fastavro/_write.pyx", line 305, in fastavro._write.write_record
> TypeError: Expected dict, got Row
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/fkj/Library/Caches/pypoetry/virtualenvs/kafka-D_aIjBYi-py3.7/lib/python3.7/site-packages/pyspark/sql/types.py", line 1595, in __getattr__
>     idx = self.__fields__.index(item)
> ValueError: 'get' is not in list
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/fkj/Library/Caches/pypoetry/virtualenvs/kafka-D_aIjBYi-py3.7/lib/python3.7/site-packages/confluent_kafka/serializing_producer.py", line 172, in produce
>     value = self._value_serializer(value, ctx)
>   File "/Users/fkj/Library/Caches/pypoetry/virtualenvs/kafka-D_aIjBYi-py3.7/lib/python3.7/site-packages/confluent_kafka/schema_registry/avro.py", line 234, in __call__
>     schemaless_writer(fo, self._parsed_schema, value)
>   File "fastavro/_write.pyx", line 694, in fastavro._write.schemaless_writer
>   File "fastavro/_write.pyx", line 379, in fastavro._write.write_data
>   File "fastavro/_write.pyx", line 323, in fastavro._write.write_record
>   File "fastavro/_write.pyx", line 379, in fastavro._write.write_data
>   File "fastavro/_write.pyx", line 323, in fastavro._write.write_record
>   File "fastavro/_write.pyx", line 373, in fastavro._write.write_data
>   File "fastavro/_write.pyx", line 173, in fastavro._write.write_array
>   File "fastavro/_write.pyx", line 381, in fastavro._write.write_data
>   File "fastavro/_write.pyx", line 379, in fastavro._write.write_data
>   File "fastavro/_write.pyx", line 313, in fastavro._write.write_record
>   File "/Users/fkj/Library/Caches/pypoetry/virtualenvs/kafka-D_aIjBYi-py3.7/lib/python3.7/site-packages/pyspark/sql/types.py", line 1600, in __getattr__
>     raise AttributeError(item)
> AttributeError: get
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/fkj/PycharmProjects/kafka/src/sparketlframework/main.py", line 26, in <module>
>     topic="observtEnvps1",
>   File "/Users/fkj/PycharmProjects/kafka/tests/common/kafka_producer.py", line 58, in publish
>     on_delivery=delivery_callback,
>   File "/Users/fkj/Library/Caches/pypoetry/virtualenvs/kafka-D_aIjBYi-py3.7/lib/python3.7/site-packages/confluent_kafka/serializing_producer.py", line 174, in produce
>     raise ValueSerializationError(se)
> confluent_kafka.error.ValueSerializationError: KafkaError{code=_VALUE_SERIALIZATION,val=-161,str="get"}

**Comment by FelixKJose** [comment]
@scottbelden Sorry, it was a mistake from my side. I am looking into it. I will update soon

**Comment by FelixKJose** [comment]
@scottbelden Everything working great. So all the issues mentioned in this ticket is resolved. Thank you for the great help.
