### ISSUE TITLE
py.typed file does not get packaged

### ISSUE THREAD

**Issue by faph** [fastavro/fastavro#496]
It seems that the `py.typed` file is not packaged. This means that tools such as MyPy cannot use the type hints and stubs provided with the source code.

This may need an `include_package_data` or similar attribute in `setup.py`.

**Comment by scottbelden** [comment]
Nice catch!

I believe in other libraries I have packaged it with something like this in the `setup` of setup.py:

```python
package_data={"fastavro": ["py.typed"]}
```

I'll double check that and get it resolved shortly.

**Comment by faph** [comment]
Yeah, that should work. See https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html

`include_package_data=True` will simply add all files which have already been committed in Git.

**Comment by scottbelden** [comment]
Resolved via https://github.com/fastavro/fastavro/commit/48dcd7359449fb430e25ca196140b6177fcc78a1.

I'm going to take a look to see if there's any other simple issues I can take care of as well before pushing out a new release, but in either case I'll try to get a new release in a few days.
