### ISSUE TITLE
[Feature Request] Publicly expose `__names_schemas`

### ISSUE THREAD

**Issue by dangreenisrael** [fastavro/fastavro#502]
Hi fastavro team 👋

Before I get to my ask, I just want to thank you for making and maintaining such an awesome library.

My ask is to expose the `__named_schemas` property on schemas loaded with `schema.load_schema` publicly and not prefixed with `__`.

I ask because I'm working on a [library](https://github.com/dangreenisrael/avro-to-python-types) to generate python `TypedDict`s from avro schemas and I wanted to use your `load_schema` functionality to handle resolving schemas that reference others using their full name.

If this is something you would be amenable to, please let me know and I would be happy to work on it.

Thanks for all your time and effort,
Dan

**Comment by scottbelden** [comment]
I'm a bit hesitant about changing the name from `__named_schemas` to `named_schemas`. One reason for the underscores was to indicate the "private" aspect, but the other was to avoid clobbering a custom attribute. The specification states `Attributes not defined in this document are permitted as metadata, but must not affect the format of serialized data.` and I take that to mean that someone theoretically could create a schema like this:

```
schema = {
    'named_schemas': 'a custom attribute'
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'station', 'type': 'string'},
        {'name': 'time', 'type': 'long'},
        {'name': 'temp', 'type': 'int'},
    ],
}
```

The chances of that are probably pretty low, but I figured that the `__` prefix would make the chances basically zero in the case of an accidental clobber.

What would you think about a simple API like this?

```python
get_named_schemas(schema):
    return parse_schema(schema)["__named_schemas"]
```

In your case, your full usage would probably look something like this:

```python
named_schemas = get_named_schemas(load_schema(<dir>))
```

**Comment by dangreenisrael** [comment]
Ah, yes I agree that that would break compliance with the spec. Good call.

As for the `get_named_schemas` approach, that would completely solve my problem. Great solution.

Would you like me to give it a go?

**Comment by dangreenisrael** [comment]
Well, this is embarrassing.    😳

I was just finishing up the tests on implementing this when it hit me that the existing functionality at `expand_schema` will probably be enough for what I am looking to do.

I would be more than happy to finish up the work on this issue, but I would hate for you to have to maintain something that nobody is using.

Thanks again for all your hard work on this project.

I'll close this for now, but feel free to reopen it if you would indeed like this functionality.

**Comment by scottbelden** [comment]
That's great to hear. If it turns out that it won't work then we can implement this, but as you mentioned I don't think there is a need to do that unless there is a need.

**Comment by scottbelden** [comment]
FYI the `named_schemas` argument is now a public argument. While not quite the same as what was being discussed here earlier, you could do the following if desired:

```python
named_schemas = {}
load_schema(schema_path, named_schemas=named_schemas)
```

And then the `named_schemas` dictionary should get populated with the named schemas that were parsed.

**Comment by dangreenisrael** [comment]
Thanks @scottbelden
