### ISSUE TITLE
Add low-level read and skip APIs

### ISSUE THREAD

**Issue by spenczar** [fastavro/fastavro#503]
The official Avro Python library supports low-level APIs for reading and skipping individual fields in an Avro-encoded byte stream. For example, it has functions like [read_enum](https://github.com/apache/avro/blob/afe8fa1adfbed7971c077338cd9441b14503507a/lang/py3/avro/io.py#L536), [skip_enum](https://github.com/apache/avro/blob/afe8fa1adfbed7971c077338cd9441b14503507a/lang/py3/avro/io.py#L556), skip_null, read_null, and so on. I don't think that fastavro has anything like this, so this issue is a feature request to add those functions.

I have a use case for this. I am scanning through and indexing very large amounts of astronomical data which have a [large and complicated schema](https://github.com/ZwickyTransientFacility/ztf-avro-alert/tree/master/schema). Out of the ~180 fields, I actually only care about 5 of them for my purposes. An encoded message might be about 100KB, and I'm interested in about 20 or 30 of those bytes.

Parsing the entire schema document with `avro-python` takes a while - about 10ms. But by using `skip` methods, and only `read`ing the fields I care about, I'm able to get that way down to about 0.3ms. This is a substantial difference for me!

Now, using `fastavro` to read the entire object takes about 0.8ms, which is quite good - but it's outperformed by my hand-tuned code which skips fields using ~`slowavro`~ the official Avro library by about 2x.

In alignment with `fastavro`'s goals, then, I think adding support for low-level `skip` and `read` APIs would be helpful. In really performance-critical or extreme circumstances, it makes it possible to write much faster code, which occasionally is needed.

What do you think about adding `skip` methods, and supporting the low-level `read` functions which are already written in a public API?

**Comment by spenczar** [comment]
By the way, I have noticed the `fastavrio.io.binary_decoder.BinaryDecoder`, but I'm just not sure whether I can depend on it as a part of the public API.

**Comment by scottbelden** [comment]
I think this should be pretty easy to implement and the main reason I hadn't done it in the past was that I didn't realize how it would be used.

For your usage, are you talking about actually interacting manually with the `BinaryDecoder` and calling the `skip_` functions in your code? Or are you talking about providing a reader schema that only contains the fields you care about. For example something like this:

```python
from io import BytesIO
from fastavro import writer, reader


writer_schema = {
    "type": "record",
    "name": "test",
    "fields": [
        {
            "name": "foo",
            "type": "string"
        },
        {
            "name": "enum",
            "type": {
                "type": "enum",
                "name": "enum_field",
                "symbols": ["FOO", "BAR"],
            },
        },
    ],
}

reader_schema = {
    "type": "record",
    "name": "test",
    "fields": [
        {
            "name": "foo",
            "type": "string"
        },
    ],
}

records = [{"foo": "bar", "enum": "FOO"}]

bio = BytesIO()

writer(bio, writer_schema, records)
bio.seek(0)
for record in reader(bio, reader_schema):
    print(record)
```

**Comment by spenczar** [comment]
I was thinking of literally calling the BinaryDecoder with `skip` functions, like here: https://github.com/ZwickyTransientFacility/alertbase/blob/900134179db96007d114a06c1095b6400d29c6d0/src/alertbase/alert.py#L65-L117

I don't really _like_ doing this, because it binds me really tightly to the shape of the writer schema, and I just have to make assumptions - which is why I named that thing "`from_file_unsafe`". If I could use the API you're describing that would be fantastic. Does that work already?

**Comment by scottbelden** [comment]
Theoretically I think it should work. If you have a moment, it would be interesting to see the timing of this approach for the `avro` library to see how it compares to the custom decoder (0.3ms) approach and the normal approach (10ms). I would probably expect it to be in the middle of the two but hopefully a lot closer to the custom decoder.

Here's basically the same example from above but using the `avro` library. Obviously you'd have to use your full writer schema and your condensed reader schema to get a timing to compare to the others.

```python
import json
from io import BytesIO
import avro.schema
from avro.datafile import DataFileReader, DataFileWriter
from avro.io import DatumReader, DatumWriter

writer_schema = {
    "type": "record",
    "name": "test",
    "fields": [
        {
            "name": "foo",
            "type": "string"
        },
        {
            "name": "enum",
            "type": {
                "type": "enum",
                "name": "enum_field",
                "symbols": ["FOO", "BAR"],
            },
        },
    ],
}

reader_schema = {
    "type": "record",
    "name": "test",
    "fields": [
        {
            "name": "foo",
            "type": "string"
        },
    ],
}

w_schema = avro.schema.parse(json.dumps(writer_schema))
r_schema = avro.schema.parse(json.dumps(reader_schema))

bio = BytesIO()

writer = DataFileWriter(bio, DatumWriter(), w_schema)
writer.append({"foo": "bar"})
writer.flush()

bio.seek(0)

reader = DataFileReader(bio, DatumReader(w_schema, r_schema))
for record in reader:
    print(record)
```

**Comment by spenczar** [comment]
Good suggestion. I've written some thorough benchmarks; you can see exactly what I'm doing here: https://github.com/ZwickyTransientFacility/alertbase/compare/benchmarks

The benchmarks compare these deserializers:

| name | description | link |
|------|---------|---|
| safe | Read using official Avro's DataFileReader, don't provide a schema | https://github.com/ZwickyTransientFacility/alertbase/blob/benchmarks/src/alertbase/alert.py#L120|
| manual_decoder | Read using official Avro with skip methods | https://github.com/ZwickyTransientFacility/alertbase/blob/benchmarks/src/alertbase/alert.py#L57 |
| subschema | Read using official Avro, providing a schema with just the fields I need | https://github.com/ZwickyTransientFacility/alertbase/blob/benchmarks/src/alertbase/alert.py#L132 |
| fastavro_safe | Read using fastavro.reader without providing a schema | https://github.com/ZwickyTransientFacility/alertbase/blob/benchmarks/src/alertbase/alert.py#L148 |
| fastavro_subschema | Read using fastavro.reader, providing a schema with just the fields I need | https://github.com/ZwickyTransientFacility/alertbase/blob/benchmarks/src/alertbase/alert.py#L157 |

I ran benchmarks against two cases.

In one case, I repeatedly deserialize a single file with one Avro object inside.

In a second, I repeatedly deserialize a ~110MB gzipped tar file with 2,567 Avro-encoded files inside. This is a more realistic case for my workload, but it will include more extraneous stuff like gzip decompression time - effectively meaning `file.read` takes longer, so times are uniformly a bit higher.

Results (these are the minimum times observed):

| Deserializer | Single-file time (ms) | Tarball time (per object) (ms) | Tarball Data Rate (MB/s) |
| ------- | ---- | ---- | ---- |
| safe | 5.862 | 7.093 | 9.35 |
| manual_decoder | 0.438 | 1.055 | 62.87 |
| subschema | 4.216 | 5.220 | 12.71 |
| fastavro_safe | 0.904 | 1.590 | 41.72 |
| fastavro_subschema | 1.240 | 1.926 | 34.44 |

I don't have a good explanation for why the 'safe' benchmark takes just ~6ms instead of ~10ms that I saw yesterday. It's probably down to differences in measurement - I was being less careful and using `time.monotonic()`, not using `timeit`. I trust these results more.

---

So, yeah - providing a schema which is a subset is a little bit faster than using the writer schema, but it's still pretty slow. For some reason, providing the reader schema to fastavro made things significantly slower. I don't know why that would be.

**Comment by scottbelden** [comment]
That's unfortunate that providing the simple reader schema doesn't provide much of a boost. [As you note here](https://github.com/ZwickyTransientFacility/alertbase/blob/benchmarks/src/alertbase/alert.py#L58-L60), using the skips manually requires knowing the structure of the schema (so if that changes then this code would have to change) and intimate knowledge of the avro specification.

However, I'm not opposed to implementing the skip functions since I think they can help in cases beyond this particular use case of wanting to manually call them. For example, I think the reason the `fastavro_subschema` is slower than `fastavro_safe` is because the subschema case has to do all the normal `read_` functions just like the safe case but also has to do some extra work due to the existence of a reader schema (check for schema mismatches, potentially handle schema evolution cases, etc).

One concern I have though is that `fastavro.io.binary_decoder` is only used for the pure python path (typically on PyPy systems). The equivalent for CPython installs live in fastavro/_read.pyx. And because it seemed a bit too low level for a normal user to mess with, the interface isn't really that polished. Despite that, I think it should be possible to use it... for example, if I locally change the functions to be `cpdef` instead of `cdef` and rebuild, I am able to execute this script which I think is the same concept as your `manual_decoder`:

```python
from io import BytesIO
from fastavro import writer, reader, parse_schema
from fastavro._read import read_record, read_long, read_utf8

VERSION = 1
MAGIC = b"Obj" + chr(VERSION).encode()
SYNC_SIZE = 16
HEADER_SCHEMA = {
    "type": "record",
    "name": "org.apache.avro.file.Header",
    "fields": [
        {
            "name": "magic",
            "type": {"type": "fixed", "name": "magic", "size": len(MAGIC)},
        },
        {"name": "meta", "type": {"type": "map", "values": "bytes"}},
        {"name": "sync", "type": {"type": "fixed", "name": "sync", "size": SYNC_SIZE}},
    ],
}

writer_schema = {
    "type": "record",
    "name": "test",
    "fields": [
        {
            "name": "foo",
            "type": "string"
        },
        {
            "name": "enum",
            "type": {
                "type": "enum",
                "name": "enum_field",
                "symbols": ["FOO", "BAR"],
            },
        },
    ],
}

records = [{"foo": "bar", "enum": "FOO"}]

bio = BytesIO()

writer(bio, writer_schema, records)
bio.seek(0)

# skip header
read_record(bio, HEADER_SCHEMA, {})  # should use skip_record when that exists

block_count = read_long(bio)
assert block_count == 1

# size in bytes of serialized objects in block
_ = read_long(bio)

# foo field
foo_field_value = read_utf8(bio)

print(foo_field_value)
```

**Comment by scottbelden** [comment]
All that being said, I can take a stab at putting in the `skip_` functions over the weekend and then when the CI builds and wheels are available to install, perhaps you could see if you can add it to the timing analysis.

**Comment by spenczar** [comment]
Right, ok - I agree with everything you've said, and would be happy to test out the skip functions once you have them.

I have no particular attachment to `fastavro.io.BinaryDecoder`; if there were a bunch of public `read` methods I'd use those, that's okay.

Definitely my preferred way to do this would be to specify a subschema, and then have `fastavro.read` just skip the fields that are in the writer schema but not the reader one. That sounds really nice.

**Comment by scottbelden** [comment]
Great. I'll let you know when that is ready to test.

> Definitely my preferred way to do this would be to specify a subschema, and then have fastavro.read just skip the fields that are in the writer schema but not the reader one. That sounds really nice.

That would be my preference as well. Maybe there are some optimizations that can done when the `skip_` functions are implemented that will make it so that using the subschema is almost as fast as the custom function.

**Comment by scottbelden** [comment]
@spenczar I put together what I think should be an initial working implementation. I haven't spent any time to do profiling or performance testing yet, but I'm hoping it should be pretty easy for you to re-run your test with the new changes.

Wheels are here:
Windows - https://github.com/fastavro/fastavro/actions/runs/521802879
Linux - https://github.com/fastavro/fastavro/actions/runs/521802875
OSX - https://github.com/fastavro/fastavro/actions/runs/521802874

As you can [see here](https://github.com/fastavro/fastavro/pull/504/files?file-filters%5B%5D=.py#diff-74ec7a83046da309f07747250bd78c184fc044ce69e668f13ee481ce28f09b61), the test cases that do the manual calls to `skip_*` show that it would be painful for users to have to do that themselves and the fact that the interfaces are different depending on whether or not the cython modules are being used is less than ideal. So I'm hoping that the simple approach of using the subschema reader will be sufficient.

**Comment by spenczar** [comment]
Great, thanks! I have implemented a manual decoder using the `skip_` methods there, and I get a hand-tuned `fastavro` decoder which is basically the same speed as my hand-tuned `avro` one - or perhaps a bit faster, but I think that's within my measurement error, and not really significant. Results:

| Deserializer | Single-file time (ms) | Tarball time (per object) (ms) | Tarball Data Rate (MB/s) |
| ---------------- | ---- | ---- | ---- |
| safe | 5.757 | 6.787 | 9.77 |
| manual_decoder | 0.428 | 1.056 | 62.79 |
| subschema | 4.214 | 5.241 | 12.66 |
| fastavro_safe | 0.902 | 1.585 | 41.84 |
| fastavro_manual_decoder | 0.395 | 1.012 | 65.57 |
| fastavro_subschema | 1.116 | 1.789 | 37.08 |

This is on the Linux Python 3.8 wheel, by the way.

I didn't know what to put the 'named_schemas' argument for the low-level method; I assume an empty dict is fine. Code is here: https://github.com/ZwickyTransientFacility/alertbase/commit/62c8bb3b6202112f3e62b8c61bfdd53dc6043b8a#diff-fde9db2995f5a7e57b81282fecd6abb46f91da15339d96dcf78d0d9d20855c16

Thanks for the quick turnaround on this!
