### ISSUE TITLE
Generating classes/types from avro schemas

### ISSUE THREAD

**Issue by gudjonragnar** [fastavro/fastavro#506]
This is not an issue with fastavro, but rather a selfish promotion. I however thought that some people in this community might enjoy checking it out. I didn't see any other way of putting it out there, so please close the issue if this is unwelcome.  

We are using avro at work to establish a message structure between multiple services. Initially the messages were only created in Java code using classes generated from the avro schemas but recently we have some Python applications that need to create messages as well.
My coworker was lamenting the non existent IDE support when creating the messages, as well as mypy not catching errors in message creation. I decided to take a stab at this as a hobby project. The result is a project similar to [avro_gen](https://github.com/rbystrit/avro_gen).

The project can be viewed [here](https://github.com/gudjonragnar/fastavro-gen).

Note that it is very much not complete. It was created with our schemas in mind and it works for those, but there are avro features we are not using that are not currently supported. 

 Any feedback, PR, issues are welcome.

**Comment by scottbelden** [comment]
Thanks for this. There have been a [few people in the past that have requested a similar feature](https://github.com/fastavro/fastavro/issues/287). Hopefully those that need this functionality can find your library useful.

I'm going to close this as this is not something that I expect will be added to fastavro but hopefully if other come looking for this feature they will search for issues and find this.
