### ISSUE TITLE
Named type behaviour in match_schemas

### ISSUE THREAD

**Issue by saska** [fastavro/fastavro#512]
The function _read.match_schemas does not account for named types, producing weird behaviour in unions (immediately matches the first e.g. record it finds). My understanding is avro allows multiple schemas of the same type to be in a union, provided they're named (record, fixed, enum and possibly error, the specification is not all that clear). 

I have a non-passing fork [here](https://github.com/saska/fastavro) which provides expected behaviour in our use case (disclaimers: haven't gone through all cases all that well and comparison should likely be done with a fullname). 

Can look at this more closely if we agree.

**Comment by scottbelden** [comment]
I'm having a bit of trouble understanding the problem. Do you have an example of a writer schema, reader schema, and the data so I can see what you mean?

**Comment by saska** [comment]
I'll try and build an example as soon as I can - ran into this at work and can't share the original schemas.

**Comment by scottbelden** [comment]
Understandable. That's a common problem and so recently I worked on some functions to do some anonymization. They haven't been merged yet, but I do have them in a branch: https://github.com/fastavro/fastavro/tree/utils.

If you are able to use/install that branch, then you should be able to get an anonymized schema and a sample data object by doing this:

```python
from fastavro.utils import anonymize_schema
from fastavro.utils import generate_one

anonymized_schema = anonymize_schema(original_schema)
data = generate_one(anonymized_schema)
```

Of course, you might need to modify the data a little to get it to trigger the case you are talking about.

Let me know if that works. If it does I'll be more likely to merge it sooner. Or if it doesn't then hopefully you can provide some feedback to help improve the anonymization.

Thanks!

**Comment by saska** [comment]
Great that you're working on anonymization, that's probably going to be a huge help! Didn't take me all that long though, hopefully I didn't make a mistake rushing it. Probably better this way anyway, our schemas are kind of large and have a bunch of useless stuff.

The gist of the issue that sparked this was that the following raises `fastavro._read_common.SchemaResolutionError: No default value for somedata_id`.
```
import io

import fastavro

record = {
    "id": "example_id_1234", 
    "data": {
        "otherdata_id": 1234,
        "otherdata_field": "some example data"
    }
}

writer = fastavro.parse_schema({
    "type": "record",
    "name": "root",
    "namespace": "example.space",
    "fields": [
        {
            "name": "id",
            "type": "string"
        },
        {
            "name": "data",
            "type": [
                "null",
                {
                    "type": "record",
                    "name": "SomeData",
                    "fields": [
                        {
                            "name": "somedata_id",
                            "type": "int"
                        },
                        {
                            "name": "somedata_field",
                            "type": "int"
                        }
                    ]
                },
                {
                    "type": "record",
                    "name": "OtherData",
                    "fields": [
                        {
                            "name": "otherdata_id",
                            "type": "int"
                        },
                        {
                            "name": "otherdata_field",
                            "type": "string"
                        }
                    ]
                }
            ]
        }
    ]
})

reader = fastavro.parse_schema({
    "type": "record",
    "name": "root",
    "namespace": "example.space",
    "fields": [
        {
            "name": "id",
            "type": "string"
        },
        {
            "name": "data",
            "type": [
                "null",
                {
                    "type": "record",
                    "name": "SomeData",
                    "fields": [
                        {
                            "name": "somedata_id",
                            "type": "int"
                        },
                        {
                            "name": "somedata_field",
                            "type": "int"
                        }
                    ]
                },
                {
                    "type": "record",
                    "name": "OtherData",
                    "fields": [
                        {
                            "name": "otherdata_id",
                            "type": "int"
                        },
                        {
                            "name": "otherdata_field",
                            "type": "string"
                        },
                        # Fully compatible change
                        {
                            "name": "newdata_field",
                            "type": "string",
                            "default": "new stuff"
                        }
                    ]
                }
            ]
        }
    ]
})

file_ = io.BytesIO()

fastavro.schemaless_writer(file_, writer, record)
file_.seek(0)
fastavro.schemaless_reader(file_, writer, reader_schema=reader)
```

**Comment by scottbelden** [comment]
Thanks for the example script. That definitely helps.

I think your change is on the right track. As you mentioned, some tests need to be fixed because they are currently wrong. For example, this test currently passes but should fail:

https://github.com/fastavro/fastavro/blob/aa574f8101c6496b1d2d30f65f661e99f7c17386/tests/test_fastavro.py#L408-L433

That's because the name in the `new_schema` doesn't match the name in the original `schema`. However, the way a test like that should evolve correctly is by using an alias for the record name which it looks like we currently don't do either. So it's probably worth fixing that up at the same time.

Do you want to submit a PR to fix this? I can certainly help with working with you to get it in a mergeable state if you'd like to do that. Otherwise I can put something together at some point.

**Comment by saska** [comment]
Sure, can probably start checking it out today.
