### ISSUE TITLE
Fastavro unable to parse schema (fastavro._schema_common.UnknownType)

### ISSUE THREAD

**Issue by Ahmedie-m** [fastavro/fastavro#518]
Hello,

I am trying to parse a schema:

`{"type":"record","name":"productView","fields":[{"name":"userId","type":"long"},{"name":"url","type":"string"}]}`

That I have also validated over here: https://json-schema-validator.herokuapp.com/avro.jsp

However, it seems that it is unable to parse it for some reason. As this is the error I am getting:

`fastavro._schema_common.UnknownType: {"type":"record","name":"productView","fields":[{"name":"userId","type":"long"},{"name":"url","type":"string"}]}`

**Comment by scottbelden** [comment]
How are you parsing this? Can you provide a script that fails? It seems to work for me...

```python
In [1]: from fastavro import parse_schema

In [2]: parse_schema({"type":"record","name":"productView","fields":[{"name":"userId","type":"long"},{"name":"url","type":"string"}]})
Out[2]:
{'type': 'record',
 'name': 'productView',
 'fields': [{'name': 'userId', 'type': 'long'},
  {'name': 'url', 'type': 'string'}],
 '__fastavro_parsed': True,
 '__named_schemas': {'productView': {'type': 'record',
   'name': 'productView',
   'fields': [{'name': 'userId', 'type': 'long'},
    {'name': 'url', 'type': 'string'}]}}}
```

**Comment by Ahmedie-m** [comment]
Hey @scottbelden thanks a lot for the fast reply. The issue was that I was passing it as a string instead of a json.
