### ISSUE TITLE
utils.generate_one (with schemaless_writer) does not produce valid Avro file

### ISSUE THREAD

**Issue by JulienPeloton** [fastavro/fastavro#519]
Hi,

https://github.com/fastavro/fastavro/pull/511 recently introduced the capability to generate random data given a schema. I followed the documentation at https://fastavro.readthedocs.io/en/latest/utils.html, but the output file does not seem to be a valid Avro file:

```python
from fastavro import schemaless_writer
from fastavro.utils import generate_one
import fastavro

print(fastavro.__version__)
# 1.3.3

schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'station', 'type': 'string'},
        {'name': 'time', 'type': 'long'},
        {'name': 'temp', 'type': 'int'},
    ],
}

with open('weather.avro', 'wb') as out:
    schemaless_writer(out, schema, generate_one(schema))

print(fastavro.is_avro('weather.avro'))
# False
```

Any ideas? Thanks!

**Comment by scottbelden** [comment]
`schemaless_writer` serializes a record without any schema information and does not produce an avro container file (which is what `is_avro` is looking for).

To do this you would want to use the `writer`. So for example, this would work:

```python
from fastavro import writer
from fastavro.utils import generate_one
import fastavro

print(fastavro.__version__)
# 1.3.3

schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'station', 'type': 'string'},
        {'name': 'time', 'type': 'long'},
        {'name': 'temp', 'type': 'int'},
    ],
}

with open('weather.avro', 'wb') as out:
    writer(out, schema, [generate_one(schema)])

print(fastavro.is_avro('weather.avro'))
# True
```

**Comment by JulienPeloton** [comment]
Many thanks @scottbelden for the quick reply -- indeed it works like a charm.

Having said that, there is some confusion on my side if I follow the documentation -- in all examples, `writer` and `schemaless_writer` produce files with `.avro` extension. Naively, I would expect that something ending with `.avro` would return `True` when checked against `is_avro`. What am I missing here?

**Comment by JulienPeloton** [comment]
I guess there is part of the answer in this thread https://github.com/fastavro/fastavro/issues/201, though the online documentation does not mention it.

**Comment by scottbelden** [comment]
> though the online documentation does not mention it

I'll create an issue to update the documentation to make it a bit more clear (especially the fact that `is_avro` will only work for container files created by the `writer`.

> Naively, I would expect that something ending with .avro would return True when checked with is_avro. What am I missing here?

I think the confusion is that file extensions are a convention and not something to be relied on. The `is_avro` function does not look at the file extension. The example above would have worked if we changed the filename from `weather.avro` to `file_with_no_extension` or `weather.anythinghere` or `weather.txt`.

**Comment by JulienPeloton** [comment]
> I'll create an issue to update the documentation to make it a bit more clear (especially the fact that is_avro will only work for container files created by the writer.

Thanks! 

> I think the confusion is that file extensions are a convention and not something to be relied on.

Agree in theory - though this is very misleading in practice to name different things with the same name...

**Comment by scottbelden** [comment]
> Agree in theory - though this is very misleading in practice to name different things with the same name...

Oh, I see what you mean in that the docs for `schemaless_writer` use `file.avro` as the filename. I'll will include changing that as well in the issue to clean up the docs as I agree that it is a bit misleading.
