### ISSUE TITLE
Writer doesn't obey fixed schemas size

### ISSUE THREAD

**Issue by spenczar** [fastavro/fastavro#522]
The fastavro writer will happily write `bytes` values of any size when writing fixed fields. If there were any invalid values in an input message, then the resulting serialized avro will be corrupted silently. This can lead to very confusing behavior for readers. For example, the reader can get the wrong data out:

```python
import io
import fastavro

buf = io.BytesIO()
schema = {"type": "fixed", "size": 2, "name": "x"}
records = [b'22', b'1', b'22'] # note the middle value, which is 1 byte instead of 2
fastavro.writer(buf, schema, records) # should error, but doesn't

buf.seek(0)
print(list(fastavro.reader(buf)) # prints [b'22', b'12', 'b'2'] which is totally wrong
```

**Comment by scottbelden** [comment]
Thanks! Should be easy to fix. Maybe I can get it this weekend.

**Comment by scottbelden** [comment]
It seems like we should also error out if the data provided is too big. For example, if `records = [b'22', b'333', b'22']`, it seems like an error should happen rather than the roundtrip value being `records = [b'22', b'33', b'22']`. What do you think?

**Comment by spenczar** [comment]
Yes, definitely. A fixed schema's values should be exactly `"size"` bytes long. You should be able to `src.read(schema["size"])` and get the right thing out.
