### ISSUE TITLE
schema.expand_schema fails to consider __named_schemas member

### ISSUE THREAD

**Issue by srfc** [fastavro/fastavro#538]
# Summary

When using `schema.expand_schema` on a schema that was created using `parse_schema(some_dict, some_named_schemas)` it does not consider the `__named_schemas` member on `parse_schema`'s output dict.
This leads to the unexpected behaviour that the schema produced by `parse_schema` has a valid named schema for some key `A` but trying to expand the schema by running `schema.expand_schema(parse_schema(some_dict, some_named_schemas))` throws `UnknownType(A)`.

# Example

Consider the following example:

```
from fastavro.schema import expand_schema
from fastavro import parse_schema

referenced = {
    "com.namespace.dependencies.Dependency": {
        "name": "Dependency",
        "namespace": "com.namespace.dependencies",
        "type": "record",
        "fields": [
            {"name": "sub_field_1", "type": "string"}
        ]
    }
}

original_schema = {
    "name": "MasterSchema",
    "namespace": "com.namespace.master",
    "type": "record",
    "fields": [{
        "name": "field_2",
        "type": "com.namespace.dependencies.Dependency"
    }]
}

schema_works = parse_schema(original_schema, named_schemas=referenced, expand=True) # works
schema_breaks = expand_schema(parse_schema(original_schema, named_schemas=referenced)) # throws UnknownType

```

# Potential cause

I think this behaviour occurs because `parse_schema` is called from `expand_schema` without checking if its input `dict` has a `__named_schemas` member and not passing it on to `parse_schema` explicitly ([_schema.py#L158](https://github.com/fastavro/fastavro/blob/c52dbfd35d7b26945a24d2225f8db3827866170b/fastavro/_schema_py.py#L158)) _and_ the local `named_schemas` dictionary in the `parse_schema` function only being populated from the `__named_schemas` member _after_ the `if expand` check ([_schema.py#L224ff.](https://github.com/fastavro/fastavro/blob/c52dbfd35d7b26945a24d2225f8db3827866170b/fastavro/_schema_py.py#L224)).

# Workaround

Ofc I didn't read the docs properly, otherwise I wouldn't have attempted this at all because what _does work_ to achieve the same goal is simply using `parse_schema` and setting the named parameter `expand` to `True`.

I still think that the behaviour of `expand_schema` on a `dict` with a `__named_schemas` member is unexpected. Do you agree? If so I think I could provide a PR for this.

**Comment by scottbelden** [comment]
I agree that `expand_schema(parse_schema(original_schema, named_schemas=referenced))` should work and the fact that it doesn't but the other does is unexpected. Thanks for finding that!

As you mentioned, there is some code in `parse_schema` that tries to combine any names that are found in the `__named_schemas` key on the schema and the passed in `named_schemas` dict. I think this might be exposing a larger issue of needing to do a better jobs of always combining those two sources.

However, I'd be okay with just resolving the one issue here the way you mentioned and I could open another issue point out the fact that we should better marry those two sources.

If you'd like to make a PR that would be appreciated. Thanks!

**Comment by srfc** [comment]
I see your point that there are two potential sources for `named_schemas` in `parse_schema` and that this leads to some complexity in the implementation.

Nevertheless, I'll create PR (most likely only tomorrow) for this specific issue here using one of the proposed fixes until the `named_schema` unified across those functions.
