### ISSUE TITLE
ambiguous records outside of a union

### ISSUE THREAD

**Issue by krishnaroskin** [fastavro/fastavro#540]
Huge fan of the module. Thanks a lot for making it and maintaining it!

I'm having issues with ambiguous records in a union, so I was excited to see the "tuple solution". That worked great when the records were part of a union. But in my case, those records are also used outside of a union and the tuple tagging breaks those instances.

Naively, I could see write_record testing for a tuple and unpacking it so that the annotated don't get in the way when used outside of a union. But I wonder if dicts could be annotated with a special key, something like "-type" which isn't an allowed field name in Avro, and the value storing fully qualified record name so that records could be lightly typed.

**Comment by scottbelden** [comment]
Outside of a union, the type isn't ambiguous so there was never a need to parse the tuple notation for the type in those cases.  Is the desire to be able to use the tuple notation so that subrecords can be created in a single form (the tuple format) and used everywhere rather than sometimes being tuples and sometimes being dicts?

For example, something like this?

```python
schema = {
    "namespace": "my.test",
    "name": "example_value_schema",
    "type": "record",
    "fields": [
        {
            "name": "field",
            "type": [
                "null",
                {
                    "type": "record",
                    "name": "my_field_type1",
                    "fields": [{"name": "subfield", "type": "string"}]
                },
                {
                    "type": "record",
                    "name": "my_field_type2",
                    "fields": [{"name": "subfield", "type": "string"}]
                }
            ]
        },
        {"name": "field2", "type": "my.test.my_field_type1"},
    ]
}

my_field_type1 = ("my.test.my_field_type1", {"subfield": "foo"})

records = [
    {"field": my_field_type1, "field2": my_field_type1}
]
```

Rather than something like this?

```python
schema = {
    "namespace": "my.test",
    "name": "example_value_schema",
    "type": "record",
    "fields": [
        {
            "name": "field",
            "type": [
                "null",
                {
                    "type": "record",
                    "name": "my_field_type1",
                    "fields": [{"name": "subfield", "type": "string"}]
                },
                {
                    "type": "record",
                    "name": "my_field_type2",
                    "fields": [{"name": "subfield", "type": "string"}]
                }
            ]
        },
        {"name": "field2", "type": "my.test.my_field_type1"},
    ]
}

normal_my_field_type1 = {"subfield": "foo"}
tuple_my_field_type1 = ("my.test.my_field_type1", normal_my_field_type1)

records = [
    {"field": tuple_my_field_type1, "field2": normal_my_field_type1}
]
```

Or is there some other use case that I'm not understanding?

**Comment by scottbelden** [comment]
I think it makes sense to allow the tuples in the non-union cases. The main question I would need to answer is if it affects the performance much.

**Comment by krishnaroskin** [comment]
Would having {"-type": "my_field_type2"} field avoid some of the performance issues? Seems like it would avoid the tuple unpacking and would only need to be checked in cases where it mattered, i.e. the union one. It does seem a little clunky.

Let me know if I can help in any way.

**Comment by scottbelden** [comment]
Thanks. I thought that only applied to record names and didn't realize it applied to the others. I the `-type` hint does make sense. If you'd like to take a stab at a PR then feel free to. Otherwise I'll try to see about implementing it this weekend.
