### ISSUE TITLE
Should return_record_name only work for records?

### ISSUE THREAD

**Issue by scottbelden** [fastavro/fastavro#543]
While working on https://github.com/fastavro/fastavro/issues/536 I realized that the `return_record_name` option currently only returns the tuple representation for records (which matches the documentation we currently have).

However, it feels like it should also work for other named types like `fixed` and `enum`. And in fact the tuple writer works for all types (even primitives like `string`) so theoretically we could have it return the tuple form for any union case being read.

But maybe always returning the tuple form for any union should be a different option? If we were to change `return_record_name` to return any names then that would be a breaking change.

Probably not going to make any changes right now since no one has brought this up yet, but just putting my thoughts here so they don't get forgotten.

**Comment by forsberg** [comment]
This just struck me after coming up with a schema like this:

```avro
{
  "type": "record",
  "name": "Event",
  "namespace": "com.example.events",
  "doc": "Payload for events",
  "fields": [
    {
      "name": "namespace",
      "doc": "Namespace of application emitting event",
      "type": {
        "type": "enum",
        "name": "EventNamespace",
        "symbols": [
          "COMPONENT_1",
          "COMPONENT_2"
        ]
      }
    },
    {
      "name": "eventsource",
      "doc": "Name of application emitting event",
      "type": [
        {
          "type": "enum",
          "name": "Component1Source",
          "symbols": [
            "MAIN",
            "AUX"
          ]
        },
        {
          "type": "enum",
          "name": "Component2Source",
          "symbols": [
            "MAIN",
            "WHATEVER"
          ]
        }
      ]
    }
  ]
}
```

I can write it properly, but I don't get any information about which type `eventsource` was written with.

```python
from fastavro import schemaless_writer, schemaless_reader
from fastavro.schema import load_schema
from io import BytesIO

schema = load_schema("example.avsc")

fp = BytesIO()

schemaless_writer(
    fp, schema, {"namespace": "COMPONENT_1", "eventsource": ("com.example.events.Component1Source", "MAIN")}
)

fp.seek(0)

print(schemaless_reader(fp, schema))
```

**Comment by scottbelden** [comment]
Looking back at my original comments, I think it would be best to introduce a new flag (e.g. `return_named_types`) instead of causing a breaking change by making `return_record_names` return more than just records.

**Comment by forsberg** [comment]
Agree.

**Comment by scottbelden** [comment]
https://github.com/fastavro/fastavro/pull/710 will add `return_named_type` and `return_named_type_override`. With that in place, going back to your original code, if you change:

`print(schemaless_reader(fp, schema))` to `print(schemaless_reader(fp, schema, return_named_type=True))`

It will now print out `{'namespace': 'COMPONENT_1', 'eventsource': ('com.example.events.Component1Source', 'MAIN')}`

**Comment by forsberg** [comment]
Excellent! Many thanks!

**Comment by malteTech** [comment]
Hi! Per here, colleague of Erik. 
I just did a check of our code with master bracnh of fastavro installed locally and we do get the output you describe in https://github.com/fastavro/fastavro/issues/543#issuecomment-1693136695. 
This is awesome and will help us a lot. When do you think this fix will be released?

**Comment by scottbelden** [comment]
Thanks for the reminder. I had tried fixing up another issue and was going to do a release of both, but that fix is turning out to be more difficult than I thought so I'll try to get a new release out today.

**Comment by scottbelden** [comment]
@forsberg @malteTech Version 1.8.3 should be on pypi now
