### ISSUE TITLE
parse_schema always expands names to canonical form

### ISSUE THREAD

**Issue by debradley** [fastavro/fastavro#545]
I think the most likely thing is that I've misunderstood the API, but my expectation is that calling `fastavro.parse_schema(schema, expand=False)` will return a schema that has a non-canonical name + namespace, while `fastavro.parse_schema(schema, expand=True)` will return the canonical form of a single name that is namespace-qualified.

Given that expectation, the following test should pass but does not:

```python
import fastavro
import avro.schema


def test_unexpanded_schema_stays_unexpanded():
    schema_str = """
    {
        "namespace": "confluent.io.examples.serialization.avro",
        "name": "User",
        "type": "record",
        "fields": [
            {"name": "name", "type": "string"},
            {"name": "favorite_number", "type": "int"},
            {"name": "favorite_color", "type": "string"}
        ]
    }
    """

    schema_dict = avro.schema.parse(schema_str).to_json()
    parsed = fastavro.parse_schema(schema_dict, expand=False)

    assert parsed["name"] == "User" # actually => confluent.io.examples.serialization.avro.User
```

In my testing, the `expand` option has no effect. I've tested this with 1.4, 1.3, 1.2 and more.

Am I confused or is this a bug?

**Comment by scottbelden** [comment]
I see you closed this so I assume you answered your question?

To add some information, `parse_schema` will always resolve the namespace/name into a single name and drop the namespace. There is currently no way to change this.

**Comment by debradley** [comment]
Yes, sorry, I should have dug more before opening the issue. I eventually realized that the `expand` option referred to something else and that fastavro always(?) returns schemas in canonical form so I closed the issue.

**Comment by scottbelden** [comment]
`parse_schema` doesn't do all of the canonical form changes, just the one about fullnames. If you did want the actual canonical form, there is a function for that though: https://fastavro.readthedocs.io/en/latest/schema.html#fastavro._schema_py.to_parsing_canonical_form
