### ISSUE TITLE
How to validate that there are no extra field

### ISSUE THREAD

**Issue by FreCap** [fastavro/fastavro#549]
Are there any way to prevent user to insert a new field which is not explicitly registered in schema?

```
{
  "type": "record",
  "name": "Value",
  "namespace": "Person",
  "fields": [
    {
      "name": "name",
      "type": "string"
    }
}
```

should throw an exception if the user passes
```
{
  "name" : "a",
  "age" : 1
}
```

**Comment by scottbelden** [comment]
There is not an option currently. Both this issue and https://github.com/fastavro/fastavro/issues/423 would probably only be solved by a `strict` option where the records must contain exactly the fields specified in the schema (no more, no less).

**Comment by FreCap** [comment]
Thanks Scott, @scottbelden .

I understand the `no more` but I don't fully get the `no less`. Isn't it already forbidden if there is no default value?

**Comment by scottbelden** [comment]
It is not forbidden currently if the field can be `null`. For example, in https://github.com/fastavro/fastavro/issues/423, notice the `invalid_record_3` option. It currently passes validation even though `nullable_union_field` isn't specified.

**Comment by FreCap** [comment]
Thanks @scottbelden !

It seems that you already have a pretty good idea of how this could be changed. if I wanted to implement the feature, would you mind writing down 3-4 points of the things that should change/come together from your point of view? (So I don't need to iterate on the wrong idea if it doesn't align with yours)

I would really appreciate it

**Comment by scottbelden** [comment]
The way I think I imagine this working is that the `writer` function would have a new keyword argument called `strict`.

So the current:

https://github.com/fastavro/fastavro/blob/e082ba399e0c4cb85dbf6d6505742b271e3e1e34/fastavro/_write_py.py#L544-L554

Would be:

```python
def writer(
    fo,
    schema,
    records,
    codec="null",
    sync_interval=1000 * SYNC_SIZE,
    metadata=None,
    validator=None,
    sync_marker=None,
    codec_compression_level=None,
    strict=False,  # <-- New
):
```

That option would need to flow through all the internal calls and would probably only be used in `write_record`. The function currently looks like this:

https://github.com/fastavro/fastavro/blob/e082ba399e0c4cb85dbf6d6505742b271e3e1e34/fastavro/_write_py.py#L222-L237

But would probably need some changes like so:

```python
def write_record(encoder, datum, schema, named_schemas, fname, strict):
    """A record is encoded by encoding the values of its fields in the order
    that they are declared. In other words, a record is encoded as just the
    concatenation of the encodings of its fields.  Field values are encoded per
    their schema."""
    field_names = set()
    for field in schema["fields"]:
        name = field["name"]
        field_names.add(name)
        if strict and name not in datum:
            raise SomeException(f"field `{name}` missing from record")
        if name not in datum and "default" not in field and "null" not in field["type"]:
            raise ValueError(f"no value and no default for {name}")
        write_data(
            encoder,
            datum.get(name, field.get("default")),
            field["type"],
            named_schemas,
            name,
        )
    if strict and (set(datum) - field_names):
        raise SomeException(f"record has additional fields not specified in the schema: {set(datum) - field_names}")
```

**Comment by scottbelden** [comment]
I would expect we should be able to add tests like the following:

```python
    schema = {
        "namespace": "namespace",
        "name": "name",
        "type": "record",
        "fields": [
            {"name": "field_1", "type": "boolean"},
            {"name": "field_2", "type": ["null", "string"], "default": None},
        ],
    }
```

Records that should fail when `strict` is `True`
```python
{"field_1": True, "field_2": "foo", "field_3": "something"}
{"field_1": True}
```

It should fail when using the `writer`, `json_writer`, and `schemaless_writer`.

**Comment by FreCap** [comment]
@scottbelden thanks for the great example! I don't fully follow why it should fail on the second case. (`{"field_1": True}`) since I thought that `defaults` should be handled according to the schema

Should we have two types of strict? e.g. `strict` and `strict_allow_default`

**Comment by scottbelden** [comment]
The specification states that default values are only supposed to be used schema evolution during read time. However, I agree that most people would probably expect the default value to be used if they omit a field with a default. So it probably does make sense to have the two options like you mentioned.

**Comment by nikolovski** [comment]
Hi, are there any updates on this?

**Comment by scottbelden** [comment]
Options `strict` and `strict_allow_default` will be available in the next release. Probably today or tomorrow.

**Comment by antopolskiy** [comment]
Should this functionality be added to `fastavro.validation` as well? Because right now, `strict` parameter of the `validate` function is not consistent with that of `writer`, which is a bit confusing, and AFAIU there is no way to do this kind of no-extra-field validation without using `writer`.

For reference, this is the meaning of `strict` in `validate`:

>strict – If true, fields without values will raise errors rather than implicitly defaulting to None

**Comment by scottbelden** [comment]
That's a good observation about the difference of the options. I don't think it should be too hard to make the `strict` from validate match the `strict` in writer but it could be a breaking change since it would be more restrictive. I'll see if I can find a way to make them match.
