### ISSUE TITLE
It's possible to declare an enum type with invalid symbols.

### ISSUE THREAD

**Issue by pawelrubin** [fastavro/fastavro#551]
According to the Avro [specification](http://avro.apache.org/docs/current/spec.html#Enums) of the `Enum` field, the `symbols` attribute is:
> a JSON array, listing symbols, as JSON strings (required). All symbols in an enum must be unique; duplicates are prohibited. Every symbol must match the regular expression [A-Za-z_][A-Za-z0-9_]* (the same requirement as for names).

So, `symbols` have to be strings and match the regular expression `[A-Za-z_][A-Za-z0-9_]*`.

However, it is possible to use an invalid schema in the `parse_schema` succesfully:

```python
from datetime import datetime
from fastavro import validate, parse_schema

INVALID_SYMBOLS = [None, 1, "Ż", "0", datetime.now()]

schema = {
    "type": "record",
    "name": "foo",
    "fields": [
        {
            "name": "bar",
            "type": {
                "type": "enum",
                "name": "my_enum",
                "symbols": INVALID_SYMBOLS,
            },
        }
    ],
}

for invalid_symbol in INVALID_SYMBOLS:
    record = {"bar": invalid_symbol}
    assert validate(record, parse_schema(schema))
```

**Comment by pawelrubin** [comment]
It should be difficult to add this validation. I'll be more than happy to do so. 🚀

**Comment by scottbelden** [comment]
Thanks for the report. If you'd like to take a stab at implementing it that would be appreciated.

**Comment by scottbelden** [comment]
Resolved via https://github.com/fastavro/fastavro/pull/552
