### ISSUE TITLE
aarch64 wheels not published for latest releases of fastavro

### ISSUE THREAD

**Issue by AWSjswinney** [fastavro/fastavro#554]
Recently pandas wheels for aarch64 were broken which caused fastavro builds to fail as well. This problem has been fixed now and [this build](https://travis-ci.com/github/fastavro/fastavro/jobs/519722900) is likely to succeed if retried. Would it be possible to do an incremental release in order to publish Arm wheels again?

**Comment by scottbelden** [comment]
I believe this should be resolved in `1.4.3`.
