### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by pocman** [fastavro/fastavro#556]
I noticed a confusing behavior when using `fastavro.schemaless_writer`.
`AttributeError: 'NoneType' object has no attribute 'encode'` exception is raised when trying to write a field that should be a string (according to the avro schema) but is actually null.

Here is the exception raised when trying to write a field that should be an int (according to the avro schema) but is actually null.
`TypeError: must be real number, not NoneType`.

I would expect `TypeError: must be string, not NoneType`.

**Comment by scottbelden** [comment]
Yeah, this makes sense. Currently we don't do a lot of actual checking of the data types because it would be slow, but if there is a failure it makes sense to give a more descriptive error. If you'd like to take stab at a PR, feel free to. Otherwise I'll try to clean it up this weekend.
