### ISSUE TITLE
s3 byte range for just schema or row count

### ISSUE THREAD

**Issue by tooptoop4** [fastavro/fastavro#570]
boto3 library has s3 get_object that accepts a byte range (to avoid downloading a whole file but just download selected byte range). if my Avro file is 100mb, can this fastavro library do some byte range seek to only download the s3 object partially (ie the parts that contain header.schema metadata and row count)?

**Comment by scottbelden** [comment]
I don't believe there is currently a way to do this, and I'm not sure if there's even a reasonable way to do this.

While there is a header at the beginning of the avro file, there is no easy way to know ahead of time how many bytes that header is. The length depends on the size of the schema as well as any optional metadata that was included when writing out the avro file.

Then you would have the problem of knowing how many blocks there are in the avro file and the size of those blocks. While there is code in this library to parse all of that information, it's not currently exposed as an API in the way that you would need and I'm not sure yet how it would be done in a reasonable manner if we wanted to.

**Comment by scottbelden** [comment]
Closing this as I don't think there's a good way to support what is being asked for.
