### ISSUE TITLE
fastavro.json_reader throws exception with map of union or array

### ISSUE THREAD

**Issue by ThomasPJordan** [fastavro/fastavro#572]
When testing a new schema I'd written which contains a `map` type whose `values` type is an `array` type, through round trip testing serialisation/deserialisation of a Python dictionary that I expected to be valid for that schema, to/from JSON using `fastavro.json_reader` and `fastavro.json_writer`, I found that the serialisation worked fine and produced the expected JSON string, but deserialisation failed due to a `KeyError` exception when trying to convert the iterable returned by `fastavro.json_reader()` to a `list`. (The `KeyError` error string references one of the keys in the Python input dictionary element that corresponds to the `map` in the schema) 

I downloaded the Github master tarball to look at the code/unit tests and found a unit test which is doing a round trip test (`test_order_of_values_in_map` in `test_fastavro.py` - ) similar to mine, although it uses the AVRO binary serialiser/deserialiser pair `fastavro.writer` and `fastavro.reader`. 

That unit test passes, however if I modify it to test also json_reader/json_writer, but without modify the schema or test data from the original unit test, as follows:

```python
    def roundtrip_binary(self, schema, records):
        new_file = io.BytesIO()
        fastavro.writer(new_file, schema, records)
        new_file.seek(0)

        reader = fastavro.reader(new_file, schema)

        new_records = list(reader)
        return new_records

    def roundtrip_json(self, schema, records):
        new_file = io.StringIO()
        fastavro.json_writer(new_file, schema, records)
        new_file.seek(0)

        reader = fastavro.json_reader(new_file, schema)

        new_records = list(reader)
        return new_records

    def test_order_of_values_in_map(self, binary=True):
        """https://github.com/fastavro/fastavro/issues/303"""
        schema = {
            "doc": "A weather reading.",
            "name": "Weather",
            "namespace": "test",
            "type": "record",
            "fields": [
                {
                    "name": "metadata",
                    "type": {
                        "type": "map",
                        "values": [
                            {"type": "array", "items": "string"},
                            {"type": "map", "values": ["string"]},
                        ],
                    },
                }
            ],
        }
        parsed_schema = fastavro.parse_schema(schema)

        records = [
            {"metadata": {"map1": {"map2": "str"}}}
        ]

        if binary:
            assert records == self.roundtrip_binary(parsed_schema, records)
        else:
            assert records == self.roundtrip_json(parsed_schema, records)
```

Then if I call `test_order_of_values_in_map(binary=False)`, I see the KeyError exception as I a saw with my own schema:

```bash
  File "./schema_test.py", line 289, in roundtrip_json
    new_records = list(reader)
  File "/usr/local/lib64/python3.6/site-packages/fastavro/_read_py.py", line 972, in _elems
    self.return_record_name
  File "/usr/local/lib64/python3.6/site-packages/fastavro/_read_py.py", line 568, in read_data
    return_record_name,
  File "/usr/local/lib64/python3.6/site-packages/fastavro/_read_py.py", line 451, in read_record
    decoder, field['type'], named_schemas, None, return_record_name
  File "/usr/local/lib64/python3.6/site-packages/fastavro/_read_py.py", line 568, in read_data
    return_record_name,
  File "/usr/local/lib64/python3.6/site-packages/fastavro/_read_py.py", line 345, in read_map
    for item in decoder.iter_map():
  File "/usr/local/lib64/python3.6/site-packages/fastavro/io/json_decoder.py", line 138, in iter_map
    del self._current[self._key]
KeyError: 'map1'
```
The unit test schema map `values` type is a union of an array of strings or a map of strings and the test uses an input Python dictionary with the latter (map of strings), however even if I modify it to be a non-unionised array of strings, I get the same problem.
If I change the map values type to be a simple type, e.g., a long, the problem goes away and round trip test passes.

So it looks like the JSON deserialisation does not handle well map `values` types which are arrays and some other complex types.

I notice also that in the unit test module `test_json.py`, there are no unit tests covering the type of structure (maps of complex types), which may be how the problem has not been noticed.

**Comment by scottbelden** [comment]
Thanks for the report and the test case. There is definitely a bug in the decoder and I'll try to look into it a bit closer and see if I can pin point where it is messing up.

**Comment by ThomasPJordan** [comment]
Thanks, Scott!
