### ISSUE TITLE
Enforce schema when using json_writer() or json_reader()

### ISSUE THREAD

**Issue by borgeser** [fastavro/fastavro#580]
Hi,

I have reproduced the example in https://fastavro.readthedocs.io/en/latest/json_writer.html but I've changed some items of the `records` array in order to introduce some type mismatches.

```
from fastavro import json_writer, parse_schema
from io import StringIO

schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'station', 'type': 'string'},
        {'name': 'time', 'type': 'long'},
        {'name': 'temp', 'type': 'int'},
    ],
}
parsed_schema = parse_schema(schema)

records = [
    {u'station': u'011990-99999', u'temp': 0, u'time': 1433269388},
    {u'station': u'011990-99999', u'temp': 22, u'time': "last day"},
    {u'station': u'011990-99999', u'temp': -11, u'time': 1433273379},
    {u'station': u'012650-99999', u'temp': 111.9, u'time': 1433275478},
]

text_stream = StringIO()
json_writer(text_stream, parsed_schema, records)
print(text_stream.getvalue())
```

The 2nd row now has a string `time` instead of a long.
The 4th row now has a float `temp` instead of a int.

So clearly, some of the records doesn't respect the avro schema.

When I run this code, I get this output:

```
{"station": "011990-99999", "time": 1433269388, "temp": 0}
{"station": "011990-99999", "time": "last day", "temp": 22}
{"station": "011990-99999", "time": 1433273379, "temp": -11}
{"station": "012650-99999", "time": 1433275478, "temp": 111.9}
```

No warning, no error, the items are written as-is.

Same thing happens to the `json_reader`.
This code runs flawlessly:

```
from fastavro import json_reader
from io import StringIO

schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'station', 'type': 'string'},
        {'name': 'time', 'type': 'long'},
        {'name': 'temp', 'type': 'int'},
    ]
}

records = """{"station": "011990-99999", "time": 1433269388, "temp": 0}
{"station": "011990-99999", "time": "last day", "temp": 22}
{"station": "011990-99999", "time": 1433273379, "temp": -11}
{"station": "012650-99999", "time": 1433275478, "temp": 111.9}
"""

avro_reader = json_reader(StringIO(records), schema)
for record in avro_reader:
    print(record)
```

I would have expected these two snippets to raise an Exception because of incompatible types. Since I use a schema, I expect the encoder/decoder to respect it.

Is it possible to fix that in the library? Or maybe add a parameter to enforce schema validation?

Thanks.

**Comment by scottbelden** [comment]
The normal `writer` function has a `validator` keyword so it's possible to do something like `writer(fo, schema, records, validator=True)`. I just realized the `json_writer` doesn't currently have a way of passing the `validator` keyword through, but I think that should be pretty easy to fix. I can try to get a PR together to open up that option on the `json_writer`.

In the meantime, as a work around, you can do `validate_many(records, schema)` to do this validation. For example, here is a modified version of your original script:

```python
from fastavro import json_writer, parse_schema
from fastavro.validation import validate_many
from io import StringIO

schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'station', 'type': 'string'},
        {'name': 'time', 'type': 'long'},
        {'name': 'temp', 'type': 'int'},
    ],
}
parsed_schema = parse_schema(schema)

records = [
    {u'station': u'011990-99999', u'temp': 0, u'time': 1433269388},
    {u'station': u'011990-99999', u'temp': 22, u'time': "last day"},
    {u'station': u'011990-99999', u'temp': -11, u'time': 1433273379},
    {u'station': u'012650-99999', u'temp': 111.9, u'time': 1433275478},
]

text_stream = StringIO()
validate_many(records, schema)
json_writer(text_stream, parsed_schema, records)
print(text_stream.getvalue())
```

When executing that, an exception is raised to try to indicate where the problems are:

```python
fastavro._validate_common.ValidationError: [
  "test.Weather.time is <last day> of type <class 'str'> expected long",
  "test.Weather.temp is <111.9> of type <class 'float'> expected int"
]
```

**Comment by borgeser** [comment]
As a alternative before your PR, I'm using the `writer` method like this:

```
text_stream = StringIO()

fastavro._write_py.writer(
    fo=AvroJSONEncoder(text_stream, write_union_type=True),
    schema=parsed_schema,
    records=records,
    validator=True
)

print(text_stream.getvalue())
```

Note that I have to use `fastavro._write_py.writer` instead of `fastavro.writer` because the cython writer in `_write.pyx` doesn't have a `JSONWriter` class.

I don't really understand the difference between [_write_py.py](https://github.com/fastavro/fastavro/blob/master/fastavro/_write_py.py) and [_write.pyx](https://github.com/fastavro/fastavro/blob/master/fastavro/_write.pyx), can you explain me?
I'd like to avoid using private package `_write_py` but it currently looks not possible.

**Comment by scottbelden** [comment]
I have a PR here that I think should fix the problem: https://github.com/fastavro/fastavro/pull/583. I think it's much simpler than what you have in the most recent comment. Let me know what you think.

**Comment by scottbelden** [comment]
This library is intended to be used for both CPython and Pypy. For most libraries, you would just write all `.py` files and it would work on both. But we want it to be more performant so we use Cython to make it faster for CPython. The files that end in `.pyx` are Cython files that get compiled for CPython users. The `.py` files are usually for the Pypy users. The content of both `_write_py.py` and `_write.pyx` is almost identical and the only real difference is that one is for CPython and the other is for Pypy.

One difference is that the `json_writer` and `json_reader` is only in the `.py` file because I didn't feel that it was important to have the JSON reader/writer as performant as the binary reader/writer.
