### ISSUE TITLE
way to put schemas in LocalSchemaRepository() in required format

### ISSUE THREAD

**Issue by saumya2700** [fastavro/fastavro#584]
I have multiple .avsc files and also referenced , LocalSchemaRepository new feature looks good to use but is there any way to read those .avsc files and and put it in LocalSchemaRepository in required format.
Help would be much appreciated.

I hope I am clear on my requirement, for more clarity please see below:

Location.avsc 
Weather.avsc and weather has Location reference

create output like below:

schema_output ='{
        "Location": {
            "name": "Location",
            "type": "record",
            "fields": [{"name": "city", "type": "long"}],
        },
        "weather": {
            "type": "array",
            "items": ["Location"],
        },
    }'

and then just define repository :

LocalSchemaRepository(schema_output)

**Comment by scottbelden** [comment]
There are probably multiple ways you can do this. For example, assuming you had something like this:

```
avro_avscs/
├── location
│   └── Location.avsc
└── weather
    └── Weather.avsc
```

You could load the schemas like this:

```python
import fastavro
from fastavro.repository import AbstractSchemaRepository
import os
import json

class CustomSchemaRepository(AbstractSchemaRepository):
    def __init__(self):
        self.schemas = {}
        for root, folders, files in os.walk("avro_avscs"):
            for file in files:
                name, extension = file.split(".")
                with open(os.path.join(root, file)) as fp:
                    self.schemas[name] = json.load(fp)

    def load(self, name):
        return self.schemas.get(name)

repo = CustomSchemaRepository()

parsed_schema = fastavro.schema.load_schema("Weather", repo=repo)
print(parsed_schema)
```

The only requirement is that the `load` function return the JSON schema for the given name. You can choose how you want to do that. It could be done by pre-reading all the files like in my example, or it could be done by reading the file on demand, or something else completely.

**Comment by saumya2700** [comment]
Awesome @scottbelden and thank you for prompt reply, this example is pretty much going to solve the issue -> loading different schemas from files from different folders.

**Comment by saumya2700** [comment]
@scottbelden When are you planning to release this feature?

**Comment by saumya2700** [comment]
@scottbelden When are you planning to release this feature?

**Comment by scottbelden** [comment]
Oh, let me do that now.

**Comment by scottbelden** [comment]
`1.4.10` is out now
