### ISSUE TITLE
Write null vs None in avro output file

### ISSUE THREAD

**Issue by sinanasa** [fastavro/fastavro#585]
A field set as (in dict)
'ExcutionSettlement': None
prints the same way as 
'ExcutionSettlement': None
Is it not supposed to print null? 
'ExcutionSettlement': null

**Comment by scottbelden** [comment]
I think this is just the difference in how Python represents `null` in memory. For example, running this script:

```python
import fastavro
from io import StringIO

schema = {
    "name": "test",
    "type": "record",
    "fields": [
        {"name": "field_1", "type": ["null", "int"]}
    ],
}

records = [
    {"field_1": None},
]

print(f"In memory representation: {records}")

sio = StringIO()
fastavro.json_writer(sio, schema, records)

print(f"JSON output representation: {sio.getvalue()}")
```

Produces this output:
```
In memory representation: [{'field_1': None}]
JSON output representation: {"field_1": null}
```

Is this what you are talking about?

**Comment by scottbelden** [comment]
Can you provide an example with a script I can run to see what you mean?

**Comment by sinanasa** [comment]
Here is a quick example:

import fastavro
from io import StringIO

schema = {
    "name": "test",
    "type": "record",
    "fields": [
        {"name": "field_1", "type": ["null", "int"]}
    ],
}

records = [
    {"field_1": None},
]

print(f"In memory representation: {records}")

sio = StringIO()
fastavro.json_writer(sio, schema, records)

print(f"JSON output representation: {sio.getvalue()}")

parsed_schema = fastavro.parse_schema(schema)
with open('/test.avro', 'wb') as out:
    fastavro.writer(out, parsed_schema, records)
    
with open('/test.avro', 'rb') as fo:
    avro_reader = fastavro.reader(fo)
    for record in avro_reader:
        print(f"File output: {record}”)


How can I make it print null for file output?

In memory representation: [{'field_1': None}]
JSON output representation: {"field_1": null}
File output: {'field_1': None}


Thanks!

**Comment by scottbelden** [comment]
The best way would be to use the `json_writer` and get the JSON output. So you would do this again:

```python
with open('/test.avro', 'rb') as fo:
    avro_reader = fastavro.reader(fo)
    for record in avro_reader:
        sio = StringIO()
        fastavro.json_writer(sio, avro_reader.writer_schema, records)
        print(f"File output: {sio.getvalue()}”)
```

Alternatively, if you aren't using `bytes` types or other logical types, you could probably get away with using the standard `json` library like so:

```python
import json

with open('/test.avro', 'rb') as fo:
    avro_reader = fastavro.reader(fo)
    for record in avro_reader:
        print(f"File output: {json.dumps(record)}”)
```

However, I would still suggest using the `json_writer` as it will handle bytes types and other logical types correctly.
