### ISSUE TITLE
Feature request: more explicit `ValueError` error output from fastavro.writer

### ISSUE THREAD

**Issue by bolinocroustibat** [fastavro/fastavro#588]
Would it be possible for `fastavro.writer` to raise more explicit `ValueError` when a record doesn't fit with the avro schema provided to the writer? For example when a type or a name doesn't match with the schema, to output where it doesn't match exactly?
Currently it can be extremely tricky to debug for complicated avro schemas.

Thanks for the great work by the way. The package is working nice and fast.

**Comment by scottbelden** [comment]
DO you mind posting an example script of the current failure case?

**Comment by scottbelden** [comment]
Closing this as I'm not exactly sure what the request is without additional information.
