### ISSUE TITLE
support literally converting 

### ISSUE THREAD

**Issue by guanlisheng** [fastavro/fastavro#589]
Hey there,

just wondering whether we can have such an option. for instance, we can convert the "123" to an integer as the schema describes on the fly instead of validator fails.

**Comment by scottbelden** [comment]
I can understand the use case, but at this time I don't feel like it's a good idea for this library to do the data massaging. But I'll leave this open for a while to see if other comments come in.

**Comment by scottbelden** [comment]
I'm going to close this since I don't plan to add support for this.
