### ISSUE TITLE
None as Schema in Writer append mode fails

### ISSUE THREAD

**Issue by toningega** [fastavro/fastavro#591]
In the documentation: https://fastavro.readthedocs.io/en/latest/writer.html

It states in 'a+b' mode the schema is ignored: "Note: When appending, any schema provided will be ignored since the schema in the avro file will be re-used. Therefore it is convenient to just use None as the schema."

However when providing None as schema we get a `TypeError: argument of type 'NoneType' is not iterable`

**Comment by toningega** [comment]
Yes sure, 

I was just following the docs and tried to set schema as `None` when appending to an existing AVRO. 
Below is the code snippet:

```
from fastavro import writer, parse_schema


schema = {
    'doc': 'A weather reading.',
    'name': 'Weather',
    'namespace': 'test',
    'type': 'record',
    'fields': [
        {'name': 'station', 'type': 'string'},
        {'name': 'time', 'type': 'long'},
        {'name': 'temp', 'type': 'int'},
    ],
}
parsed_schema = parse_schema(schema)

records = [
    {u'station': u'011990-99999', u'temp': 0, u'time': 1433269388},
    {u'station': u'011990-99999', u'temp': 22, u'time': 1433270389},
    {u'station': u'011990-99999', u'temp': -11, u'time': 1433273379},
    {u'station': u'012650-99999', u'temp': 111, u'time': 1433275478},
]

more_records = [
    {u'station': u'123456-99999', u'temp': 99, u'time': 1433269389}
]

# Write initial records
with open('weather.avro', 'wb') as out:
    writer(out, parsed_schema, records)

# Write some more records
with open('weather.avro', 'a+b') as out:
    writer(out, None, more_records)
```
This gives me a TypeError: `TypeError: argument of type 'NoneType' is not iterable`

For reference I am using `fastavro==1.4.10`

**Comment by scottbelden** [comment]
Sorry, I just realized I never made a new release after committing the change for this feature. I'll try to get one out today or tomorrow.

**Comment by scottbelden** [comment]
1.4.11 should be out now. Let me know if that resolves this for you.

**Comment by toningega** [comment]
Can confirm it works fine now. Thanks
