### ISSUE TITLE
Appveyor mentioned in README but not used?

### ISSUE THREAD

**Issue by pllim** [fastavro/fastavro#594]
> Copy the windows build artifacts for the new version from https://ci.appveyor.com/project/scottbelden/fastavro to the dist folder

I don't see any `appveyor.yml` in the root dir and the build from link above seems broken. 🤷‍♀️

**Comment by scottbelden** [comment]
Ah, yeah. AppVeyor was used at one point for Windows builds before moving to Github Actions. This is now up to date in https://github.com/fastavro/fastavro/commit/3ecf5a70189a13968ec4fb6a29f2674ee3328a94. Thanks for pointing out these spots that could use some updates.
