### ISSUE TITLE
Fastavro 1.5.0 breaks older code

### ISSUE THREAD

**Issue by dirodriguezm** [fastavro/fastavro#607]
I hve a piece of code that uses `reader.next()` that raises an error on `1.5.0` but not on `1.4.12`:

```
        bytes_io = io.BytesIO(message.value())
        reader = fastavro.reader(bytes_io)
>       data = reader.next()
E       AttributeError: 'reader' object has no attribute 'next'
```

I guess this is not really an issue, but a heads up for people. I fixed this by staying on version 1.4

**Comment by scottbelden** [comment]
Yeah, I knew this would potentially happen. The fix is to change `reader.next()` to `next(reader)` to align with the normal way that one would iterate. The `reader.next()` is an artifact from when this library supported Python 2.

**Comment by scottbelden** [comment]
I'll try to do a better job of putting in a deprecation warning in the future when I know something is going to break (like this).
