### ISSUE TITLE
Getting "Error -5 while decompressing data: incomplete or truncated stream" 

### ISSUE THREAD

**Issue by 5agado** [fastavro/fastavro#617]
I am using version 1.5.1 to load the avro file generated by another program. I have little knowledge about this other program, and can't share the generated avro unfortunately, but I was hoping to get some insight about this error.

I am running the following

```
with open(products_data_path, 'rb') as f:
    nb_products = 0
    avro_reader = reader(f)
    for rows_read, product in enumerate(avro_reader):
        nb_products += 1
```

And getting this
```
      2     nb_products = 0
      3     avro_reader = reader(f)
----> 4     for rows_read, product in enumerate(avro_reader):
      5         nb_products += 1

  File "fastavro/_read.pyx", line 917, in _iter_avro_records
  File "fastavro/_read.pyx", line 826, in fastavro._read.deflate_read_block
  File "fastavro/_read.pyx", line 831, in fastavro._read.deflate_read_block
zlib.error: Error -5 while decompressing data: incomplete or truncated stream
```

The thing is that if I check the avro file with the command line `avro-tools` util, it doesn't find any error at all, and it's able to load all the data. This also allowed me to check that all entries are actually loaded in the loop above, but the fastavro reader throws the error at the end.

**Comment by scottbelden** [comment]
Would you be able to try the same avro file with the standard python `avro` library? I kind of hope it gives the same error, because it looks like they do the same implementation that we do, but if it works there then that would b e a useful data point to know.

Doing a quick search I see some similar errors here: https://stackoverflow.com/questions/32367005/zlib-error-error-5-while-decompressing-data-incomplete-or-truncated-stream-in

And the suggestion there is to use `zlib.decompressobj()` to better handle the decompression. There was a [similar issue with zstandard](https://github.com/fastavro/fastavro/pull/575) that was solved by using the `decompressobj()`, so I think that might be the solution here.

**Comment by 5agado** [comment]
@scottbelden you are right, getting an error with `avro` library too.

```
AssertionError                            Traceback (most recent call last)
/var/folders/bh/sn1709k55xl8yy2w_n1xd9f80000gq/T/ipykernel_97243/3669929203.py in <module>
      1 with open(products_data_path, 'rb') as f:
      2     reader = DataFileReader(f, DatumReader())
----> 3     for rows_read, product in enumerate(reader):
      4         nb_product += 1

~/opt/anaconda3/envs/pdq/lib/python3.7/site-packages/avro/datafile.py in __next__(self)
    559       if self.is_EOF() or (self._skip_sync() and self.is_EOF()):
    560         raise StopIteration
--> 561       self._read_block_header()
    562 
    563     datum = self.datum_reader.read(self.datum_decoder)

~/opt/anaconda3/envs/pdq/lib/python3.7/site-packages/avro/datafile.py in _read_block_header(self)
    506       # Compressed data is stored as (length, data), which
    507       # corresponds to how the "bytes" type is encoded.
--> 508       data = self.raw_decoder.read_bytes()
    509       # -15 is the log of the window size; negative indicates
    510       # "raw" (no zlib headers) decompression.  See zlib.h.

~/opt/anaconda3/envs/pdq/lib/python3.7/site-packages/avro/io.py in read_bytes(self)
    214     nbytes = self.read_long()
    215     assert (nbytes >= 0), nbytes
--> 216     return self.read(nbytes)
    217 
    218   def read_utf8(self):

~/opt/anaconda3/envs/pdq/lib/python3.7/site-packages/avro/io.py in read(self, n)
    156     assert (n >= 0), n
    157     input_bytes = self.reader.read(n)
--> 158     assert (len(input_bytes) == n), input_bytes
    159     return input_bytes
    160 
```

**Comment by scottbelden** [comment]
That's somewhat reassuring, though it doesn't give much insight.

I'll make a branch to use the `decompressobj` and I'm hoping you might be able to test it for me since I haven't been able to reproduce the issue.

**Comment by scottbelden** [comment]
I pushed a new branch, [issue617](https://github.com/fastavro/fastavro/tree/issue617), with the proposed fix. Would you be able to test this for me? You should be able to clone the repo, switch to that branch, and `pip install .`. It does require `Cython` to be installed to compile the extension modules, but if you want to simplify the install and avoid that I think you can modify the setup.py and [comment out `ext_modules=ext_modules,`](https://github.com/fastavro/fastavro/blob/master/setup.py#L48). That will just run the pure python version of the code, but that would be a good enough test.

**Comment by scottbelden** [comment]
Actually, one sec on that. I need to make a few tweaks.

**Comment by scottbelden** [comment]
Okay, should be good to test now. Let me know if that's something you'd be able to help with. If it works I can get out a new release shortly.

**Comment by 5agado** [comment]
Thanks @scottbelden I'll give it a try. Will probably get back to you at the beginning of next week.

**Comment by scottbelden** [comment]
Great to hear. I wish I had a test case to go with it so that there aren't surprise regressions in the future, but since I can't reproduce it then I'll just merge as is. Thanks for your help.
