### ISSUE TITLE
tuple notation even for simple unions with return_record_name

### ISSUE THREAD

**Issue by untereiner** [fastavro/fastavro#625]
Hi,

I am testing a basic example with a  nullable field (ie. The error field can be an ErrorInfo or null)

```
schema = {
    "type": "record",
    "name": "Inbox",
    "fields": [
        {
            "type": "int",
            "name": "id"
        },
        {
            "type": ["null",
                     "string",
                    ],
            "name": "msg_title"
        },
        {
            "type": [
                "null",
                {
                    "type": "record",
                    "name": "ErrorInfo",
                    "fields": [
                        {
                            "name": "message",
                            "type": "string"
                        },
                        {
                            "name": "code",
                            "type": "int"
                        }
                    ]
                }
            ],
            "name": "error",
            "default": "None"
        }
    ]
}

payload = {
    'id': 1234,
    'msg_title': "",
    'error': {'message': 'test', 'code': 1},
}

fp = io.BytesIO()
fastavro.schemaless_writer(fp, fastavro.parse_schema(schema), payload)

# let's see how serialization works fine
fp.getvalue()

# '{"id": 1234, "msg_title": "Hi", "date_sent": ('ErrorInfo', {'message': 'test', 'code': 1})}'

# let's go to the initial position on fp
fp.seek(0)

# deserialize
record = fastavro.schemaless_reader(fp, fastavro.parse_schema(schema), return_record_name=True)

print(record)
```
I expected that for this simple case (only null or errorInfo) the reader did not return a tuple but the actual fields or null
Is this an expected return ?

I am trying to deserialize with pydantic and it complexify very much.

**Comment by untereiner** [comment]
Yes, my bad. My question isn't clear. 
I expected this return `{'id': 1234, 'msg_title': '', 'error': {'message': 'test', 'code': 1}}` since the other branch of the union is null. So it is easy to discriminate compared to unions with to records.

**Comment by scottbelden** [comment]
Oh, so is the problem that you have a large schema where there could be a union of `Name1` and `null` and other parts where there could be a union of `AnotherName1` and `AnotherName2`. So in the first case with the `null` you don't want the tuple because it's unambiguous whereas in the second case with multiple named types it is useful to have the tuple?

**Comment by untereiner** [comment]
Ha exactly thank you, for reformulating. Is it possible ? Or does it break the avro serialisation/deserialisation spec ?

**Comment by scottbelden** [comment]
It doesn't break anything with the spec since the whole tuple notation thing is a feature of this library that doesn't really relate to the specification.

However, it would be a breaking change to change the behavior of `return_record_name` so this request would probably have to be added as a new option. Maybe something like `return_record_name_if_ambiguous`

**Comment by scottbelden** [comment]
Sure

**Comment by untereiner** [comment]
I proposed a PR. It wasn't easy to find a good way to insert the modification. Could you take a look ?
I need this change by next week

**Comment by scottbelden** [comment]
I'll try to make comments and see if we can find something that works.

Also, if you are in a time crunch I would propose forking the repo or monkey patching as I can't guarantee a fix will be available by then.

**Comment by untereiner** [comment]
Thanks and I will use a patched version in the meanwhile.

**Comment by scottbelden** [comment]
Resolved via https://github.com/fastavro/fastavro/pull/626
