### ISSUE TITLE
Bug: `strict_allow_default` validation in `writer` does not see a single extra field when another field is present with default value

### ISSUE THREAD

**Issue by antopolskiy** [fastavro/fastavro#638]
There seems to be a bug with `strict_allow_default` validation. In the following example, it is supposed to fail, because there is no field `"eggs"` in the schema. However, it does not fail on `fastavro==1.6.0`.

```python
from io import BytesIO
from fastavro import writer, parse_schema


def test_avro_schema_json(schema_json, data_json):
    parsed_schema = parse_schema(schema_json)
    writer(BytesIO(), parsed_schema, [data_json], strict_allow_default=True)


test_avro_schema_json(
    schema_json={
        "name": "validation_test",
        "type": "record",
        "fields": [
            {
                "name": "some_field",
                "default": "test",
                "type": "string",
            },
        ],
    },
    data_json={
        "eggs": "eggs"
    },
)
```

I tested reading the file, and in fact it does not contain `"eggs": "eggs"`, only `{"some_field": "test"}`. Since AFAIU this type of `strict_allow_default` validation is used for the exact purpose of not missing any data in the encoded AVRO file, I'd say this is a critical bug for this feature.

However, we add an extra field to the data, e.g.
```python
    data_json={
        "spam": "spam",
        "eggs": "eggs"
    },
```

It fails on both fields: `ValueError: record contains more fields than the schema specifies: eggs, spam`

This seems to happen only if there is another field present with the default value, and that field is absent from the record.

**Comment by scottbelden** [comment]
I created a PR that should fix this: https://github.com/fastavro/fastavro/pull/639

> I tested reading the file, and in fact it does not contain "eggs": "eggs", only {"some_field": "test"}. Since AFAIU this type of strict_allow_default validation is used for the exact purpose of not missing any data in the encoded AVRO file, I'd say this is a critical bug for this feature.

I just want to make sure I understand this comment.

Given data like `{"eggs": "eggs"}` it should provide and error saying that `record contains more fields than the schema specifies: eggs`.

However, if given an empty data like `{}`, it should work just fine because it will use the default value of the field `some_field`.

That's what you expect, right?

**Comment by antopolskiy** [comment]
Exactly right! Thanks!
