### ISSUE TITLE
Wrong encoding with unions that contains an invalid default value

### ISSUE THREAD

**Issue by marcosschroh** [fastavro/fastavro#649]
**Description**: Sometimes data encoding is not done properly when using invalid `avro schema` that contains invalid unions because of wrong default values.

The `avro schema` used in the section **Step to reproduce**  is a schema that contains an `union [string, long]` field  which has a wrong default value `10` (the default should be type `string` because the first element of the union is `string`)

**fastavro version**: `1.6.1`

According to the default value for [union spec](https://avro.apache.org/docs/1.11.1/specification/#schema-record).
> default: A default value for this field, only used when reading instances that lack the field for schema evolution purposes. The presence of a default value does not make the field optional at encoding time. Permitted values depend on the field’s schema type, according to the table below. _### **Default values for union fields correspond to the first schema in the union**_.

**Step to reproduce:** 

```python
schema = {
    'type': 'record',
    'name': 'UnionSchema',
    'fields': [
        {
            'name': 'first_union',
            'type': ['string', 'long'],
            'default': 10
        }
    ],
    'doc': 'Some Unions'
}
```

Parsing the schema with `fastavro` does not raise any errors. Is this behavior expected?

```python
import fastavro

fastavro.parse_schema(schema)

{
    'type': 'record',
    'doc': 'Some Unions',
    'name': 'UnionSchema',
    'fields': [
        {
            'default': 10,
            'name': 'first_union',
            'type': ['string', 'long']
        }
    ],
    '__fastavro_parsed': True,
    '__named_schemas': {
        'UnionSchema': {
            'type': 'record',
            'doc': 'Some Unions',
            'name': 'UnionSchema',
            'fields': [
                {
                    'default': 10,
                    'name': 'first_union',
                    'type': ['string', 'long']
                }
            ]
        }
    }
}
```

Also, the encoding does not raise any errors but it should:

```python
import io

file_like_output = io.BytesIO()
fastavro.schemaless_writer(file_like_output, schema, {})
```

At the moment of decoding it uses the default `10` because it was encoded with the default:

```python
file_like_output.seek(0)

fastavro.schemaless_reader(file_like_output, writer_schema=schema)
# >>> {'first_union': 10}
```

Then this use case works as expected:

```python
schema = {
    'type': 'record',
    'name': 'UnionSchema',
    'fields': [
           {
                'name': 'first_union',
                 'type': ['boolean', 'string'],
                  'default': 10
            }
     ],
    'doc': 'Some Unions'
}

file_like_output = io.BytesIO()
fastavro.schemaless_writer(file_like_output, schema, {})

ValueError: 10 (type <class 'int'>) do not match ['boolean', 'string'] on field first_union
```

**Comment by scottbelden** [comment]
> I think this issue is somehow related to Java. I faced problems generating the JAR files when the union first type didn't match the default.

That should be intentional. The Java code is the reference language for the spec and so it tends to follow the spec much more strictly than other libraries in other languages.

**Comment by scottbelden** [comment]
@woile That's good that they finally relaxed this restriction. I probably should have been paying more attention to the avro issues and maybe I would have held off longer on making the change that made this library more strict.

I'll make a new issue to loosen it back up to the new specification.
