### ISSUE TITLE
New default checking introduced in PR #650 is breaking change and forces the existence of default

### ISSUE THREAD

**Issue by fsiola** [fastavro/fastavro#654]
PR #650 added default checks, but default is not a mandatory field and now it breaks schema validations.

Shouldn't the check happens only when default is explicitly set in the schema?

**Comment by scottbelden** [comment]
@fsiola Could you provide an example of the failure? There are numerous tests that are run that don't use a default value in their schema but those are not failing.

@marcosschroh The default you have is `1570903062179.133` but the avro type is `long`. Should the default instead be just `1570903062179`?

**Comment by fsiola** [comment]
Ok, my fault. My schema has defaults for fields with multiple types. My schema is `type: ['string', 'null']` and default is `None`. So the error saying the default should be of the first type.

**Comment by scottbelden** [comment]
> Ok, my fault. My schema has defaults for fields with multiple types. My schema is `type: ['string', 'null']` and default is `None`. So the error saying the default should be of the first type.

Yes, that is part of the avro specification and was added in the recent change. But if you have suggestions of how to make the error message more obvious or helpful then do let me know.

**Comment by marcosschroh** [comment]
@scottbelden you are right, for my case the default should be `1570903062179`. It was kind of weird that before was working, now all the producers must update before the consumers. Thanks for your help.

**Comment by scottbelden** [comment]
I would assume the extra parts after the decimal got ignored previously, but I haven't tried comparing the two versions to see if that is the case.
