### ISSUE TITLE
Support writting the data type pd.Int64 with null values

### ISSUE THREAD

**Issue by FranArenas** [fastavro/fastavro#658]
As far as i investigated, fastavro doesn't support the writting of dtype pd.Int64 that contains Nan Values.

I think this would be a significant improvement to the project because this will allow to handle missing values that are common in databases.

**Comment by scottbelden** [comment]
Would you be able to provide a simple script that shows the problem? But in general I believe this library doesn't have much support for records that are pandas or numpy types.

**Comment by ksunden** [comment]
note that fastavro is somewhat limited in what types can be encoded to what is valid by the [avro specification](https://avro.apache.org/docs/1.11.1/specification/), which does not have such a directly nullable type idea.

The fundamental issue is that the way avro encodes integers has no room for a NaN type. This is the same reason (although with slightly different actual formatting) you cannot store NaN to a C integer or in a raw numpy array with an int dtype. Every possible sequence of bits corresponds to one and exactly one valid integer and there is nowhere to put the NaN value.

What you can do, depending on context:

- encode as a union of `[null, int]` (this is probably ideal for smaller arrays/single values)
- write a logical type over a relatively arbitrary `bytes` field (not necessarily a _great_ plan, and severely impedes interoperability, but is perhaps the most flexible option)
- encode as two arrays: one with type `int` (the data) and one with type `bool` (the mask) and treat as a masked array (this is the numpy style of missing data representation). This is also what pandas actually does under the hood, they just present it as a single concept.
- Use a sentinel value to represent NaN (this throws out one valid integer, but if the expected range of your data is known, can be feasible) examples would be `-1` if you know your data is non-negative, `2**64-1` or `-2**64` which are just trimming the very edge value off of the range of valid numbers, but would have strange consequences if you rely on overflow behavior  (e.g. doing computations mod 2**64 such as is common in cryptography)
