### ISSUE TITLE
Update docs to clarify zstd encoding support

### ISSUE THREAD

**Issue by alec-heif** [fastavro/fastavro#659]
Hey all,

It seems from [reading the code](https://github.com/fastavro/fastavro/blob/master/fastavro/_write.pyx#L558) that there appears to be support for writing (and reading?) zstd encoding.

It would be great if the [docs](https://fastavro.readthedocs.io/en/latest/writer.html) could be updated to highlight this! Currently the description only says

> codec – Compression codec, can be ‘null’, ‘deflate’ or ‘snappy’ (if installed)

which might lead people to believe that zstd is not supported even though (at least by inspection) that seems to be the case.

**Comment by scottbelden** [comment]
Good point. We should also include the other codecs that are supported. The full list is

- null
- deflate
- snappy
- bzip2
- xz
- zstandard
- lz4

Would you like to submit the PR to update this? Otherwise I can try to get to it soon.

**Comment by scottbelden** [comment]
I double checked and it looks like the codecs are listed in the docs:

https://fastavro.readthedocs.io/en/latest/index.html#supported-features
