### ISSUE TITLE
Schema registry compresses FLOAT default value of 0.0 to 0 and then reader fails to read it as valid

### ISSUE THREAD

**Issue by dcicc4** [fastavro/fastavro#663]
As part of saving data to our schema registry it compacts the default value of '0.0' to '0' this creates an issue when trying to read the schema as 0 is not considered a valid float

Suggested fix: If the scheam_type is FLOAT/DOUBLE and the default isinstanceof Int, caste it to FLOAT instead of rejecting it as invalid. 

https://github.com/fastavro/fastavro/blob/022dbbef27cf5fc349f0d8925bd56e71a3c8317e/fastavro/_schema.pyx#L349
https://github.com/fastavro/fastavro/blob/022dbbef27cf5fc349f0d8925bd56e71a3c8317e/fastavro/_schema.pyx#L180

**Comment by scottbelden** [comment]
I think this makes sense and should be pretty easy to fix. If you'd like to submit a PR please feel free otherwise I will try to get to it when I have a moment.
