### ISSUE TITLE
Example fastavro with KafkaProducer

### ISSUE THREAD

**Issue by pixie79** [fastavro/fastavro#664]
I am trying to use fastavro with KafkaProducer to take a JSON message I have convert it to AVRO where I can validate it against the AVSC. Then put the AVRO bytes message onto a Kafka topic.

The first few steps are working fine, I can convert and validate the JSON string into AVRO ok. I have an issue though when I put the Bytes object onto Kafka topic it seems to be doing it in binary mode instead of recognising it as AVRO. As such I then get a stream off Bytes not a proper AVRO payload in the topic.

Any Ideas where I went wrong or how to fix it?

Here is a copy of the function - https://gist.github.com/pixie79/4ba55e62cb9fa5b5efc8b3ddeb6b307d

Thanks

**Comment by scottbelden** [comment]
What Kafka library are you using? I can attempt to help but I'm less familiar with the Kafka libraries and how they operate.

**Comment by pixie79** [comment]
Hi,

I was attempting to use the python-kafka on Python3.9

Thanks

**Comment by scottbelden** [comment]
When you say `it seems to be doing it in binary mode instead of recognising it as AVRO` what is doing the "recognizing"? It looks like that library has no special support for avro and so from its perspective it is just sending an receiving binary strings. Are you talking about a consumer somewhere that is saying that the message is not an avro message? What is the consumer library?

**Comment by pixie79** [comment]
It looks like they needed to be schemaless AVRO files but with a 5 byte header with the first byte being a 1 followed by 4 bytes which represent the ID of the schema in the attached schema registry.
I have found how to get it to work for both the Confluent and Redpanda registries using FastAvro and the schemaless writer.

Thanks

**Comment by scottbelden** [comment]
Good to hear. I believe the [confluent kafka python library](https://github.com/confluentinc/confluent-kafka-python) does automatically add that 5 byte header but if you've got it working yourself then that sounds great.

**Comment by pixie79** [comment]
It does which is partly where I found the solution however, it also requires librdkafka which is proving tricky to build and a bit heavy for a lambda

**Comment by scottbelden** [comment]
Ah, yeah, that's a good point.
