### ISSUE TITLE
Logical Type - Decimal

### ISSUE THREAD

**Issue by pixie79** [fastavro/fastavro#665]
Hi,

I have an issue when trying to validate data or if i skip validation use the schemaless writer to write data. The problem is happening is our amount fields which are being sent to me as a Base64 Byte Encoded string (which i think is correct format they are stored within Kafka in). But this fails the validation and conversion rules as they don't need to be converted.
The definition for the field is:
```JSON
 {
   "name": "value",
   "type": {
     "logicalType": "decimal",
     "precision": 18,
     "scale": 5,
     "type": "bytes"
   }
 }
```

The value of the example record is currently 'D0JA'

If it helps when I decode it using Spark SQL I do the following:
```sql
CAST(conv(hex(unbase64(encode({{ column_name }},'utf-8'))), 16, 10) / pow(10,{{ dec_scale }}) AS DECIMAL({{ dec_precision }},{{ decimal_places }}))
```

If there a way to override this or provide a custom function to skip if the type for the field is a string instead of bytes for logicalType decimal?

I notice something similar I think is done for logicalType timestamp-mills as we are sent those as a LONG rather than a date and they validate and allow conversion ok.

Thanks

**Comment by scottbelden** [comment]
The way logical types are intended to work is that the underlying data should be in the underlying basic avro type and the library is responsible for converting that to the more user friendly logical type.

In the case of the `timestamp-millis`, the schema looks like this: `{"type": "long", "logicalType": "timestamp-millis"},`. This means that the data itself is stored as an avro long, and then the library will convert that to a datetime class.

For logical type decimals, the underlying avro type is supposed to be `bytes` (as seen in the schema you posted) and so the converter in this library expects bytes, not a string like `D0JA`.

However, one way that you might be able to get around this is to create a custom decoder. You can see an example of how this is done here: https://fastavro.readthedocs.io/en/latest/logical_types.html#custom-logical-types

In your case, the custom decoder function would look something like this:

```python
def decode_string_as_datetime(data, writer_schema, reader_schema):
    from decimal import Context
    import base64
    b_data = base64.b64decode(data)
    decimal_context = Context()

    scale = writer_schema.get("scale", 0)
    precision = writer_schema["precision"]

    unscaled_datum = int.from_bytes(data, byteorder="big", signed=True)

    decimal_context.prec = precision
    return decimal_context.create_decimal(unscaled_datum).scaleb(
        -scale, decimal_context
    )
```

And your schema would be something like:

```
 {
   "name": "value",
   "type": {
     "logicalType": "customdecimal",
     "precision": 18,
     "scale": 5,
     "type": "string"
   }
 }
```

Let me know if that helps or if I misunderstood.

**Comment by pixie79** [comment]
Thanks, I think that is exactly what I am after 

will give it a test out

**Comment by scottbelden** [comment]
I'm going to close this. If something is still not working as expected then feel free to re-open or make a new issue.
