### ISSUE TITLE
Schema Failed - DateAndDateTime2Choice

### ISSUE THREAD

**Issue by pixie79** [fastavro/fastavro#671]
Hi,

I have a schema which is defining the following:

```
 {
   "doc": "The service timestamp value associated with the commit point in the platform database giving rise to the INSERT operation recorded in 'milliseconds since epoch' format",
   "name": "created_date",
   "type": {
     "logicalType": "timestamp-millis",
     "type": "long"
   }
 },
```

When I give it the following value 1665408385179, I get the following error 'Schema check failed DateAndDateTime2Choice'

Do you happen to know what the issue might be?

Thanks

**Comment by scottbelden** [comment]
I don't think this library produces an error like that. Can you post a script that produces the error?

**Comment by scottbelden** [comment]
Instead of:

```python
    try:
        validate(msg, parsed_schema)
        logger.debug(f'MESSAGE passed AVRO validation')
    except Exception as err:
        raise RuntimeError(f'ERROR MESSAGE Schema check failed {str(err)}')
```

Can you just change it to:

```python
validate(msg, parsed_schema)
```

And post the error?

**Comment by pixie79** [comment]
I am wondering if this relates to our custom schema. I have cut taken out the try loop and got the following error:

"level":"ERROR","location":"log_uncaught_exception_hook:760","message"
.....
\"type\": \"record\"\n}\n","exception_name":"UnknownType"}


I cant post the whole message as it is very large, and part of the schema is sensitive.


I reduced the script to just validate keeping it simple as :

```
import fastavro
from aws_lambda_powertools import Logger
from fastavro.read import schemaless_reader
from fastavro.schema import parse_schema
from fastavro.validation import validate
from fastavro.write import schemaless_writer


logger = Logger(log_uncaught_exceptions=True, level='DEBUG')


def encode_string_as_b64decimal(data, *args):
    return data


def decode_string_as_b64decimal(data, schema, *args):
    import base64
    from decimal import Context
    b_data = base64.b64decode(data)
    logger.debug(f'B64DECIMAL {b_data=}')
    decimal_context = Context()
    scale = schema.get('scale', 0)
    logger.debug(f'B64DECIMAL {scale=}')
    precision = schema['precision']
    logger.debug(f'B64DECIMAL {precision=}')
    unscaled_datum = int.from_bytes(b_data, byteorder='big', signed=True)
    logger.debug(f'B64DECIMAL {unscaled_datum=}')
    decimal_context.prec = precision
    result = decimal_context.create_decimal(unscaled_datum).scaleb(
        -scale, decimal_context
    )
    logger.debug(f'B64DECIMAL {result=}')
    return str(result)


fastavro.write.LOGICAL_WRITERS['string-b64decimal'] = encode_string_as_b64decimal
fastavro.read.LOGICAL_READERS['string-b64decimal'] = decode_string_as_b64decimal

with open('cards-posting-event-v001.avsc') as s:
    parsed_schema = parse_schema(s.read())

avro_data = {<PAYLOAD_HERE>}


validate(avro_data, parsed_schema)

```

Is it that validate does not know about the LOGICAL_Reader/Writer

**Comment by scottbelden** [comment]
Is it possible to use the [anonymize_schema utility](https://fastavro.readthedocs.io/en/latest/utils.html#fastavro.utils.anonymize_schema) and send me the result of that schema after verifying that it doesn't contain anything sensitive?

**Comment by pixie79** [comment]
I got an error trying that as well which i think is probably from the same cause :)

https://gist.github.com/pixie79/e9f68b816611d5e4553ac68b339a8afc

**Comment by scottbelden** [comment]
It looks like the error is in the parsing (before it gets to validate). Looking at your example you have:

```python
with open('cards-posting-event-v001.avsc') as s:
    parsed_schema = parse_schema(s.read())
```

But `parse_schema` expects a dictionary object for the schema, not a string. So you probably want to do something like:

```python
with open('cards-posting-event-v001.avsc') as s:
    parsed_schema = parse_schema(json.load(s))
```

**Comment by pixie79** [comment]
Ah, lol that's much better :)

validate it a bit happier in my cut-down script as well now. That will teach me to cut and paste quickly out of my module.

I think I have found the culprit as I now get the following error when doing validate:

```
"fields": [
   {
     "default": null,
     "name": "cardPresent",
     "type": [
       "null",
       "boolean"
     ]
   }
```

**Comment by scottbelden** [comment]
Are you doing `json.load` with your data payload as well? This sounds like you have a JSON data payload that isn't being parsed correctly. Because `true` is the value in JSON where as `True` is the constant in python.

**Comment by pixie79** [comment]
Ok I think I have located the issue. It must be with the conversion of the Lambda payload (which is a JSON_PAYLOAD) being passed through somehow it breaking before passing to validate on some data types.

Thanks

**Comment by scottbelden** [comment]
Oh nice. I was scratching my head as it is a bit hard to debug without the actual schema and data objects. I'm glad you were able to figure out it.
