### ISSUE TITLE
Default type enforcement should be relaxed for int->float

### ISSUE THREAD

**Issue by msinto93** [fastavro/fastavro#673]
Following the changes in PR #650, this now fails

```
schema = {
    "type": "record",
    "name": "PyType",
    "fields": [
        {
            "name": "field_a",
            "type": "float",
            "default": 1
        }
    ],
    "namespace": "test_avro_schema",
    "doc": "My PyType"
}
fastavro.parse_schema(schema)
```
with the following error
```
fastavro._schema_common.SchemaParseException: Default value <1> must match schema type: float
```
While I appreciate the default type enforcement is the correct thing to do, this should be relaxed to allow `int` default values to be allowed for `float` (or `double`) types.

It is common for round floats (e.g. `1.0`) in schemas to be cast to ints (`1`) meaning schema parsing then fails. For example, this casting happens when we upload a schema to our Kafka Schema Registry, then when the application pulls the schema from the registry and tries to parse with `fastavro.parse_schema()` we get the above error.

**Comment by faph** [comment]
Just to add here, Avro schemas are defined in JSON. JSON does not distinguish between "float" and "integer" numbers, it's just a number. Therefore it will be up to applications to parse this as Python native types as required.

While fastavro could just allow both Python `int` and `float` types for Avro `float` and `double` schemas, during reader-writer schema resolution any missing field values should of course be substituted with a default value of the correct type, i.e. `float` for Avro `float`/`double`.

**Comment by scottbelden** [comment]
Sorry about that. I think this was resolved in https://github.com/fastavro/fastavro/pull/670 but it looks like I haven't created a new release since that PR.

I'll try to get a new release out shortly.

**Comment by scottbelden** [comment]
Version 1.7.1 should be out. If it doesn't resolve this feel free to re-open.

**Comment by faph** [comment]
Awesome @scottbelden !
