### ISSUE TITLE
Optionally support Jackson encoded nonfinite doubles (NaN, +Infinity, -Infinity) as default values

### ISSUE THREAD

**Issue by keithks** [fastavro/fastavro#674]
Hi,

The official Avro implementation has had different positions on whether nonfinite doubles are supported in schemas/json encoding, see: https://issues.apache.org/jira/browse/AVRO-972 and https://issues.apache.org/jira/browse/AVRO-1466.  As a result, in our systems we do have some schemas served from Confluent's schema registry that contains non-finite default for doubles encoded by Jackson.

Would it be possible to support these values when specified as default value for floats in fastavro, perhaps as an option?   We would like to use the schema validation tools in fastavro but cannot use 1.7.0+ because of the problems above.

Thanks!
Keith

**Comment by scottbelden** [comment]
So the idea is be able to do have a schema like the following:

```
    schema = {
        "namespace": "namespace",
        "name": "name",
        "type": "record",
        "fields": [
            {"name": "field_1", "type": "float", "default": "NaN"},
        ],
    }
```

Would you be expecting to write avro binary? Or just avro JSON?

**Comment by keithks** [comment]
We want to write Avro binary from that schema.  Don't foresee to write any Avro JSON in our use cases.

**Comment by scottbelden** [comment]
I think https://github.com/fastavro/fastavro/pull/675 should fix this issue. I'm curious to know if in the past when you used this default if the default was ever actually needed. I'm pretty sure this library would have raised an exception because it would have tried to write `"NaN"` as a string when it actually needed the `float("NaN")` value.

**Comment by keithks** [comment]
Hi, thanks for the quick turnaround, and I think the fix looks good and should work for us.  For writing, we always asked users to provide values so you are right in that we never used defaults there.  I don't recall whether the string NaN passed through the read path in fastavro as our code used to use the writer schema from the Confluent Schema Registry to decode for a long time, but if it did I suspect users would have re-casted to a float like the fix does but outside the library.
