### ISSUE TITLE
aarch linux wheels (again?)

### ISSUE THREAD

**Issue by dave-shawley** [fastavro/fastavro#678]
I recently tried to pip install on an Alpine distribution and it fell back to doing a source install which was painful (cross platform build).  I think that [the wildcard in "build_linux.yml"](https://github.com/fastavro/fastavro/blob/0af9c80ade695f0b945d189d7b973ab55aba35da/.github/workflows/build_linux.yml#L64) is at fault.  When I manually build the wheel on an Alpine arm64 container, the resulting wheel is named "fastavro-x.y.z-cp31-cp311-linux_aarch64.whl".

Should the wildcard be "dist/*-linux*.whl" instead of "dist/*-manylinux*.whl"?  I think that it should be but I'm not sure if there is a difference between building with cibuildwheel versus `python -m build --wheel` on the target platform.

**Comment by dave-shawley** [comment]
Hmm... it looks like yarl is building for musllinux:
```
% docker run --rm -it --platform linux/x86_64 --entrypoint /bin/sh python:3.11-alpine3.16
/ # pip install yarl
Collecting yarl
  Downloading yarl-1.8.2-cp311-cp311-musllinux_1_1_x86_64.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.8/246.8 kB 4.6 MB/s eta 0:00:00
Collecting multidict>=4.0
  Downloading multidict-6.0.4-cp311-cp311-musllinux_1_1_x86_64.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.3/137.3 kB 13.9 MB/s eta 0:00:00
Collecting idna>=2.0
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 8.7 MB/s eta 0:00:00
Installing collected packages: multidict, idna, yarl
Successfully installed idna-3.4 multidict-6.0.4 yarl-1.8.2
/ #
```
That does use musllinux as the tag.  I haven't looked at their build pipeline.

Looks like the same tag is used for arm as well:
```
% docker run --rm -it --platform linux/arm64 --entrypoint /bin/sh python:3.11-alpine3.16
/ # pip install yarl
Collecting yarl
  Downloading yarl-1.8.2-cp311-cp311-musllinux_1_1_aarch64.whl (243 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.9/243.9 kB 3.4 MB/s eta 0:00:00
Collecting multidict>=4.0
  Downloading multidict-6.0.4-cp311-cp311-musllinux_1_1_aarch64.whl (141 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.0/141.0 kB 2.5 MB/s eta 0:00:00
Collecting idna>=2.0
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 2.7 MB/s eta 0:00:00
Installing collected packages: multidict, idna, yarl
Successfully installed idna-3.4 multidict-6.0.4 yarl-1.8.2
/ #
```

I guess that the wildcard should be something like `dist/*-*linux*.whl`.  Then we just need to tweak the image building process to generate musllinux tagged versions and they will get uploaded?

**Comment by scottbelden** [comment]
I'll make a new 1.7.3 release with the musllinux wheel shortly.
