### ISSUE TITLE
Support `cramjam` codec package as an alternative to `python-snappy`

### ISSUE THREAD

**Issue by kveretennicov** [fastavro/fastavro#682]
`python-snappy` is taking a long time to release wheels for Python 3.11 (https://github.com/andrix/python-snappy/issues/124).

`fastavro` could support https://pypi.org/project/cramjam as an alternative implementation for `snappy` and possibly other codecs.

**Comment by scottbelden** [comment]
That looks like a good alternative. I'll try to put that in as an option, or you can feel free to submit a PR if you'd like to.

**Comment by askepen** [comment]
Any update on this?

**Comment by scottbelden** [comment]
[I had created a branch to try to do this](https://github.com/fastavro/fastavro/compare/master...issue682) and some tests were failing but I must have got pulled away and never came back. Let me see if I can re-vitalize that branch and remind myself what the issue was.
