### ISSUE TITLE
Understanding the use of schema in json_reader

### ISSUE THREAD

**Issue by JaimeArboleda** [fastavro/fastavro#688]
Hello, 

I am fairly new to apache Avro and this particular project. I will be receiving data in a serialized json format supporting an avro schema, and I'd like to know if the deserialization will respect the schema. 

To ask something concrete, for example, let's say that I have this simple schema: 

```python
schema = fastavro.parse_schema({
    "type": "record",
    "name": "root",
    "fields": [
        {
            "name": "some_date",
            "type": [
                "null",
                {
                    "type": "string",
                    "logicalType": "datetime2",
                },
            ],
        },
        {
            "name": "a_float",
            "type": [
                "null",
                {
                    "type": "float"
                }
            ]
        }


    ]
})
```

Now, let's imagine that I want to deserialize some json that has been sent.  

```python
json_str = '{"some_date": {"string": "2023-04-30T16:06:38.172940"}, "a_float": {"float": "ja"}}\n{"some_date": {"string": "2023-04-30T16:06:38.172943"}, "a_float": {"float": 4.2}}\n{"some_date": {"string": "2023-03-30T16:06:38.172943"}, "a_float": {"float": 4}}'
```

Then, if I try to read the result: 

```python
file_str = io.StringIO(json_str)
avro_reader = json_reader(file_str, schema)
for record in avro_reader:
    print(record)
```

I get: 

```bash
{'some_date': datetime.datetime(2023, 4, 30, 16, 6, 38, 172940), 'a_float': 'ja'}
{'some_date': datetime.datetime(2023, 4, 30, 16, 6, 38, 172943), 'a_float': 4.2}
{'some_date': datetime.datetime(2023, 3, 30, 16, 6, 38, 172943), 'a_float': 4}
```

Which is unexpected, because, in the first case, I would have expected an error (how a field that should be a float has been ingested with a string?), and in the third case, I would have expected a float conversion, so 4.0 instead of 4. 

From this example, I am guessing that the schema in json_reader is not used for validation and/or type conversion, which is something that I expected as a byproduct of this library. Is there any way of ensuring the that the types obtained after deserializing are what they should be, and even raise some error in case the conversion is not possible? 

For example (and that's why I included this field in the example), the `datetime` is converted from a string, which is really great. To do this, I followed the example in the documentation:

```python
def encode_datetime_as_string(data, *args):
    return datetime.isoformat(data)

def decode_string_as_datetime(data, *args):
    return datetime.fromisoformat(data)

fastavro.write.LOGICAL_WRITERS["string-datetime2"] = encode_datetime_as_string
fastavro.read.LOGICAL_READERS["string-datetime2"] = decode_string_as_datetime
``` 

Maybe, there is a way of casting values to floats, for instance, and controlling this part in a more fine grained way. 

Thanks in advance.

**Comment by scottbelden** [comment]
These are great points. We do have validation option, but it is only available when writing, not reading. I think it would be a good addition to add the same option for reading, but that's probably not an easy change and something that probably won't get implemented that soon.

---

You could do as you mentioned and enforce some of this via the custom logical types and an example would look like this:

```python
import fastavro
from fastavro import json_reader

import io

def encode_float_as_validated(data, *args):
    if not isinstance(data, float):
        raise Exception("not a float")
    return data

def decode_validated_float(data, *args):
    try:
        return float(data)
    except Exception:
        raise ValueError(f"Could not cast {data} to float")

fastavro.write.LOGICAL_WRITERS["float-validated_float"] = encode_float_as_validated
fastavro.read.LOGICAL_READERS["float-validated_float"] = decode_validated_float


schema = fastavro.parse_schema({
    "type": "record",
    "name": "root",
    "fields": [
        {
            "name": "some_date",
            "type": [
                "null",
                {
                    "type": "string",
                    "logicalType": "datetime2",
                },
            ],
        },
        {
            "name": "a_float",
            "type": [
                "null",
                {
                    "type": "float",
                    "logicalType": "validated_float",
                }
            ]
        }


    ]
})

json_str = '{"some_date": {"string": "2023-04-30T16:06:38.172940"}, "a_float": {"float": "ja"}}\n{"some_date": {"string": "2023-04-30T16:06:38.172943"}, "a_float": {"float": 4.2}}\n{"some_date": {"string": "2023-03-30T16:06:38.172943"}, "a_float": {"float": 4}}'

file_str = io.StringIO(json_str)
avro_reader = json_reader(file_str, schema)
for record in avro_reader:
    print(record)
```

The problem with that is that is that if you can't control the schema (say it comes from somewhere else) then that won't help.

---

Another option to improve the validation (specifically for the case of the json_reader) would be to implement a custom JSON decoder. For example:

```python
import fastavro
from fastavro import json_reader
from fastavro.io.json_decoder import AvroJSONDecoder
from fastavro.io.symbols import Float

import io

class CustomJSONDecoder(AvroJSONDecoder):
    def read_float(self):
        symbol = self._parser.advance(Float())
        value = self.read_value(symbol)
        try:
            return float(value)
        except Exception:
            raise ValueError(f"Could not cast {value} to float")


schema = fastavro.parse_schema({
    "type": "record",
    "name": "root",
    "fields": [
        {
            "name": "some_date",
            "type": [
                "null",
                {
                    "type": "string",
                    "logicalType": "datetime2",
                },
            ],
        },
        {
            "name": "a_float",
            "type": [
                "null",
                {
                    "type": "float"
                }
            ]
        }


    ]
})

json_str = '{"some_date": {"string": "2023-04-30T16:06:38.172940"}, "a_float": {"float": "ja"}}\n{"some_date": {"string": "2023-04-30T16:06:38.172943"}, "a_float": {"float": 4.2}}\n{"some_date": {"string": "2023-03-30T16:06:38.172943"}, "a_float": {"float": 4}}'

file_str = io.StringIO(json_str)
avro_reader = json_reader(file_str, schema, decoder=CustomJSONDecoder)
for record in avro_reader:
    print(record)

```

You'd have to look at the source code to see the appropriate functions to overload, but that's probably the fastest workaround until a proper reader validation could be implemented.

**Comment by JaimeArboleda** [comment]
Thanks a lot, those are great suggestions! I will try them. 

I have a further question. In addition to casting and validating types, we want the tool to be very fast, because the system will be exposed in real time. From what I saw in the source code, many things are written in Cython for achieving speed. Do you think that I should try to use Cython to not to create a big overhead?

**Comment by scottbelden** [comment]
This library is written so that it uses cython under the hood (when running in a CPython interpreter). Your code does not need to use cython to make use of the cython code in this library. So it's really up to you on if you want to use cython for your code.

**Comment by JaimeArboleda** [comment]
Ok, I know nothing about cython. My concern was that, if I add custom functions for deserializing, as you suggested, and those are written in pure Python, I might see a big drop in performance... Thanks for the answer. 

Do you want me to close the issue, or do you prefer to leave it open for future implementation?

**Comment by scottbelden** [comment]
> Do you want me to close the issue, or do you prefer to leave it open for future implementation?

I created a new issue to track the feature request (validation when reading files) so I'm going to close this one.
