### ISSUE TITLE
Append writer is inefficient

### ISSUE THREAD

**Issue by bpburns** [fastavro/fastavro#689]
I want to use fastavro to write large avro files where all of the records to be written cannot be held in memory at once. Calling `fastavro.writer` seems to atomically write to a file with every call. It would be convenient to be able to hold a file open for the whole duration of the writing process and get the benefits of compression and reduced header/sync marker overhead. Here's an example showing writing 100,000 records to a single file with multiple approaches:

- 100k records where records are appended individually without compression: 2.24 MB
- 100k records where records are appended individually and compression is used: 2.71 MB
- 100k records where records are written in a single step without compression: 537 KB
- 100k records where records are written in a single step with compression: 2.92 KB

| Strategy | Compression | File Size |
|----------|-------------|-----------|
| Append   | No          | 2.24 MB   |
| Append   | Yes         | 2.71 MB   |
| Atomic   | No          | 537 KB    |
| Atomic   | Yes         | 2.92 KB   |

```
import fastavro

schema = {
    "type": "record",
    "name": "test_schema",
    "fields": [
        {"name": "foo", "type": "string"}
    ]
}

records = [{'foo': 'bar'}, {'foo': 'foobar'}]

APPEND_FILE_NO_COMPRESSION = 'test_avro_append_no_compression.avro'
APPEND_FILE_COMPRESSION = 'test_avro_append_compression.avro'
SINGLE_FILE_NO_COMPRESSION = 'test_avro_single_no_compression.avro'
SINGLE_FILE_COMPRESSION = 'test_avro_single_compression.avro'

records_list = []
for x in range(50000):
    records_list.extend(records)

with open(APPEND_FILE_NO_COMPRESSION, 'a+b') as outfile:
    for record in records_list:
        fastavro.writer(fo=outfile, schema=schema, records=[record])

with open(APPEND_FILE_COMPRESSION, 'a+b') as outfile:
    for record in records_list:
        fastavro.writer(fo=outfile, schema=schema, records=[record], codec='deflate')

with open(SINGLE_FILE_NO_COMPRESSION, 'wb') as outfile:
    fastavro.writer(fo=outfile, schema=schema, records=records_list)

with open(SINGLE_FILE_COMPRESSION, 'wb') as outfile:
    fastavro.writer(fo=outfile, schema=schema, records=records_list, codec='deflate')
```

Am I missing something in the docs or source? I'd like to be able to do something like this and get the benefits of speed and compression:

```
unmanageably_large_list_of_records = [...]
with open('outfile.avro', 'wb') as outfile:
    writer = fastavro.writer(...)
    for record in unmanageably_large_list_of_records:
        writer.write(record)
```

**Comment by scottbelden** [comment]
As long as you supply some sort of iterable as the `records` argument, it should work. You mentioned the list of records is too large to hold in memory, so if you can give it something like a generator that yields each record, you should be good. Here's an example:

```python
import fastavro

schema = {
    "type": "record",
    "name": "test_schema",
    "fields": [
        {"name": "foo", "type": "string"}
    ]
}

record = {'foo': 'bar'}

SINGLE_FILE_COMPRESSION = 'test_avro_single_compression.avro'

def gen_next_record():
    for _ in range(5):  # do something to get the next record
        yield record

generator = gen_next_record()

with open(SINGLE_FILE_COMPRESSION, 'wb') as outfile:
    fastavro.writer(fo=outfile, schema=schema, records=generator, codec='deflate')

```

**Comment by bpburns** [comment]
Okay, thanks!
