### ISSUE TITLE
does fastavro support bytes Primitive Type?

### ISSUE THREAD

**Issue by c0b** [fastavro/fastavro#69]
I'm using another language avro library writing some avro files with `bytes` field, I believe the avro files were written correctly because bigquery can load it successfully (https://cloud.google.com/bigquery/loading-data#loading_avro_files)

```json
      {
       "type": "bytes", 
       "name": "SenderIP"
      }, 
```

http://avro.apache.org/docs/1.8.1/spec.html

however, when I want to use the standard python `avro` or this `fastavro` as command line tool to view it, it results a crash like this in utf-8:

```py
{
    "senderInfo": {
        "SenderIP": Traceback (most recent call last):
  File "./.local/bin/fastavro", line 11, in <module>
    sys.exit(main())
  File "/home/.../.local/lib/python2.7/site-packages/fastavro/__main__.py", line 55, in main
    json_dump(record, indent)
  File "/home/.../.local/lib/python2.7/site-packages/fastavro/six.py", line 45, in py2_json_dump
    json.dump(obj, stdout, indent=indent, encoding=_outenc)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
  File "/usr/lib/python2.7/json/encoder.py", line 233, in _encoder
    o = o.decode(_encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x87 in position 2: invalid start byte
```

or this if I unset LANG to utf-8, it defaults to `ascii`

```py
{
    "senderInfo": {
        "SenderIP": Traceback (most recent call last):
  File "./.local/bin/fastavro", line 11, in <module>
    sys.exit(main())
  File "/home/.../.local/lib/python2.7/site-packages/fastavro/__main__.py", line 55, in main
    json_dump(record, indent)
  File "/home/.../.local/lib/python2.7/site-packages/fastavro/six.py", line 45, in py2_json_dump
    json.dump(obj, stdout, indent=indent, encoding=_outenc)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
  File "/usr/lib/python2.7/json/encoder.py", line 233, in _encoder
    o = o.decode(_encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x87 in position 2: ordinal not in range(128)
```

I can confirm when my older code generated the AVRO files without the SenderIP bytes field, the avro / fastavro was able to decode; so the bytes field could be the one that fastavro doesn't understand?

**Comment by tebeka** [comment]
Thanks for reporting. I'll try to have a look soon (on the road next 3 weeks)

**Comment by tebeka** [comment]
Can you share an example file?

**Comment by c0b** [comment]
these avro files were written in Go (with github.com/linkedin/goavro library) and consumed by BigQuery pretty well; that's why report to here fastavro or apache official avro python code isn't a priority, but I will simplify the code to make a cleansed avro file here with bytes.

**Comment by c0b** [comment]
@tebeka check this file https://filetea.me/n3wPFV70dkcR9xnDGJpa4zv9A (this ephemeral file sharing service may not keep it for long time)

```console
$ wget -P ./tmp --content-disposition https://filetea.me/n3wPFV70dkcR9xnDGJpa4zv9A
...
Length: 393
Saving to: ‘./tmp/encode-test1.avro’

encode-test1.avro                       100%
2017-05-26 21:58:16 (78.1 MB/s) - ‘./tmp/encode-test1.avro’ saved [393/393]
```

the jar avro-tools can handle it correctly:

```console
$ java -jar ./Downloads/avro-tools-1.8.2.jar tojson ./tmp/encode-test1.avro
{"station":"011990-99999","time":-619524000000,"temp":null,"bytes1":{"bytes":"\n\u0001ý\u0018"}}
{"station":"011990-99999","time":-619506000000,"temp":{"int":22},"bytes1":null}
{"station":"011990-99999","time":-619484400000,"temp":{"int":-11},"bytes1":null}
{"station":"012650-99999","time":-655531200000,"temp":{"int":111},"bytes1":null}
{"station":"012650-99999","time":-655509600000,"temp":{"int":78},"bytes1":null}
```

while, the python fastavro or official avro are not:

```console
$ fastavro < ./tmp/encode-test1.avro
{"station": "011990-99999", "bytes1": Traceback (most recent call last):
  File "./.local/bin/fastavro", line 11, in <module>
    sys.exit(main())
  File "../.local/lib/python2.7/site-packages/fastavro/__main__.py", line 55, in main
    json_dump(record, indent)
  File "../.local/lib/python2.7/site-packages/fastavro/six.py", line 45, in py2_json_dump
    json.dump(obj, stdout, indent=indent, encoding=_outenc)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
  File "/usr/lib/python2.7/json/encoder.py", line 233, in _encoder
    o = o.decode(_encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfd in position 2: invalid start byte

$ avro cat ./tmp/encode-test1.avro
panic: 'utf8' codec can't decode byte 0xfd in position 2: invalid start byte
```

it doesn't look like utf8 related, I've tried override `LANG=C` then it failed with 'ascii' codec

```console
➸ env LANG=C ./.local/bin/fastavro < ./tmp/encode-test1.avro
{"station": "011990-99999", "bytes1": Traceback (most recent call last):
  File "./.local/bin/fastavro", line 11, in <module>
    sys.exit(main())

  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
  File "/usr/lib/python2.7/json/encoder.py", line 233, in _encoder
    o = o.decode(_encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfd in position 2: ordinal not in range(128)
```

**Comment by c0b** [comment]
Update: this may not be a problem specific to `avro` or `fastavro`, but a generic Python Unicode problem when it tries to decode any byte string to Unicode, and it has existed for many years in Python2 without a proper solution,

1. https://stackoverflow.com/questions/11766231/json-dumps-unicodedecodeerror
2. http://farmdev.com/talks/unicode/
3. https://stackoverflow.com/questions/35086193/unicodedecodeerror-utf8-codec-cant-decode-byte-inside-a-dictionary
4. https://stackoverflow.com/questions/43925426/python-utf8-codec-cant-decode-byte-0xcd-in-position-0-invalid-continuation-b

```py
In [4]: json.dumps({"a": b"\1\2\34"})
Out[4]: '{"a": "\\u0001\\u0002\\u001c"}'

In [5]: json.dumps({"a": b"\1\2\34\xfb"})
---------------------------------------------------------------------------
[...]
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfb in position 3: invalid start byte

In [6]: json.dumps({"a": b"\1\2\34\xfb"}, encoding='latin1')
Out[6]: '{"a": "\\u0001\\u0002\\u001c\\u00fb"}'
```

To Unicode, the Python community's ultimate answer seems to be the Python3, however this json module just refuses to dump an object where a bytes string is nested inside:

```py
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.0.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import json

In [2]: json.dumps({"a": b"\1\2\34\xfb"})
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)

TypeError: b'\x01\x02\x1c\xfb' is not JSON serializable
```

**Comment by tebeka** [comment]
Thanks! I can't access the file (gone now?) Can you try an place it again? (maybe attach to this issue if it's not too big).

As for the JSON example - JSON protocol don't have a bytes object, just strings with *must* be UTF-8 encoded. The common use case it to base64encode the value and then send it.

**Comment by c0b** [comment]
https://file.io/dh5MhN (download one time only)

**Comment by c0b** [comment]
[encode-test1.avro.txt](https://github.com/tebeka/fastavro/files/1033596/encode-test1.avro.txt)

**Comment by c0b** [comment]
https://github.com/tebeka/fastavro/files/1033596/encode-test1.avro.txt (393 bytes) remove .txt

**Comment by c0b** [comment]
so the problem isn't fastavro/avro unable to handle bytes type in avro files, the avro-record-to-python-dict object decoding has no problem; but it's because **Python's `json.dump` unable to serialize a dict where has bytes string nested**.

**Comment by c0b** [comment]
so the problem isn't fastavro/avro unable to handle bytes type in avro files, the avro-record-to-python-dict decoding has no problem; but it's because Python's json.dump unable to serialize a dict where has bytes string nested.

**Comment by c0b** [comment]
https://github.com/tebeka/fastavro/files/1033596/encode-test1.avro.txt (393 bytes) (remove .txt)

so the problem isn't fastavro/avro unable to handle bytes type in avro files, the avro-record-to-python-dict decoding has no problem; but it's because Python's json.dump unable to serialize a dict where has bytes string nested.

**Comment by tebeka** [comment]
Yes. I might try to convert `bytes` to `str` before encoding, need to check if it breaks other things.

**Comment by tebeka** [comment]
I can probably add a custom `Encoder` class (see https://docs.python.org/3/library/json.html#basic-usage `cls` keyword). However need to profile for the impact on performance.

**Comment by c0b** [comment]
it's kind of python's problem: `byte string is not JSON serializable` applies to both avro.apache.org standard python avro library and this fastavro as well

because my avro schema has a fixed 4 bytes string to save IPv4Addr, both avro and fastavro can't print

    {
      "name" : "SenderIP",
      "type" : {
        "type" : "fixed",
        "name" : "IPv4Addr",
        "size" : 4
      }
    }

The java version avro-tools is able to print it, in this format, would you like to implement a similar printing of byte string? this will happen when printing (serializing to json) only, would not hurt conversion performance I think
https://mvnrepository.com/artifact/org.apache.avro/avro-tools

    "SenderIP" : "\n\u00026("

**Comment by scottbelden** [comment]
@c0b Do you know how the java library represents the byte string? Does it just decode it with utf-8 to get a regular string? I'm hoping to take a stab at implementing [an avro to json output](https://github.com/tebeka/fastavro/issues/33) fairly soon and I feel like this is going to come up there.
