### ISSUE TITLE
'utf-8' codec can't decode byte 0xe2 in position 37: invalid continuation byte

### ISSUE THREAD

**Issue by 91Eric** [fastavro/fastavro#695]
I use python3.10.6 and fastavro（1.1.0 and 1.7.4） read avro ，code is below
```
from fastavro import reader
import sys

def read(avro_path: str):
    with open(avro_path, 'rb') as fo:
        for record in reader(fo):
            yield record

records = read(sys.argv[1])
for record in records:
    print(record)
```
then i get errors following
```
Traceback (most recent call last):
  File "/home/a.py", line 10, in <module>
    for record in records:
  File "/home/a.py", line 6, in read
    for record in reader(fo):
  File "fastavro/_read.pyx", line 928, in _iter_avro_records
  File "fastavro/_read.pyx", line 749, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 620, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 706, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 288, in fastavro._read.read_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 37: invalid continuation byte
```

some other avro arise following  errors
```
Traceback (most recent call last):
  File "/home/.py", line 10, in <module>
    for record in records:
  File "/home/a.py", line 6, in read
    for record in reader(fo):
  File "fastavro/_read.pyx", line 928, in _iter_avro_records
  File "fastavro/_read.pyx", line 749, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 620, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 722, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 381, in fastavro._read.read_array
  File "fastavro/_read.pyx", line 749, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 620, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 706, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 288, in fastavro._read.read_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 15: invalid start byte

```
but I use  java tool: avro-tools-1.10.1.jar [https://repo1.maven.org/maven2/org/apache/avro/avro-tools/1.10.1/](url)
all is ok

and I read issue:https://github.com/fastavro/fastavro/issues/392
 do any one have ideas？ thanks

**Comment by 91Eric** [comment]
@scottbelden do you have any ideas? thanks

**Comment by 91Eric** [comment]
您好，您的来信我已收到.

**Comment by 91Eric** [comment]
@scottbelden thanks for your reply. yes，I can share my avro, we create them from network traffic and write usring libavro（c++ library）,but how can I share avro files to you?

**Comment by scottbelden** [comment]
> @scottbelden thanks for your reply. yes，I can share my avro, we create them from network traffic and write usring libavro（c++ library）,but how can I share avro files to you?

I think you can either drag the file on to one of these comments or you can create a gist (https://gist.github.com/) and share it with me.

**Comment by 91Eric** [comment]
> > @scottbelden thanks for your reply. yes，I can share my avro, we create them from network traffic and write usring libavro（c++ library）,but how can I share avro files to you?
> 
> I think you can either drag the file on to one of these comments or you can create a gist (https://gist.github.com/) and share it with me.
@scottbelden 
YES,drag the file is worked, here is avro files,readme.txt contains avro files and errinfos,Thanks
[avro.zip](https://github.com/fastavro/fastavro/files/11923954/avro.zip)

**Comment by scottbelden** [comment]
Thanks for the files. The problem is in some of the file names.

For example, in one of the messages, the file name decodes as `�红冲发票台账表样（报区公司备查）(未审计全).xlsx`. Notice how the first character is `�`, and that's because in the binary that's an invalid UTF-8 character.

The avro-tools package uses the `�` character when it has a problem, but this library just stops with an exception.

The real problem is somewhere on the encoding side (since it is encoding non-utf-8 characters. I suppose we could add an option to do the same as the avro-tools utility, but it wouldn't be the default behavior.

**Comment by 91Eric** [comment]
> Thanks for the files. The problem is in some of the file names.
> 
> For example, in one of the messages, the file name decodes as `�红冲发票台账表样（报区公司备查）(未审计全).xlsx`. Notice how the first character is `�`, and that's because in the binary that's an invalid UTF-8 character.
> 
> The avro-tools package uses the `�` character when it has a problem, but this library just stops with an exception.
> 
> The real problem is somewhere on the encoding side (since it is encoding non-utf-8 characters. I suppose we could add an option to do the same as the avro-tools utility, but it wouldn't be the default behavior.

Thanks for your work and reply.I think I understand the problem.
I read the library code:read_utf8 whree exception ocurs，the function use decode，
![image](https://github.com/fastavro/fastavro/assets/16057575/a54720d8-5953-4ea0-9e83-c075370a1886)
as you mentioned bellow:  suppose we could add an option to do the same as the avro-tools utility, but it wouldn't be the default behavior  .I don not kown if follow code can solve the problem for I am a newer in python, so I  I haven't figured out how to use cypthon yet
![image](https://github.com/fastavro/fastavro/assets/16057575/5df31100-d9cf-4dc2-b90e-85ef82f2a068)
Last,I wonder if you have a plan to solve the problem.Thanks  again

**Comment by 91Eric** [comment]
I use setup.py install from source using the code do not work too,the exception arise 
![image](https://github.com/fastavro/fastavro/assets/16057575/81d87a26-e5ff-4d80-9128-df45065b229f)
error  info
![image](https://github.com/fastavro/fastavro/assets/16057575/b76a508e-b059-4ce7-a449-11a26e4a328d)

**Comment by scottbelden** [comment]
@91Eric https://github.com/fastavro/fastavro/pull/696 should resolve this. With that change you will be able to do one of the following:

`reader = fastavro.reader(fp, handle_unicode_errors="replace")` if you want to get the `�` anytime there is a invalid unicode character

`reader = fastavro.reader(fp, handle_unicode_errors="ignore")` if you want to just ignore the invalid unicode character

**Comment by 91Eric** [comment]
> @91Eric #696 should resolve this. With that change you will be able to do one of the following:
> 
> `reader = fastavro.reader(fp, handle_unicode_errors="replace")` if you want to get the `�` anytime there is a invalid unicode character
> 
> `reader = fastavro.reader(fp, handle_unicode_errors="ignore")` if you want to just ignore the invalid unicode character

Thank you for providing a solution so efficiently，I read the code,  Can I simply understand that when reading data, provide the errors parameter to control the behavior when abnormal data is read？I will try the code in my avrofiles

**Comment by 91Eric** [comment]
> > @91Eric #696 should resolve this. With that change you will be able to do one of the following:
> > `reader = fastavro.reader(fp, handle_unicode_errors="replace")` if you want to get the `�` anytime there is a invalid unicode character
> > `reader = fastavro.reader(fp, handle_unicode_errors="ignore")` if you want to just ignore the invalid unicode character
> 
> Thank you for providing a solution so efficiently，I read the code, Can I simply understand that when reading data, provide the errors parameter to control the behavior when abnormal data is read？I will try the code in my avrofiles

@scottbelden  I use the code [https://github.com/fastavro/fastavro/pull/696](url) and use setup.py to update the fastavro in my machine，I try  two ways mentioned above,Both works well,That is great！
Last,I wonder if you have a plan to merge the code and  publish a new version,otherwsize I have to build from the code

**Comment by scottbelden** [comment]
@91Eric It should now be released as version 1.8.0

**Comment by 91Eric** [comment]
> @91Eric It should now be released as version 1.8.0
great！I use my ubutun try the new version，It works well，I want to know if [https://pypi.org/search/?q=fastavro&o=&c=Development+Status+%3A%3A+5+-+Production%2FStable&c=Operating+System+%3A%3A+POSIX+%3A%3A+Linux](url) any founed fastavro  version is supported in differents os if I can search it in the url，Because I will use it in different arch，such as x86_64 or arm64

**Comment by 91Eric** [comment]
@scottbelden I read your readme.md and find that only support python above Python3.8？In fact, I use fastavro 1.0.0 in python 3.6.8, It works well,or the old fastavro version  can use in old python?Thanks

**Comment by 91Eric** [comment]
> @scottbelden I read your readme.md and find that only support python above Python3.8？In fact, I use fastavro 1.0.0 in python 3.6.8, It works well,or the old fastavro version can use in old python?Thanks

I search in the url[https://mirrors.aliyun.com/pypi/simple/fastavro/](url) and found fastavro1.1.0 can run in python 3.6 but the newer version only support python3.7 and above,If there are any reason for newer version don not support python3.6

**Comment by scottbelden** [comment]
> https://pypi.org/search/?q=fastavro&o=&c=Development+Status+%3A%3A+5+-+Production%2FStable&c=Operating+System+%3A%3A+POSIX+%3A%3A+Linux

This library only officially supports versions of python that are actively maintained. [Python 3.6 went end of life in December 2021](https://devguide.python.org/versions/). However, it's possible that the current version is still compatible with Python 3.6.

**Comment by 91Eric** [comment]
> > https://pypi.org/search/?q=fastavro&o=&c=Development+Status+%3A%3A+5+-+Production%2FStable&c=Operating+System+%3A%3A+POSIX+%3A%3A+Linux
> 
> This library only officially supports versions of python that are actively maintained. [Python 3.6 went end of life in December 2021](https://devguide.python.org/versions/). However, it's possible that the current version is still compatible with Python 3.6.

I understand now, Thanks for your apply
