### ISSUE TITLE
Deserialization with reader schema. Compatibility validation failure.

### ISSUE THREAD

**Issue by SerikDM** [fastavro/fastavro#700]
Recently I ran into issue with deserialization using array of records withing record.

My schemas are look like:
```json
{
  "name": "Writer",
  "type": "record",
  "fields": [
    {"name": "foo", "type": {"type": "array", "items": {
      "name": "Item",
      "namespace": "Writer",
      "type": "record",
      "fields": [{"name": "field1", "type": "string"}]
    }}}
    {"name": "bar", "type": {"type": "array", "items": "Writer.Item"}}
  ]
}

{
  "name": "Reader",
  "type": "record",
  "aliases": ["Writer"],
  "fields": [
    {"name": "foo", "type": {"type": "array", "items": {
      "name": "Item",
      "namespace": "Reader",
      "type": "record",
      "aliases": ["Writer.Item"],
      "fields": [{"name": "field1", "type": "string"}]
    }}}
    {"name": "bar", "type": {"type": "array", "items": "Reader.Item"}}
  ]
}
```

Problem is child schema mentioned multiple times in parent, and it's full representation is given only once on first occurrence.
On second occurrence fastavro fails to validate compatibility, because it tries to validate compatibility of `"Reader.Item" vs "Writer.Item"` strings.

**Comment by scottbelden** [comment]
This is a good find. I tried to search in the avro repository and avro issues for a similar issue/use-case but was unable to find one. Currently we process the aliases on demand and don't keep a history of them so when it starts evaluating the `bar` field we have completely forgotten that `Reader.Item` is an alias to `Writer.Item`.

To me, the schema seems like it should be valid (though I don't have a good way to test with the Java implementation to verify), and so I think it's on our end to better keep track of previous aliases in the schema.

**Comment by scottbelden** [comment]
Resolved via https://github.com/fastavro/fastavro/pull/704
