### ISSUE TITLE
Loosen restrictions on default value; it no longer has to match the first schema

### ISSUE THREAD

**Issue by scottbelden** [fastavro/fastavro#723]
@scottbelden heads up, I think this has been fixed in avro, and it will be released in java for `0.12.0`. Rust already has this fix on `0.16.0`.

**resources**
- https://issues.apache.org/jira/browse/AVRO-3649
- https://github.com/apache/avro/pull/2503
- [yet to be released docs](https://github.com/apache/avro/blob/main/doc/content/en/docs/%2B%2Bversion%2B%2B/Specification/_index.md#:~:text=(Note%20that%20when%20a%20%5Bdefault%20value%5D(%7B%7B%3C%20ref%20%22%23schema%2Drecord%22%20%3E%7D%7D%20%22Schema%20record%22)%20is%20specified%20for%20a%20record%20field%20whose%20type%20is%20a%20union%2C%20the%20type%20of%20the%20default%20value%20must%20match%20with%20one%20element%20of%20the%20union)

_Originally posted by @woile in https://github.com/fastavro/fastavro/issues/649#issuecomment-1757080342_

**Comment by jvansanten** [comment]
Hi there! I happen to have a rather large collection of data that was serialized with fastavro < 1.7, with lots of union fields in the wrong order, e.g. `{"type": ["float", "null"], default: "null"}`. For a while I was keeping fastavro pinned to 1.6 in the projects that have to read these data, but this is slowly becoming untenable. From this conversation I gather that the intention is now to validate defaults against types in the union in order, and I have [a branch queued up that does just that](https://github.com/fastavro/fastavro/compare/master...jvansanten:fastavro:issue723).

The README says I should ask in an issue before filing a PR, so...should I file a PR for this?

**Comment by scottbelden** [comment]
Please do open a PR. There was a [work around for this that involved being able to pass in a valid reader schema](https://github.com/fastavro/fastavro/issues/676), but now that the spec is being changed it would be nice to just have it work out of the box.

**Comment by jvansanten** [comment]
Heh, the schema of the dataset alluded to in #676 looks veeeery familiar 😁. I couldn't get the reader_schema workaround to work for me, though, since `isinstance(float(None), float)` raises `TypeError` on `float(None)` rather than returning False, so I figured I might as well actually fix the problem.
