### ISSUE TITLE
`parse_schema` allows enum symbols with spaces

### ISSUE THREAD

**Issue by OffByOnee** [fastavro/fastavro#727]
According to the Avro spec for [enum symbols](https://avro.apache.org/docs/1.11.1/specification/#enums:~:text=this%20schema%20(optional).-,symbols,-%3A%20a%20JSON%20array), a symbol is not allowed to contain spaces:
>a JSON array, listing symbols, as JSON strings (required). All symbols in an enum must be unique; duplicates are prohibited. Every symbol must match the regular expression [A-Za-z_][A-Za-z0-9_]* (the same requirement as for [names](https://avro.apache.org/docs/1.11.1/specification/#names)).

This was partially addressed in the resolution to issue [551](https://github.com/fastavro/fastavro/issues/551), but misses some edge cases. For instance, the string symbol in the following example has spaces, but `parse_schema` doesn't raise an exception:
```python
import fastavro

if __name__ == '__main__':
    schema = {
        'type': 'record',
        'name': 'test_record',
          "fields": [
            {
                "name": "test_field",
                "type": {
                    "type": "enum",
                    "name": "Test_Field",
                    "symbols": ['string with spaces']
                }
            }
          ]
    }
    fastavro.parse_schema(schema)
```

This is due to the fact that [`re.match`](https://docs.python.org/3/library/re.html#re.match) is used in the [`_validate_enum_symbols`](https://github.com/fastavro/fastavro/blob/master/fastavro/_schema.pyx#L759) method, and `re.match` only enforces a match on the beginning of the string rather than the entire string. So in this case it matches `'string'` and stops. We can see this play out with a dumbed down example:
```python
import re
pattern = '[A-Za-z_][A-Za-z0-9_]*'
print(re.match(pattern=pattern, string='string with spaces'))
# <re.Match object; span=(0, 6), match='string'>
```
Changing `re.match` to [`re.fullmatch`](https://docs.python.org/3/library/re.html#re.fullmatch) yields the desired behavior:
```python
import re
pattern = '[A-Za-z_][A-Za-z0-9_]*'
print(re.fullmatch(pattern=pattern, string='string with spaces'))
# None
```

**Comment by scottbelden** [comment]
Thanks. Sounds like it should be a simple change. If you'd like to make a PR it should be pretty fast to get it merged in. Otherwise I think I can get to it soon.

**Comment by OffByOnee** [comment]
@scottbelden sure, I'll get started on it.
