### ISSUE TITLE
writing data in blocks

### ISSUE THREAD

**Issue by rkarthik29** [fastavro/fastavro#744]
I have a file that i am reading using block_reader, the file contains two blocks. I want to modify some records in the file and then write it back again, but i want to ensure the new file also has two blocks. How can this be achieved with fastavro.

**Comment by rkarthik29** [comment]
@scottbelden any thoughts on this

**Comment by scottbelden** [comment]
I tried to think about this, but I'm not sure if there is a good way to guarantee this at the moment. There's definitely no API we have that can modify block data in place. Typically modifying the middle means re-writing the whole thing. I will think on it a little more to see if I can think of some hacky way to make it work, but nothing is coming to mind right this second.

**Comment by rkarthik29** [comment]
import io
import fastavro
class Block:
    def __init__(self,writer_schema):
        self.bytes_=io.BytesIO()
        self.num_records=0
        self.schema=writer_schema
    
    def addrecord(self,record):
        fastavro.schemaless_writer(self.bytes_,self.schema,record)
        self.num_records+=1

with open("/tmp/test2.avro","wb") as f:
    writer=fastavro.write.Writer(f,schema=reader.writer_schema, codec=reader.codec)
    for block in reader:
        outblock=Block(reader.writer_schema)
        for record in block:
            outblock.addrecord(record)
        writer.write_block(outblock)
        writer.flush()

**Comment by rkarthik29** [comment]
this worked for me

**Comment by rkarthik29** [comment]
```
import io
import fastavro
class Block:
    def __init__(self,writer_schema):
        self.bytes_=io.BytesIO()
        self.num_records=0
        self.schema=writer_schema
    
    def addrecord(self,record):
        fastavro.schemaless_writer(self.bytes_,self.schema,record)
        self.num_records+=1

with open("/tmp/test2.avro","wb") as f:
    writer=fastavro.write.Writer(f,schema=reader.writer_schema, codec=reader.codec)
    for block in reader:
        outblock=Block(reader.writer_schema)
        for record in block:
            outblock.addrecord(record)
        writer.write_block(outblock)
        writer.flush()
```
the above changes worked for me and i will able to write in blocks

**Comment by rkarthik29** [comment]
@scottbelden i hacked something, dont think will work in middle of a file, but seemed to work

**Comment by rkarthik29** [comment]
did you see the solution i did, it seems simple, do you think that would work?  Will try this as well.

**Comment by scottbelden** [comment]
Sorry, I missed that. If that works for you then I would go with that.

**Comment by rkarthik29** [comment]
thanks @scottbelden
