### ISSUE TITLE
How to debug fastavro

### ISSUE THREAD

**Issue by BewareMyPower** [fastavro/fastavro#754]
I'm trying to debug an application that uses fastavro with ipdb. However, I found I cannot step into fastavro.

```
ipdb> c
False
> main.py(43)<module>()
     42 d = fastavro.schemaless_reader(io.BytesIO(buffer.getvalue()),
1--> 43                                writer_schema,
     44                                reader_schema)

ipdb> s
> main.py(44)<module>()
1    43                                writer_schema,
---> 44                                reader_schema)
     45 print(d)

ipdb> s
> main.py(42)<module>()
     41 
---> 42 d = fastavro.schemaless_reader(io.BytesIO(buffer.getvalue()),
1    43                                writer_schema,

ipdb> s
> main.py(45)<module>()
1    43                                writer_schema,
     44                                reader_schema)
---> 45 print(d)
```

As you can see, the `s` (step) command does not work. I also tried to set the breakpoint in the `_read_py.py` directly but it does not stop.

```
ipdb> b fastavro/_read_py.py:1253
Breakpoint 1 at /opt/homebrew/lib/python3.12/site-packages/fastavro/_read_py.py:1253
```

It seems something related to Cython and I don't have enough knowledge for it. Could anyone help for how to debug it?

**Comment by scottbelden** [comment]
Yeah, because the cython code compiles c-modules, you won't be able to use python's normal debugging on those. Probably the easiest way to get around this is to remove the `.so` files from your `/opt/homebrew/lib/python3.12/site-packages/fastavro/` directory. This will force it to use the python path which will work with the python debugger and should be identical.

**Comment by BewareMyPower** [comment]
Thanks. I will give it a spin.

**Comment by scottbelden** [comment]
I'm going to assume the suggestion worked and close this. Feel free to re-open if that is not the case.
