### ISSUE TITLE
FastAvro with generated classes? 

### ISSUE THREAD

**Issue by omer-shtivi** [fastavro/fastavro#755]
Hello,
I'm generating Python classes with avro-gen3
But I'm unable to work with fastavro when I pass the schema:
``` python
from generated_gen_code.schema_classes import MyClass, # This is a class generated by avro-gen3
from fastavro.utils import generate_one

entry: MyClass = MyClass()
schema = entry.RECORDED_SCHEMA.fields_dict
generate_one(schema=parsed_schema)
```
error:
```
authz_controller/transformers/avro.py:13: in write
    parsed_schema = parse_schema(schema)
fastavro/_schema.pyx:173: in fastavro._schema.parse_schema
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   KeyError: 'type'
```
Is there a known library which generates python classes which works with fastavro? I much prefer to work with strict types rather then dict/lists.
Or do is there someway to make the libraries play nicely together?

**Comment by scottbelden** [comment]
Are you able to post the schema from `entry.RECORDED_SCHEMA.fields_dict`?

In general, I don't know if there is a library that does what you are looking for. I believe this might be worth looking into: https://github.com/marcosschroh/dataclasses-avroschema (it uses fastavro under the hood so it should operate well with it).

**Comment by omer-shtivi** [comment]
Thanks,
I actually made it work.
```
    schema = entry.RECORD_SCHEMA.to_json()  # type: ignore
    parsed_schema = parse_schema(schema)  # type: ignore
```
but I think I will actually will switch to dataclasses-avroschema, looks like it's better supported
