### ISSUE TITLE
Single write support

### ISSUE THREAD

**Issue by omer-shtivi** [fastavro/fastavro#757]
Hello,
I have an application which writes avro file, but each time only a single row.
Looks like the avro writer only allow to write a iterable and not a single entity, and maybe there is other performance consideration.
Is there an option to have an api which is a single write to the file?

**Comment by scottbelden** [comment]
Just to clarify, are you writing a full avro file (with the schema header) with just a single record each time? If so, you can pass the `writer` an iterable of a single record (I often just take my single record and put it in a list or tuple).

**Comment by omer-shtivi** [comment]
This what I did , but I guess there is some performance considerations to that
The interpreter will have to build a list and iterate over it for each entry 
Also the schema will have to move around and I don't know when it compress (only when the file close ? Or whil writing ? ) but it might also cost

**Comment by scottbelden** [comment]
As for building the list, one other option would be to create some generator for the single record. I would assume that would be pretty free.

I'm not sure I understand the other comment about the schema moving around.

**Comment by omer-shtivi** [comment]
I mean that I need to hold the schema in memory, and I can't drop it because it not in use anymore after the initial header use.
The generator is good enough, I will close it.
