### ISSUE TITLE
Question: Fastavro write to a variable

### ISSUE THREAD

**Issue by omer-shtivi** [fastavro/fastavro#759]
Hi,
I have a need to serialize data to Avro, keep it in memory, and then upload it to a GCP bucket, is there a way instead of writing the data to file to write it to a variable?

**Comment by scottbelden** [comment]
Yes, look at the [second example](https://fastavro.readthedocs.io/en/latest/writer.html#fastavro-write) which shows how to use `BytesIO` to write to a file-like object in memory
