### ISSUE TITLE
`namespace` not included in `reader.writer_schema`

### ISSUE THREAD

**Issue by GeorgeVince** [fastavro/fastavro#762]
I ran into an issue whereby files re-written by `fastavro` were not visible in Redshift Spectum.

I narrowed down the reason and found out it is because `reader.writer_schema` does not have the `namespace` property.

The below script will create three files...
`email.avro` -> visible to Redshift Specturm
`re_written_email.avro` -> Not visible to Redshift Spectrum
`re_written_email_fixed.avro` -> visible to Redshift Spectum

You will see the following output:
```
email.avro: {'type': 'record', 'doc': 'A schema for storing emails', 'name': 'something.with.dots.email', 'fields': [{'name': 'email', 'type': 'string'}]}
re_written_email.avro Schema: {'type': 'record', 'doc': 'A schema for storing emails', 'name': 'something.with.dots.email', 'fields': [{'name': 'email', 'type': 'string'}]}
re_written_fixed_email.avro Schema: {'type': 'record', 'doc': 'A schema for storing emails', 'name': 'email', 'fields': [{'name': 'email', 'type': 'string'}], 'namespace': 'something.with.dots'}
```
Notice the schema has `name` which combines `name` and `namespace`, this becomes: 
```
'name': 'something.with.dots.email'
```

Sample Script:
```
def create_sample():
    # Define the schema for our Avro file
    schema = {
        'doc': 'A schema for storing emails',
        'name': 'email',
        'namespace': 'something.with.dots',
        'type': 'record',
        'fields': [
            {'name': 'email', 'type': 'string'}
        ],
    }

    records = [{'email': 'hello@example.com'}]

    file_name = 'email.avro'

    with open(file_name, 'wb') as out:
        fastavro.writer(out, schema, records)

def read_sample():
    with open('email.avro', 'rb') as f:
        reader = fastavro.reader(f)
        schema = reader.writer_schema
    print(f"email.avro: {schema}")

def rewrite_sample():
    location = 'email.avro'
    out_location = "re_written_" + location
    with open(location, 'rb') as input_file, open(out_location, 'wb') as output_file:
        reader = fastavro.reader(input_file)
        schema = reader.writer_schema
        records = [record for record in reader]
        fastavro.writer(output_file, schema, records)
    print(f"{out_location} Schema: {schema}")

def rewrite_sample_fixed():
    location = 'email.avro'
    out_location = "re_written_fixed_" + location
    with open(location, 'rb') as input_file, open(out_location, 'wb') as output_file:
        reader = fastavro.reader(input_file)
        schema = reader.writer_schema
        schema['namespace'] = ".".join(schema['name'].split('.')[:-1])
        schema['name'] = schema['name'].split('.')[-1]
        records = [record for record in reader]
        fastavro.writer(output_file, schema, records)
    print(f"{out_location} Schema: {schema}")

if __name__ == '__main__':
    create_sample()
    read_sample()
    rewrite_sample()
    rewrite_sample_fixed()
```

If I query my Redshift Spectrum table I get:
```
select *, "$path" from gv_test_new.example e 
```
|email|$path|
|-----|-----|
|hello@example.com|s3://BUCKET/example/email.avro|
|hello@example.com|s3://BUCKET/example/re_written_fixed_email.avro|

---
I'm not really sure if the cause here is `fastavro` or Redshift Spectrum?

**Comment by scottbelden** [comment]
I'm not familiar with Redshift Spectrum, so I may not be of much help.

When fastavro parses a schema, it does combine the `namespace` and `name` fields into the resulting `name` field and drops the `namespace`. This helps simplify some logic later in the code and is equivalent based on the avro specification.

If Redshift Spectrum is treating `{"name": "something.with.dots.email"}` differently than `{"name": "email", "namespace": "something.with.dots"}` then that feels like a bug on that end.

**Comment by GeorgeVince** [comment]
No problem, feel free to close.  I'll raise this on the AWS side.
Thanks Scott!
