### ISSUE TITLE
Inconsistent canonical form for schemas

### ISSUE THREAD

**Issue by sdjmchattie** [fastavro/fastavro#764]
I'd like to preface with the idea that perhaps `fastavro` is displaying correct behaviour, as it's not clear, but let me explain.

Given the following schema definition:

```
{
    "namespace": "com.example",
    "type": "record",
    "name": "CanonicalForm",
    "doc": "A demo of canonical form variations for custom types.",
    "fields": [
        {
            "name": "firstCard",
            "doc": "A custom type.",
            "type": {
                "name": "cardSuit",
                "type": "enum",
                "symbols": [
                    "CLUBS",
                    "DIAMONDS",
                    "HEARTS",
                    "SPADES"
                ]
            }
        },
        {
            "name": "secondCard",
            "doc": "Second instance of the custom type.",
            "type": "cardSuit"
        }
    ]
}
```

`fastavro` will generate the canonical form:

```
{"name":"com.example.CanonicalForm","type":"record","fields":[{"name":"firstCard","type":{"name":"com.example.cardSuit","type":"enum","symbols":["CLUBS","DIAMONDS","HEARTS","SPADES"]}},{"name":"secondCard","type":"com.example.cardSuit"}]}
```

which in isolation looks good.  But Apache's implementation of Avro in Ruby gives the canonical form:

```
{"name":"com.example.CanonicalForm","type":"record","fields":[{"name":"firstCard","type":{"name":"com.example.cardSuit","type":"enum","symbols":["CLUBS","DIAMONDS","HEARTS","SPADES"]}},{"name":"secondCard","type":"cardSuit"}]}
```

where the type in the `secondCard` does not have the namespace appended, but the original name in the `firstCard` does.  This seems more consistent with the [specifications for generating a canonical form](https://avro.apache.org/docs/1.11.1/specification/_print/#transforming-into-parsing-canonical-form) which only mentions adding namespaces to names, and not to types.  I suppose you could argue that the type in this case is a name!

The problem here is that the fingerprint used to validate that the correct schema is being retrieved from a registry is different between the two systems.  I suppose worse is that the Apache library for Avro in Python produces another canonical form and this produces a third variation of the fingerprint.  I haven't tried any other Apache libraries/packages in other languages.

**Comment by scottbelden** [comment]
Do you have an easy way of seeing what the Java output is as that tends to be the reference implementation? I tried getting it myself to check, but I was having trouble getting the environment set up in the few minutes that I tried

**Comment by sdjmchattie** [comment]
Thanks Scott. I had a feeling you would say the Java implementation was the reference. I will try getting that form when I get a chance but I haven't used Java in years at this point 😄

**Comment by scottbelden** [comment]
Thanks for going through the hoops of setting up the Java environment to check. I also stay quite far from Java (though I probably should have it set up just to check compatibility things like this).
