### ISSUE TITLE
fastavro does not validate schemas for compliance of type order for `default` type

### ISSUE THREAD

**Issue by lgo** [fastavro/fastavro#785]
According to the Avro spec, union types are expected to have the type of the `default` value be the first value in the type list. See:
https://avro.apache.org/docs/1.11.1/specification/#unions

> (Note that when a [default value](https://avro.apache.org/docs/1.11.1/specification/#schema-record) is specified for a record field whose type is a union, the type of the default value must match the first element of the union. Thus, for unions containing “null”, the “null” is usually listed first, since the default value of such unions is typically null.)

`fastavro` doesn't validate that condition, resulting in schemas like this to slide which other libraries that implement a more strict `avro` compliance will throw validation errors. In this case, `null` is not a `string`  (first type) so it is technically not in compliance. I faced this issue with some manually curated Avro schemas that passed validation with `fastavro`, but later failed when used alongside other systems.

```py
schema = """
{
    "type": "record",
    "name": "foo",
    "fields": [
        {
            "name": "bar",
            "type": [
                "string",
                "null"
            ],
            "default": null
        }
    ]
}
"""
schema_json = json.loads(schema)
from fastavro.schema import parse_schema

# Expected exception on parse, but it parses fine.
parse_schema(schema_json)
```

`fastavro` just validates that the `default` type at least corresponds to any permitted type, here: https://github.com/fastavro/fastavro/blob/4548e8cc2b00f179138629cc43109b6db961decb/fastavro/_schema_py.py#L385-L390

The official `avro` Python package also has a similar issue, and instead doesn't even validate the `default` type at all :/ - https://issues.apache.org/jira/browse/AVRO-3272

**Comment by scottbelden** [comment]
This is intentional. It was changed in https://github.com/fastavro/fastavro/pull/738 because the spec is changing to loosen the restriction and allow the default to match any value in the union: https://github.com/apache/avro/commit/1b78e69f6de50a511fb57fb275294168bbc49c24. That was merged a while ago, but they just haven't released 1.12 yet.

**Comment by joeyp-openai** [comment]
Got it, in this case there's no real issue then and thanks for letting me know about that! I unfortunately hit this with manually maintained Avro files validated by `fastavro` but interacting with systems that implement this constraint 🤷

**Comment by lgo** [comment]
Got it, in this case there's no real issue then and thanks for letting me know about that! I unfortunately hit this with manually maintained Avro files validated by `fastavro` but interacting with systems that implement this constraint so :shrug:
