### ISSUE TITLE
Documentation inside IDE does not show some arguments (fastavro.schemaless_reader)

### ISSUE THREAD

**Issue by sral85** [fastavro/fastavro#787]
I have the issue that locally some arguments of function are not properly shown in the documentation:
In my case the argument "return_named_true" of "fastavro.schemaless_reader" is not present.
Also mypy complaints about this argument and states that it is not present.
 
 Is it possible that the stubs file does not contain the relevant information (see https://github.com/fastavro/fastavro/blob/master/fastavro/_read.pyi#L75) while the source code does (https://github.com/fastavro/fastavro/blob/master/fastavro/_read.pyx#L1159)?

![image](https://github.com/user-attachments/assets/ce20ebdd-e9b4-4f12-a699-c6241e7a7286)

Thank you very much.

**Comment by scottbelden** [comment]
Thanks. https://github.com/fastavro/fastavro/pull/790 should fix this.

**Comment by sral85** [comment]
@scottbelden Thank you for taking are of this so fast.
