### ISSUE TITLE
Regression in write_union for non-record fields after resolving named schema

### ISSUE THREAD

**Issue by enifsieus** [fastavro/fastavro#795]
The change in https://github.com/fastavro/fastavro/pull/792 assumes that union members in named schemas are records, and forces record_type = 'record' after resolving the target schema.  This assumption does not hold for all schemas, and can e.g. force nullable enums to be subsequently treated as records.  Lacking 'fields' this causes a KeyError to be raised.

**Comment by enifsieus** [comment]
The easiest fix here seems to be to call extract_record_type(...) after resolving the target. I'm working on a test case to cover the regression and will open a pull request ASAP ... any other guidance is of course welcome.

**Comment by scottbelden** [comment]
Thanks. I forgot that named types are more than just records
